### ISSUE TITLE
hardhat-ethers.SignerWithAddress.signMessage broken on hardhat network

### ISSUE THREAD

**Issue by cytadela8** [NomicFoundation/hardhat#1972]
## Summary

Calling `signMessage` on a signer returned by `ethers.getSigners()` when using hardhat network results with following error:

```
     MethodNotFoundError: Method personal_sign not found
      at HardhatNetworkProvider._send (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:208:11)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async HardhatNetworkProvider.request (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:108:18)
      at async EthersProviderWrapper.send (node_modules/@nomiclabs/hardhat-ethers/src/internal/ethers-provider-wrapper.ts:13:20)
```

## Code

Test producing the above error:
```typescript
import { expect } from "chai";
import { ethers } from "hardhat";

describe("Test signing", function () {
  it("sign", async function () {
    const [account] = await ethers.getSigners();
    console.log(await account.signMessage("test"));
  });
});
```

Full repository with the test failing: https://github.com/cytadela8/hardhat-issue-sign-failed/

## Steps to reproduce

```bash
$ npm install hardhat
$ npx hardhat  # choose advanced project with typescript
$ vim test/index.ts   # Create a test as above
$ npx hardhat test  # Test fails with exception as above
```

**Comment by fvictorio** [comment]
Thanks for reporting this @cytadela8. This seems to be a change introduced in `ethers@5.5.0`, see [this issue](https://github.com/ethers-io/ethers.js/issues/1544). For the time being, a workaround is to downgrade to 5.4.x, although I understand that's not ideal. Alternatively, you can use this helper:

```ts
function sign(address: string, data: string) {
  return hre.network.provider.send(
    "eth_sign",
    [address, ethers.utils.hexlify(ethers.utils.toUtf8Bytes('foo'))]
  )
}

// ...

const [signer] = await ethers.getSigners()
const signed = await sign(signer.address, 'test')
```

I guess we should implement the `personal_sign` RPC method to fix this.
