### ISSUE TITLE
Cannot call function with gas limit on hardhat node

### ISSUE THREAD

**Issue by kigawas** [NomicFoundation/hardhat#2208]
```
ProviderError: Error: Transaction reverted and Hardhat couldn't infer the reason. Please report this to help us improve Hardhat.
    at HttpProvider.request (/Users/user/project/node_modules/hardhat/src/internal/core/providers/http.ts:49:19)
    at GanacheGasMultiplierProvider.request (/Users/user/project/node_modules/hardhat/src/internal/core/providers/gas-providers.ts:312:34)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

This occurs when specifying the gas limit:
```js
const factory = await ethers.getContractFactory("MyContract");
const contract = await factory.attach(ADDRESS);
await contract.connect(accounts[0]).func(...args, { gasLimit: 760000 });
```

**Comment by feuGeneA** [comment]
Can you provide more context for the problem you're experiencing? It would be helpful to have all of the files and folders from your hardhat project directory.

I tried to reproduce this but could not.  I created a new basic project, and modified the sample script to append the following lines to the `main()` method:

```js
  const contract = await Greeter.attach(greeter.address);
  const accounts = await hre.ethers.getSigners();
  const greeting = await contract.connect(accounts[0]).greet({ gasLimit: 760000 });
  console.log(`greeting returned from method: ${greeting}`);
```

And then when I execute the script it works as expected:
```console
$ yarn hardhat run scripts/sample-script.js 
yarn run v1.22.11
$ /home/gene/dev/hardhat-empty/node_modules/.bin/hardhat run scripts/sample-script.js
Deploying a Greeter with greeting: Hello, Hardhat!
Greeter deployed to: 0x5FbDB2315678afecb367f032d93F642f64180aa3
greeting returned from method: Hello, Hardhat!
Done in 1.64s.
```
