### ISSUE TITLE
Error HH11 when depending on a local npm package

### ISSUE THREAD

**Issue by RevCBH** [NomicFoundation/hardhat#2210]
I'm trying to move some contracts out of a project, into a shared package. When I remove the files from the project and change the imports to reference the package, I get:

```bash
Error HH11: An internal invariant was violated: Libraries should have both name and version, or neither one

HardhatError: HH11: An internal invariant was violated: Libraries should have both name and version, or neither one
    at assertHardhatInvariant (/home/ben/source/dfktools/node_modules/hardhat/src/internal/core/errors.ts:264:11)
    at new ResolvedFile (/home/ben/source/dfktools/node_modules/hardhat/src/internal/solidity/resolver.ts:42:27)
    at Resolver._resolveFile (/home/ben/source/dfktools/node_modules/hardhat/src/internal/solidity/resolver.ts:325:12)
    at async Resolver.resolveImport (/home/ben/source/dfktools/node_modules/hardhat/src/internal/solidity/resolver.ts:120:16)
    at async DependencyGraph._addDependenciesFrom (/home/ben/source/dfktools/node_modules/hardhat/src/internal/solidity/dependencyGraph.ts:171:26)
    at async DependencyGraph._addDependenciesFrom (/home/ben/source/dfktools/node_modules/hardhat/src/internal/solidity/dependencyGraph.ts:174:7)
    at async Function.createFromResolvedFiles (/home/ben/source/dfktools/node_modules/hardhat/src/internal/solidity/dependencyGraph.ts:13:7)
    at async SimpleTaskDefinition.action (/home/ben/source/dfktools/node_modules/hardhat/src/builtin-tasks/compile.ts:182:31)
    at async Environment._runTaskDefinition (/home/ben/source/dfktools/node_modules/hardhat/src/internal/core/runtime-environment.ts:217:14)
    at async Environment.run (/home/ben/source/dfktools/node_modules/hardhat/src/internal/core/runtime-environment.ts:129:14)
```

The docs for the error (https://hardhat.org/errors/#HH11) specifically suggest opening an issue.

**Comment by kanej** [comment]
Hey @RevCBH, thanks for opening the issue. Can we get more detail on the reproduction steps?

Specifically is the "reference package" in a monorepo, or how is the referencing being done?

**Comment by RevCBH** [comment]
It's a different git repo. The two projects are independent, but in the
same parent directory, so was a "file:../package" npm dependency.

The same package works when reference via GitHub with
"RevCBH/dfk-contracts" as the package specifier.

Very possible that I setup the npm package incorrectly or incompletely, I
was trying to crib from @openzeppelin/contracts

**Comment by fvictorio** [comment]
@RevCBH check the `package.json` of the package where those contracts are. This is not a common error, but when it happens it's because the `package.json` doesn't have a `version` field.

**Comment by alexandervantrijffel** [comment]
That solves it for me @fvictorio, thanks!
