### ISSUE TITLE
Failed to generate 2 stack traces

### ISSUE THREAD

**Issue by pcaversaccio** [NomicFoundation/hardhat#2227]
In order to reproduce the error you can simply run the tests from my repo here: https://github.com/pcaversaccio/create2deployer/blob/main/test/Create2.test.ts

This will produce the following 2 stack trace errors:
```bash
 deploy
      √ deploys a ERC1820Implementer from inline assembly code (65ms)
      √ deploys a ERC20Mock with correct balances (170ms)
      √ deploys a contract with funds deposited in the factory (246ms)
  hardhat:core:hardhat-network:node Could not generate stack trace. Please report this to help us improve Hardhat.
  hardhat:core:hardhat-network:node  TypeError: Cannot use 'in' operator to search for 'pc' in undefined
    at isEvmStep (C:\Dev\Blockchain\create2deployer\node_modules\hardhat\src\internal\hardhat-network\stack-traces\message-trace.ts:89:14)
    at ErrorInferrer._isConstructorInvalidArgumentsError (C:\Dev\Blockchain\create2deployer\node_modules\hardhat\src\internal\hardhat-network\stack-traces\error-inferrer.ts:972:19) 
    at ErrorInferrer.inferBeforeTracingCreateMessage (C:\Dev\Blockchain\create2deployer\node_modules\hardhat\src\internal\hardhat-network\stack-traces\error-inferrer.ts:142:14)     
    at SolidityTracer._getCreateMessageStackTrace (C:\Dev\Blockchain\create2deployer\node_modules\hardhat\src\internal\hardhat-network\stack-traces\solidityTracer.ts:126:27)        
    at SolidityTracer.getStackTrace (C:\Dev\Blockchain\create2deployer\node_modules\hardhat\src\internal\hardhat-network\stack-traces\solidityTracer.ts:52:19)
    at SolidityTracer._rawTraceEvmExecution (C:\Dev\Blockchain\create2deployer\node_modules\hardhat\src\internal\hardhat-network\stack-traces\solidityTracer.ts:201:38)
    at SolidityTracer._traceEvmExecution (C:\Dev\Blockchain\create2deployer\node_modules\hardhat\src\internal\hardhat-network\stack-traces\solidityTracer.ts:149:29)
    at SolidityTracer._getCallMessageStackTrace (C:\Dev\Blockchain\create2deployer\node_modules\hardhat\src\internal\hardhat-network\stack-traces\solidityTracer.ts:72:17)
    at SolidityTracer.getStackTrace (C:\Dev\Blockchain\create2deployer\node_modules\hardhat\src\internal\hardhat-network\stack-traces\solidityTracer.ts:56:19)
    at HardhatNode._manageErrors (C:\Dev\Blockchain\create2deployer\node_modules\hardhat\src\internal\hardhat-network\provider\node.ts:1773:41)
    at HardhatNode._gatherTraces (C:\Dev\Blockchain\create2deployer\node_modules\hardhat\src\internal\hardhat-network\provider\node.ts:1530:30)
    at async HardhatNode._mineBlockWithPendingTxs (C:\Dev\Blockchain\create2deployer\node_modules\hardhat\src\internal\hardhat-network\provider\node.ts:1650:23)
    at async HardhatNode.mineBlock (C:\Dev\Blockchain\create2deployer\node_modules\hardhat\src\internal\hardhat-network\provider\node.ts:459:16)
    at async EthModule._sendTransactionAndReturnHash (C:\Dev\Blockchain\create2deployer\node_modules\hardhat\src\internal\hardhat-network\provider\modules\eth.ts:1496:18)
    at async HardhatNetworkProvider.request (C:\Dev\Blockchain\create2deployer\node_modules\hardhat\src\internal\hardhat-network\provider\provider.ts:117:18)
    at async Web3HTTPProviderAdapter._sendJsonRpcRequest (C:\Dev\Blockchain\create2deployer\node_modules\@nomiclabs\hardhat-web3\src\web3-provider-adapter.ts:80:22) +0ms
  hardhat:core:hardhat-network:node Could not generate stack trace. Please report this to help us improve Hardhat.
  hardhat:core:hardhat-network:node  TypeError: Cannot use 'in' operator to search for 'pc' in undefined
    at isEvmStep (C:\Dev\Blockchain\create2deployer\node_modules\hardhat\src\internal\hardhat-network\stack-traces\message-trace.ts:89:14)
    at ErrorInferrer._isConstructorInvalidArgumentsError (C:\Dev\Blockchain\create2deployer\node_modules\hardhat\src\internal\hardhat-network\stack-traces\error-inferrer.ts:972:19) 
    at ErrorInferrer.inferBeforeTracingCreateMessage (C:\Dev\Blockchain\create2deployer\node_modules\hardhat\src\internal\hardhat-network\stack-traces\error-inferrer.ts:142:14)     
    at SolidityTracer._getCreateMessageStackTrace (C:\Dev\Blockchain\create2deployer\node_modules\hardhat\src\internal\hardhat-network\stack-traces\solidityTracer.ts:126:27)        
    at SolidityTracer.getStackTrace (C:\Dev\Blockchain\create2deployer\node_modules\hardhat\src\internal\hardhat-network\stack-traces\solidityTracer.ts:52:19)
    at SolidityTracer._rawTraceEvmExecution (C:\Dev\Blockchain\create2deployer\node_modules\hardhat\src\internal\hardhat-network\stack-traces\solidityTracer.ts:201:38)
    at SolidityTracer._traceEvmExecution (C:\Dev\Blockchain\create2deployer\node_modules\hardhat\src\internal\hardhat-network\stack-traces\solidityTracer.ts:149:29)
    at SolidityTracer._getCallMessageStackTrace (C:\Dev\Blockchain\create2deployer\node_modules\hardhat\src\internal\hardhat-network\stack-traces\solidityTracer.ts:72:17)
    at SolidityTracer.getStackTrace (C:\Dev\Blockchain\create2deployer\node_modules\hardhat\src\internal\hardhat-network\stack-traces\solidityTracer.ts:56:19)
    at HardhatNode._manageErrors (C:\Dev\Blockchain\create2deployer\node_modules\hardhat\src\internal\hardhat-network\provider\node.ts:1773:41)
    at HardhatNode._gatherTraces (C:\Dev\Blockchain\create2deployer\node_modules\hardhat\src\internal\hardhat-network\provider\node.ts:1530:30)
    at async HardhatNode.runCall (C:\Dev\Blockchain\create2deployer\node_modules\hardhat\src\internal\hardhat-network\provider\node.ts:535:20)
    at async EthModule._callAction (C:\Dev\Blockchain\create2deployer\node_modules\hardhat\src\internal\hardhat-network\provider\modules\eth.ts:353:9)
    at async HardhatNetworkProvider.request (C:\Dev\Blockchain\create2deployer\node_modules\hardhat\src\internal\hardhat-network\provider\provider.ts:117:18)
    at async Web3HTTPProviderAdapter._sendJsonRpcRequest (C:\Dev\Blockchain\create2deployer\node_modules\@nomiclabs\hardhat-web3\src\web3-provider-adapter.ts:80:22) +83ms
      √ fails deploying a contract in an existent address (255ms)
```

Environment:
- Hardhat `2.8.2`
- Nodejs `14.11.0`

**Comment by gzliudan** [comment]
I also encount this error:
```text
  hardhat:core:hardhat-network:node Could not generate stack trace. Please report this to help us improve Hardhat.
  hardhat:core:hardhat-network:node  Error: This shouldn't happen: a call trace has no functionJumpdest but has already jumped into a function
    at ErrorInferrer._getEntryBeforeFailureInModifier (/home/liudan/matrix/MatrixProtocol/node_modules/hardhat/src/internal/hardhat-network/stack-traces/error-inferrer.ts:1495:13)
    at ErrorInferrer._checkRevertOrInvalidOpcode (/home/liudan/matrix/MatrixProtocol/node_modules/hardhat/src/internal/hardhat-network/stack-traces/error-inferrer.ts:389:16)
    at ErrorInferrer._checkLastInstruction (/home/liudan/matrix/MatrixProtocol/node_modules/hardhat/src/internal/hardhat-network/stack-traces/error-inferrer.ts:573:44)
    at ErrorInferrer.inferAfterTracing (/home/liudan/matrix/MatrixProtocol/node_modules/hardhat/src/internal/hardhat-network/stack-traces/error-inferrer.ts:162:12)
    at SolidityTracer._rawTraceEvmExecution (/home/liudan/matrix/MatrixProtocol/node_modules/hardhat/src/internal/hardhat-network/stack-traces/solidityTracer.ts:211:61)
    at SolidityTracer._traceEvmExecution (/home/liudan/matrix/MatrixProtocol/node_modules/hardhat/src/internal/hardhat-network/stack-traces/solidityTracer.ts:149:29)
    at SolidityTracer._getCallMessageStackTrace (/home/liudan/matrix/MatrixProtocol/node_modules/hardhat/src/internal/hardhat-network/stack-traces/solidityTracer.ts:72:17)
    at SolidityTracer.getStackTrace (/home/liudan/matrix/MatrixProtocol/node_modules/hardhat/src/internal/hardhat-network/stack-traces/solidityTracer.ts:56:19)
    at HardhatNode._manageErrors (/home/liudan/matrix/MatrixProtocol/node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:1772:41)
    at HardhatNode._gatherTraces (/home/liudan/matrix/MatrixProtocol/node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:1529:30) +0ms
```
I'm using node v16.13.1 and hardhat v2.8.0

**Comment by Kokokokoka** [comment]
Using: hardhat v2.8.3 nodejs v16.13.1
```
2022-02-04T18:37:33.724Z hardhat:core:hardhat-network:node Could not generate stack trace. Please report this to help us improve Hardhat.
 Error: This shouldn't happen: a call trace has no functionJumpdest but has already jumped into a function
    at ErrorInferrer._getEntryBeforeFailureInModifier (/home/id0/src/neuron-options/node_modules/hardhat/src/internal/hardhat-network/stack-traces/error-inferrer.ts:1495:13)
    at ErrorInferrer._checkRevertOrInvalidOpcode (/home/id0/src/neuron-options/node_modules/hardhat/src/internal/hardhat-network/stack-traces/error-inferrer.ts:389:16)
    at ErrorInferrer._checkLastInstruction (/home/id0/src/neuron-options/node_modules/hardhat/src/internal/hardhat-network/stack-traces/error-inferrer.ts:573:44)
    at ErrorInferrer.inferAfterTracing (/home/id0/src/neuron-options/node_modules/hardhat/src/internal/hardhat-network/stack-traces/error-inferrer.ts:162:12)
    at SolidityTracer._rawTraceEvmExecution (/home/id0/src/neuron-options/node_modules/hardhat/src/internal/hardhat-network/stack-traces/solidityTracer.ts:211:61)
    at SolidityTracer._traceEvmExecution (/home/id0/src/neuron-options/node_modules/hardhat/src/internal/hardhat-network/stack-traces/solidityTracer.ts:149:29)
    at SolidityTracer._getCallMessageStackTrace (/home/id0/src/neuron-options/node_modules/hardhat/src/internal/hardhat-network/stack-traces/solidityTracer.ts:72:17)
    at SolidityTracer.getStackTrace (/home/id0/src/neuron-options/node_modules/hardhat/src/internal/hardhat-network/stack-traces/solidityTracer.ts:56:19)
    at SolidityTracer._rawTraceEvmExecution (/home/id0/src/neuron-options/node_modules/hardhat/src/internal/hardhat-network/stack-traces/solidityTracer.ts:201:38)
    at SolidityTracer._traceEvmExecution (/home/id0/src/neuron-options/node_modules/hardhat/src/internal/hardhat-network/stack-traces/solidityTracer.ts:149:29)
```

**Comment by vladikopl01** [comment]
I had the same issue as shown above.

```
hardhat:core:hardhat-network:node Could not generate stack trace. Please report this to help us improve Hardhat.
  hardhat:core:hardhat-network:node  Error: This shouldn't happen: a call trace has no functionJumpdest but has already jumped into a function
    at ErrorInferrer._getEntryBeforeFailureInModifier (D:\Programming\Work\bocachica-deimos-sc\node_modules\hardhat\src\internal\hardhat-network\stack-traces\error-inferrer.ts:1500:13)
    at ErrorInferrer._checkRevertOrInvalidOpcode (D:\Programming\Work\bocachica-deimos-sc\node_modules\hardhat\src\internal\hardhat-network\stack-traces\error-inferrer.ts:389:16)
    at ErrorInferrer._checkLastInstruction (D:\Programming\Work\bocachica-deimos-sc\node_modules\hardhat\src\internal\hardhat-network\stack-traces\error-inferrer.ts:573:44)    at ErrorInferrer.inferAfterTracing (D:\Programming\Work\bocachica-deimos-sc\node_modules\hardhat\src\internal\hardhat-network\stack-traces\error-inferrer.ts:162:12)    
    at SolidityTracer._rawTraceEvmExecution (D:\Programming\Work\bocachica-deimos-sc\node_modules\hardhat\src\internal\hardhat-network\stack-traces\solidityTracer.ts:211:61)
    at SolidityTracer._traceEvmExecution (D:\Programming\Work\bocachica-deimos-sc\node_modules\hardhat\src\internal\hardhat-network\stack-traces\solidityTracer.ts:149:29)  
    at SolidityTracer._getCallMessageStackTrace (D:\Programming\Work\bocachica-deimos-sc\node_modules\hardhat\src\internal\hardhat-network\stack-traces\solidityTracer.ts:72:17)
    at SolidityTracer.getStackTrace (D:\Programming\Work\bocachica-deimos-sc\node_modules\hardhat\src\internal\hardhat-network\stack-traces\solidityTracer.ts:56:19)        
    at SolidityTracer._getUnrecognizedMessageStackTrace (D:\Programming\Work\bocachica-deimos-sc\node_modules\hardhat\src\internal\hardhat-network\stack-traces\solidityTracer.ts:100:44)
    at SolidityTracer.getStackTrace (D:\Programming\Work\bocachica-deimos-sc\node_modules\hardhat\src\internal\hardhat-network\stack-traces\solidityTracer.ts:59:17) +3s    
```

Hardhat v2.10.0
Hardhat-network-helpers v1.0.3
Node >=v16.0.0

**Comment by fvictorio** [comment]
I'm going to close this in favor of https://github.com/NomicFoundation/hardhat/issues/3482, that has a minimal reproduction and some initial investigation.

Thanks a lot for the reproduction repo, @pcaversaccio, that was super useful.
