### ISSUE TITLE
eth_estimateGas may throw before eth_sendTransaction (`throwOnTransactionFailures: false`)

### ISSUE THREAD

**Issue by snf** [NomicFoundation/hardhat#2320]
Hi,
As the title says, I had `throwOnTransactionFailures: false` in the config but my `sendTransaction` with the ethers wrapper was throwing.
After some debugging I found that it wasn't actually sendTransaction but the estimateGas call before it:

```
[+] sending tx
eth_blockNumber
eth_chainId
eth_estimateGas
  Contract call: <UnrecognizedContract>
  From:          ...
  To:            ...
  Value:         0 ETH

  Error: VM Exception while processing transaction: reverted with reason string '...'
      at <UnrecognizedContract>.<unknown> (...)
      at <UnrecognizedContract>.<unknown> (...)
      at <UnrecognizedContract>.<unknown> (...)
      at async EthModule._estimateGasAction (/node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:425:7)
      at async HardhatNetworkProvider._sendWithLogging (/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:138:22)
      at async HardhatNetworkProvider.request (/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:115:18)
      at async EthersProviderWrapper.send (/node_modules/@nomiclabs/hardhat-ethers/src/internal/ethers-provider-wrapper.ts:13:20)
```

The fix for my code was setting the gas myself instead of letting hardhat estimate it. My issue was that it looked like sendTransaction was throwing which is confusing cause it looked like hardhat was ignoring the conf.

I think my solution would be to have a warning/notice message if `throwOnTransactionFailures: false` and `eth_estimateGas` throws but not sure if it's the best solution or even if a solution is needed. 

Please let me know if you need more details.

**Comment by asalem1** [comment]
> The fix for my code was setting the gas myself instead of letting hardhat estimate it. My issue was that it looked like sendTransaction was throwing which is confusing cause it looked like hardhat was ignoring the conf.

This saved me a massive headache. Thanks!

**Comment by snf** [comment]
Just noticed that this one was closed automatically by the bot. Any opinions on if this is worth "fixing"?
