### ISSUE TITLE
insufficient funds for intrinsic transaction cost

### ISSUE THREAD

**Issue by RijaCloud** [NomicFoundation/hardhat#2404]
Hello.

I'm trying to follow a tutorial to create an NFT: https://ethereum.org/en/developers/tutorials/how-to-write-and-deploy-an-nft/

I took a faucet here: https://faucet.metamask.io/

But when trying to mint the contract I get this error: 

`
λ npx hardhat --network ropsten run scripts/deploy.js
Error: insufficient funds for intrinsic transaction cost (error={"name":"ProviderError","code":-32000,"_isProviderError":true}, method="sendTransaction", transaction=undefined, code=INSUFFICIENT_FUNDS, version=providers/5.5.3)
    at Logger.makeError (E:\chat\nft\my-nft\node_modules\@ethersproject\logger\src.ts\index.ts:225:28)
    at Logger.throwError (E:\chat\nft\my-nft\node_modules\@ethersproject\logger\src.ts\index.ts:237:20)
    at checkError (E:\chat\nft\my-nft\node_modules\@ethersproject\providers\src.ts\json-rpc-provider.ts:53:16)
    at E:\chat\nft\my-nft\node_modules\@ethersproject\providers\src.ts\json-rpc-provider.ts:215:24
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  reason: 'insufficient funds for intrinsic transaction cost',
  code: 'INSUFFICIENT_FUNDS',
  error: ProviderError: insufficient funds for gas * price + value
      at HttpProvider.request (E:\chat\nft\my-nft\node_modules\hardhat\src\internal\core\providers\http.ts:49:19)
      at LocalAccountsProvider.request (E:\chat\nft\my-nft\node_modules\hardhat\src\internal\core\providers\accounts.ts:182:36)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at EthersProviderWrapper.send (E:\chat\nft\my-nft\node_modules\@nomiclabs\hardhat-ethers\src\internal\ethers-provider-wrapper.ts:13:20),
  method: 'sendTransaction',
  transaction: undefined
}
`
I have tried to find on the net I do not understand why it does not work when I am on the ropsten test network.

how i can solve this problem?

Thank you

**Comment by feuGeneA** [comment]
Thank you for using Hardhat. GitHub Issues are intended to be used only for known or suspected problems with Hardhat, or for feature requests.  For questions or other help, please use either [our Discord server](https://hardhat.org/discord) or [the GitHub Discussions feature](https://github.com/nomiclabs/hardhat/discussions/) instead.

Having said that, a quick tip for you: It sounds to me like you don't have any Ropsten ETH in the account that is attempting to execute the deployment. In that tutorial, ensure that you followed Step 4, and in Step 11 ensure that you're using the right PRIVATE_KEY.
