### ISSUE TITLE
@nomiclabs/hardhat-solpp - Upgrade to 0.11.5 as 0.10.1 leads to NodeJS errors.

### ISSUE THREAD

**Issue by Cotspheer** [NomicFoundation/hardhat#2429]
When adding @nomiclabs/hardhat-solpp to my hardhat build environment / build chain it leads to a "TypeError".  Followed the guide on https://hardhat.org/plugins/nomiclabs-hardhat-solpp.html.

## Expected Behavior
It should compile and call solpp correctly and flatten my solidity based contracts.

## Current Behavior
```
C:\Github\hardhat-playground>npx hardhat compile

An unexpected error occurred:

TypeError: Assignment to constant variable.
    at createRelativePathTest (C:\Github\hardhat-playground\node_modules\@nomiclabs\hardhat-solpp\node_modules\solpp\src\resolver.js:20:23)
    at Object.<anonymous> (C:\Github\hardhat-playground\node_modules\@nomiclabs\hardhat-solpp\node_modules\solpp\src\resolver.js:16:28)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (C:\Github\hardhat-playground\node_modules\@nomiclabs\hardhat-solpp\node_modules\solpp\src\index.js:5:18)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
```

## Possible Solution
This is as version 0.10.1 tries to assign "pathSeparator" on line 20 in resolver.js with a new string value but the variable is imported as const value on line 7. This is corrected at least on version 0.11.4. See also: [Fix assignment to constant variable error](https://github.com/merklejerk/solpp/commit/f21d5d0a16312e5e1c5132a5640d648e9b1a762b).

## Steps to Reproduce
1. Run npx hardhat
2. Select "Create an advanced sample project that uses TypeScript"
4. Add package.json as described below
5. Run npm install
6. Add import "@nomiclabs/hardhat-solpp"; below line 6 on hardhat.config.ts
7. Run npx hardhat compile
8. An unexpected error occurred

## Context (Environment)
package.json
```
{
  "name": "hardhat-project",
  "devDependencies": {
    "@nomiclabs/hardhat-ethers": "2.0.5",
    "@nomiclabs/hardhat-etherscan": "3.0.1",
    "@nomiclabs/hardhat-solhint": "^2.0.0",
    "@nomiclabs/hardhat-solpp": "2.0.0",
    "@nomiclabs/hardhat-waffle": "2.0.2",
    "@typechain/ethers-v5": "9.0.0",
    "@typechain/hardhat": "4.0.0",
    "@types/chai": "4.3.0",
    "@types/mocha": "9.1.0",
    "@types/node": "17.0.21",
    "chai": "4.3.6",
    "dotenv": "16.0.0",
    "ethers": "5.5.4",
    "hardhat": "2.8.4",
    "hardhat-gas-reporter": "1.0.8",
    "hardhat-preprocessor": "^0.1.4",
    "solpp": "0.11.5",
    "mocha": "9.2.1",
    "npm-run-all": "4.1.5",
    "prettier": "^2.5.1",
    "prettier-plugin-solidity": "^1.0.0-beta.19",
    "solhint": "^3.3.7",
    "solhint-plugin-prettier": "0.0.5",
    "solidity-coverage": "^0.7.20",
    "ts-node": "10.5.0",
    "typechain": "7.0.0",
    "typescript": "4.5.5"
  }
}
```

## Detailed Description
Upgrade package.json of @nomiclabs/hardhat-solpp to use the latest version.

**Comment by alcuadrado** [comment]
We released a new version. Can you try again with it?

**Comment by Cotspheer** [comment]
Perfect! That solved it. Thank you!
