### ISSUE TITLE
ProviderError: VM Exception while processing transaction: revert on request core provider

### ISSUE THREAD

**Issue by agiledev624** [NomicFoundation/hardhat#2431]
I forked bsc and working hardhat on localhost.
I have sometimes got this error.
It seems like it's working randomly. (even with same script)
Two cases (deploying and testing for the deployed contract) are the same.
I noticed it happened if while going to write on contract. (i.e. to read on contract for test is working)

```ProviderError: VM Exception while processing transaction: revert
      at HttpProvider.request (node_modules\hardhat\src\internal\core\providers\http.ts:49:19)
      at GanacheGasMultiplierProvider._getMultipliedGasEstimation (node_modules\hardhat\src\internal\core\providers\gas-providers.ts:72:59)
      at GanacheGasMultiplierProvider.request (node_modules\hardhat\src\internal\core\providers\gas-providers.ts:309:19)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)```

Any solution? Thanks

**Comment by fvictorio** [comment]
Hi @agiledev624. Can you provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)?

**Comment by agiledev624** [comment]
I think it's due to the provider. I changed the provider url and ran on the other device and it worked.

**Comment by fvictorio** [comment]
Ok, thanks for letting us know. Closing this for now then. If someone runs into this problem and has precise and minimal reproduction steps, please let us know.
