### ISSUE TITLE
sendTransaction fails when testing locally

### ISSUE THREAD

**Issue by msugarm** [NomicFoundation/hardhat#2462]
I am currently testing using ganache forking BSC.

when try to sendTransaction, throw errors with a CALL_EXCEPTION code error.

code
```javascript
  it("send BNB", async () => {
    const value = ethers.utils.parseEther("1");

    const balanceBefore = await provider.getBalance(receiver.address);
    console.log(balanceBefore);
    let tx = await signer.sendTransaction({
      to: receiver.address,
      value: value,
      gasPrice: GAS_CONFIG.gasPrice,
      gasLimit: GAS_CONFIG.gasLimit,
    });
    await tx.wait();
    console.log({ tx });
    const balanceAfter = await provider.getBalance(receiver.address);
    console.log(balanceAfter);

    expect(balanceBefore).to.equal(0);
    expect(balanceAfter).to.equal(value);
  });
  ```
  
error
  ```
send BNB:
     Error: transaction failed (transactionHash="0x0d46ca5e92f24b97b7fa5883a5c4ee7462ef4975fcd9860881131bc59c0b9255", transaction={"hash":"0x0d46ca5e92f24b97b7fa5883a5c4ee7462ef4975fcd9860881131bc59c0b9255","type":0,"accessList":null,"blockHash":"0x4a378ba16f26056f80cc657419e5c36f970647bb237be9f39c3533884f31163e","blockNumber":15853400,"transactionIndex":0,"confirmations":1,"from":"0xCeA06DcdD724b93320C97138bB369bdcc84AB6E3","gasPrice":{"type":"BigNumber","hex":"0x012a05f200"},"gasLimit":{"type":"BigNumber","hex":"0x0f4240"},"to":"0xC15912958e822fF999469186879A31054566ac9e","value":{"type":"BigNumber","hex":"0x0de0b6b3a7640000"},"nonce":765,"data":"0x","r":"0xa22914e7c357f7f3105527542fa83f0553f85cb0cf9486423f47bd75a6dfd697","s":"0x116ff6588c774602045b62016abe84c1a08cee5281eda90f412a90253c7a904d","v":2709,"creates":null,"chainId":1337}, receipt={"to":"0xC15912958e822fF999469186879A31054566ac9e","from":"0xCeA06DcdD724b93320C97138bB369bdcc84AB6E3","contractAddress":null,"transactionIndex":0,"gasUsed":{"type":"BigNumber","hex":"0x5232"},"logsBloom":"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","blockHash":"0x4a378ba16f26056f80cc657419e5c36f970647bb237be9f39c3533884f31163e","transactionHash":"0x0d46ca5e92f24b97b7fa5883a5c4ee7462ef4975fcd9860881131bc59c0b9255","logs":[],"blockNumber":15853400,"confirmations":1,"cumulativeGasUsed":{"type":"BigNumber","hex":"0x5232"},"effectiveGasPrice":{"type":"BigNumber","hex":"0x012a05f200"},"status":0,"type":0,"byzantium":true}, code=CALL_EXCEPTION, version=providers/5.5.3)
      at Logger.makeError (node_modules/@ethersproject/logger/src.ts/index.ts:225:28)
      at Logger.throwError (node_modules/@ethersproject/logger/src.ts/index.ts:237:20)
      at EthersProviderWrapper.<anonymous> (node_modules/@ethersproject/providers/src.ts/base-provider.ts:1352:24)
      at step (node_modules/@ethersproject/providers/lib/base-provider.js:48:23)
      at Object.next (node_modules/@ethersproject/providers/lib/base-provider.js:29:53)
      at fulfilled (node_modules/@ethersproject/providers/lib/base-provider.js:20:58)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
  ```

**Comment by morgansliman** [comment]
I don't know enough about this part of the codebase to tell whether this is a bug, needs more info, or otherwise. @feuGeneA could you take a look when you get a chance?

**Comment by morgansliman** [comment]
@msugarm in the meantime, you can check out our [discord server](https://hardhat.org/discord) if you need more immediate support.

**Comment by feuGeneA** [comment]
@msugarm can you provide a reproduction scenario? See https://stackoverflow.com/help/minimal-reproducible-example

There's not a lot to go on here, but one thing I see that's probably wrong is the `"chainId":1337` in your transaction. I'm not a BSC user, but a quick googling suggests that you should be using `56` instead.
