### ISSUE TITLE
Fail to verify contract when address is all upper case

### ISSUE THREAD

**Issue by gzliudan** [NomicFoundation/hardhat#2487]
When I pass an address as all upper case format, the @nomiclabs/hardhat-etherscan (version: 3.0.3) report below error:
```text
NomicLabsHardhatPluginError: Value 0X9C3C9283D3E44854697CD22D3FAA240CFB032889 cannot be encoded for the parameter weth.
Encoder error reason: invalid address (argument="address", value="0X9C3C9283D3E44854697CD22D3FAA240CFB032889", code=INVALID_ARGUMENT, version=address/5.5.0)
    at encodeArguments (<DIR>/node_modules/@nomiclabs/hardhat-etherscan/src/ABIEncoder.ts:34:13)
    at SimpleTaskDefinition.verifySubtask [as action] (<DIR>/node_modules/@nomiclabs/hardhat-etherscan/src/index.ts:265:34)
    at Environment._runTaskDefinition (<DIR>/node_modules/hardhat/src/internal/core/runtime-environment.ts:217:14)
    at Environment.run (<DIR>/node_modules/hardhat/src/internal/core/runtime-environment.ts:129:14)
    at verifyContract (<DIR>/deploy/verify.js:23:5)
    at verifyWithControllerAndWeth (<DIR>/deploy/verify.js:114:3)
    at verify (<DIR>/deploy/verify.js:357:7)

    Caused by: Error: invalid address (argument="address", value="0X9C3C9283D3E44854697CD22D3FAA240CFB032889", code=INVALID_ARGUMENT, version=address/5.5.0) (argument="weth", value="0X9C3C9283D3E44854697CD22D3FAA240CFB032889", code=INVALID_ARGUMENT, version=abi/5.5.0)
        at Logger.makeError (<DIR>/node_modules/@ethersproject/logger/src.ts/index.ts:225:28)
        at Logger.throwError (<DIR>/node_modules/@ethersproject/logger/src.ts/index.ts:237:20)
        at Logger.throwArgumentError (<DIR>/node_modules/@ethersproject/logger/src.ts/index.ts:241:21)
        at AddressCoder.Coder._throwError (<DIR>/node_modules/@ethersproject/abi/src.ts/coders/abstract-coder.ts:68:16)
        at AddressCoder.encode (<DIR>/node_modules/@ethersproject/abi/src.ts/coders/address.ts:22:18)
        at <DIR>/node_modules/@ethersproject/abi/src.ts/coders/array.ts:71:19
        at Array.forEach (<anonymous>)
        at pack (<DIR>/node_modules/@ethersproject/abi/src.ts/coders/array.ts:54:12)
        at TupleCoder.encode (<DIR>/node_modules/@ethersproject/abi/src.ts/coders/tuple.ts:54:20)
        at AbiCoder.encode (<DIR>/node_modules/@ethersproject/abi/src.ts/abi-coder.ts:112:15)
```
If I pass all lower case format address, then above error disappear.

**Comment by fvictorio** [comment]
@gzliudan when an address has at least some upper-case letter, then [the checksum of the address is verified](https://ethereum.stackexchange.com/questions/1374/how-can-i-check-if-an-ethereum-address-is-valid). The checksum is incorrect in this case (and probably in most all-uppercase addresses).

**Comment by gzliudan** [comment]
Thank you, I got the reason. Address should begin with 0x not 0X.
