### ISSUE TITLE
Error: Transaction reverted without a reason string at <UnrecognizedContract>.<unknown> 

### ISSUE THREAD

**Issue by AdilNehal22** [NomicFoundation/hardhat#2517]
I'm trying to call a function[propose] from Openzeppelin governor.sol. I'm using this function in my GovernorContract.sol like this...

```
  function propose(
    address[] memory targets,
    uint256[] memory values,
    bytes[] memory calldatas,
    string memory description
  ) public override(Governor, IGovernor) returns (uint256) {
    return super.propose(targets, values, calldatas, description);
  }
```

Actually, I want to propose the store function of Box.sol 

```
  // Stores a new value in the contract
  function store(uint256 newValue) public onlyOwner {
    value = newValue;
    emit ValueChanged(newValue);
  }
```

After compiling and deploying all the contracts, I made a script called `propose.ts` where I'm first getting the contract ABI, and then generating the encoded bytes of the `store selector`. I'm calling the propose function below...

```
export async function Propose(args: any[], 
    functionToCall: string, 
    proposalDescription: string) 
    {

    const governor = await ethers.getContractAt("GovernorContract", '0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0');
    const box = await ethers.getContractAt("Box", '0x5FbDB2315678afecb367f032d93F642f64180aa3');

    //because in the propose function, it takes bytes calldata that what function to call in bytes. 
    const encodedFunctionCall = box.interface.encodeFunctionData(functionToCall, args);
    
    console.log(`proposing ${functionToCall} on ${box.address} with args ${args}`);
    console.log(`proposal description: \n ${proposalDescription}`);

    console.log("proposing>>>>>>>>>");

    const proposeTx = await governor.propose(
        [box.address],
        [0],
        [encodedFunctionCall],
        proposalDescription,
        {
            gasLimit: 30000000,
            gasPrice: 908478342
        }
    );

    //we will also get the proposalId from the event and we will use it to vote later
    const proposeReceipt = await proposeTx.wait(1);
};
```

But, I'm getting the error...

```
web3_clientVersion (2)
eth_chainId (2)
eth_accounts
eth_chainId
eth_accounts
web3_clientVersion (2)
eth_chainId (2)
eth_accounts
eth_chainId
eth_accounts
web3_clientVersion (2)
eth_chainId (2)
eth_accounts
eth_chainId
eth_accounts
eth_blockNumber
eth_chainId
eth_sendTransaction //eth_sendTransaction turned of red color while the above properties are in green color. 
  Contract call:       GovernorContract#propose
  Transaction:         0xb346e775313a60fdef9487ea8d4f1a536b9dd819b3fba030fdfc554f757b1646
  From:                0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266
  To:                  0x9fe46736679d2d9a65f0992f2272de9f3c7fa6e0
  Value:               0 ETH
  Gas used:            31842 of 30000000
  Block #12:           0x7ce029ec3194f14fd56cdcd8310a65cd1276e4293c8e7c079ab59ee6c84d0c44

  Error: Transaction reverted without a reason string
      at <UnrecognizedContract>.<unknown> (0x5fbdb2315678afecb367f032d93f642f64180aa3) //see this
      at GovernorContract.getVotes (@openzeppelin/contracts/governance/extensions/GovernorVotes.sol:25)
      at GovernorContract.getVotes (contracts/Governance_Standard/GovernorContract.sol:62)
      at GovernorContract.propose (@openzeppelin/contracts/governance/Governor.sol:200)
      at GovernorContract.propose (contracts/Governance_Standard/GovernorContract.sol:80)
      at async HardhatNode._mineBlockWithPendingTxs (C:\Users\Adil.Nehal\Desktop\BOX_DAO\node_modules\hardhat\src\internal\hardhat-network\provider\node.ts:1772:23)
      at async HardhatNode.mineBlock (C:\Users\Adil.Nehal\Desktop\BOX_DAO\node_modules\hardhat\src\internal\hardhat-network\provider\node.ts:466:16)
      at async EthModule._sendTransactionAndReturnHash (C:\Users\Adil.Nehal\Desktop\BOX_DAO\node_modules\hardhat\src\internal\hardhat-network\provider\modules\eth.ts:1496:18)
      at async HardhatNetworkProvider._sendWithLogging (C:\Users\Adil.Nehal\Desktop\BOX_DAO\node_modules\hardhat\src\internal\hardhat-network\provider\provider.ts:139:22)
      at async HardhatNetworkProvider.request (C:\Users\Adil.Nehal\Desktop\BOX_DAO\node_modules\hardhat\src\internal\hardhat-network\provider\provider.ts:116:18)
      at async JsonRpcHandler._handleRequest (C:\Users\Adil.Nehal\Desktop\BOX_DAO\node_modules\hardhat\src\internal\hardhat-network\jsonrpc\handler.ts:188:20)
      at async JsonRpcHandler._handleSingleRequest (C:\Users\Adil.Nehal\Desktop\BOX_DAO\node_modules\hardhat\src\internal\hardhat-network\jsonrpc\handler.ts:167:17)
```
I couldn't recognize why the contract and the function selector are
![Capture1](https://user-images.githubusercontent.com/65488685/159462725-843907a7-b982-472b-81c9-1b49d8158913.PNG)
 not being recognized meanwhile, it compiled and deployed perfectly with the good ABIs.

**Comment by aliveli186** [comment]
If you're using MetaMask you may need to reset the nonce value of the account and to do that go to Settings->Advanced->Reset Account and Reset it.
You'll need to do this every time you start a node if on your previous run you performed a write transaction (increases nonce) from that account.

**Comment by morgansliman** [comment]
This doesn't seem like a bug in Hardhat, so I'm going to close this. Feel free to add more info and we can reopen if necessary!

**Comment by AdamMomen** [comment]
> If you're using MetaMask you may need to reset the nonce value of the account and to do that go to Settings->Advanced->Reset Account and Reset it.
> You'll need to do this every time you start a node if on your previous run you performed a write transaction (increases nonce) from that account.

@yablados  Have you had any luck figuring it out?

**Comment by aliveli186** [comment]
You may be calling a wrong contract address. Address may change after a new deploy. Make sure you're calling the newest contract address.

**Comment by lukastanisic99** [comment]
I've had the same issue for days and the solution for me was just to use ganache or geth in the end when I wanted to interact with my contract through Metamask... The contracts work in the hardhat network through the default provider, but not through Metamask while sending ETH works fine on Metamask on the hardhat node. Changing chainID to 1337 doesn't solve this. Tried both 1337 and 31337 and created new networks in Metamask and it just doesn't work in the hardhat node. The exact same setup works out of the box on ganache and geth.
