### ISSUE TITLE
Error HH201: Could not set param noTypechain for task compile because its name is already used.

### ISSUE THREAD

**Issue by tamaramack** [NomicFoundation/hardhat#2521]
Hello!
I'm having an issue with calling `hardhat`. With every call, I get the same message.
```shell
macPro@Monterey12 testNFT % npx hardhat node --no-deploy
Error HH201: Could not set param noTypechain for task compile because its name is already used.

For more info go to https://hardhat.org/HH201 or run Hardhat with --show-stack-traces
macPro@Monterey12 testNFT % npx hardhat node --no-deploy --show-stack-traces
Error HH201: Could not set param noTypechain for task compile because its name is already used.

HardhatError: HH201: Could not set param noTypechain for task compile because its name is already used.
    at SimpleTaskDefinition._validateNameNotUsed (/Users/testNFT/node_modules/hardhat/src/internal/core/tasks/task-definitions.ts:440:13)
    at SimpleTaskDefinition.addFlag (/Users/user/testNFT/node_modules/hardhat/src/internal/core/tasks/task-definitions.ts:184:10)
    at OverriddenTaskDefinition.addFlag (/Users/user/TtestNFT/node_modules/hardhat/src/internal/core/tasks/task-definitions.ts:723:31)
    at OverriddenTaskDefinition.addFlag (/Users/user/testNFT/node_modules/hardhat/src/internal/core/tasks/task-definitions.ts:723:31)
    at Object.<anonymous> (/Users/user/testNFT/node_modules/hardhat-packager/node_modules/@typechain/hardhat/src/index.ts:20:4)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
```

I have the HardHat project setup as a [npm _workspace_](https://docs.npmjs.com/cli/v8/using-npm/workspaces) package with other packages (IPFS, network configs, web services, etc) in relation. 
I'm working on Node v16 using the latest hardhat version.

**Comment by fvictorio** [comment]
Hi @tamaramack, can you share your Hardhat config, or at least tell us which plugins (and versions) you are using?

**Comment by tamaramack** [comment]
Sure,
*package.json*:
```json
  "devDependencies": {
    "@erc725/erc725.js": "^0.8.0",
    "@nomiclabs/hardhat-ethers": "^2.0.3",
    "@nomiclabs/hardhat-etherscan": "^2.1.8",
    "@nomiclabs/hardhat-waffle": "^2.0.1",
    "@typechain/ethers-v5": "^9.0.0",
    "@typechain/hardhat": "^5.0.0",
    "@types/chai": "^4.2.22",
    "@types/mocha": "^9.0.0",
    "@types/node": "^17.0.22",
    "@typescript-eslint/eslint-plugin": "^5.16.0",
    "@typescript-eslint/parser": "^5.16.0",
    "chai": "^4.3.6",
    "dotenv": "^16.0.0",
    "ethereum-waffle": "^3.4.0",
    "ethers": "^5.6.1",
    "hardhat": "^2.9.1",
    "hardhat-deploy": "^0.11.2",
    "hardhat-deploy-ethers": "^0.3.0-beta.13",
    "hardhat-gas-reporter": "^1.0.8",
    "hardhat-packager": "^1.3.0",
    "prettier": "^2.5.0",
    "prettier-plugin-solidity": "^1.0.0-beta.13",
    "solhint": "^3.3.7",
    "solidity-coverage": "^0.7.20",
    "ts-node": "^10.7.0",
    "typechain": "^7.0.1",
    "typescript": "^4.5.2"
  },
  "dependencies": {
    "@erc725/smart-contracts": "^2.1.6",
    "@lukso/universalprofile-smart-contracts": "^0.4.1",
    "@openzeppelin/contracts": "^4.4.0",
    "@supercharge/promise-pool": "^2.1.0",
    "ajv": "^8.9.0",
    "ajv-formats": "^2.1.1",
    "env-cmd": "^10.1.0",
    "ipfs-core": "^0.14.1",
    "ipfs-http-client": "^56.0.1",
    "sharp": "^0.30.3"
  }
```

*hardhat.config.ts*
```javascript
import * as dotenv from "dotenv";

import { HardhatUserConfig, task, types } from "hardhat/config";
import "@nomiclabs/hardhat-ethers";
import "@nomiclabs/hardhat-etherscan";
import "@nomiclabs/hardhat-waffle";
import "@typechain/hardhat";
import "hardhat-deploy";
import "hardhat-packager";
// import "hardhat-deploy-ethers";
import "hardhat-gas-reporter";
import "solidity-coverage";
import { deployProfileFull } from "./scripts/deployProfileContract";
import path from "path";

if (process.env.BUILD_ENV) {
  dotenv.config({path: process.env.BUILD_ENV});
} else {
  dotenv.config({path: "../test.env"});
}


// This is a sample Hardhat task. To learn how to create your own go to
// https://hardhat.org/guides/create-task.html
task("accounts", "Prints the list of accounts", async (taskArgs, hre) => {
  const accounts = await hre.ethers.getSigners();

  for (const account of accounts) {
    console.log(account.address);
  }
});

task("namedAccounts", "Print named accounts", async(taskArgs, hre) => {
  for (const account of Object.entries(await hre.getNamedAccounts())) {
    console.log(account);
  }
})

task("deployProfile", "Deploys profile contracts, uploads LSP3 to ipfs and sets keys according to provided json file matching ProfileDeploymentOptions interface.")
.addPositionalParam("file", "json file containing ProfileDeploymentOptions", undefined, types.inputFile, false)
.setAction(
  async (taskArgs, hre) => {
    const filePath = taskArgs.file;
    if (filePath === undefined) {
      throw Error("File path was undefined.");
    }
    const absPath = path.resolve(filePath);
    console.log(`Loading json from: ${absPath}`);
    const address = await deployProfileFull(absPath, hre);
  }
)

// You need to export an object to set up your config
// Go to https://hardhat.org/config/ to learn more

const config: HardhatUserConfig = {
  solidity: {
    version: "0.8.6",
    settings: {
      optimizer: {
        enabled: true,
        runs: 1000,
      },
    },
  },
  packager: {
    contracts: ["Account", "Authorizor", "Den", "Profile", "UniversalProfile"],
    includeFactories: true,
  },
  typechain: {
    outDir: "types",
    target: "ethers-v5",
  },
  networks: {
    ropsten: {
      url: process.env.ROPSTEN_URL || "",
      accounts:
        process.env.PRIVATE_KEY !== undefined ? [process.env.PRIVATE_KEY] : [],
    },
    l14: {
      url:  "https://rpc.l14.lukso.network",
      accounts:
        [
        ]
    }
  },
  gasReporter: {
    enabled: process.env.REPORT_GAS !== undefined,
    currency: "USD",
  },
  etherscan: {
    apiKey: process.env.ETHERSCAN_API_KEY,
  },
  namedAccounts: {
    corporate: {
      default: 0,
    },
    employee1: {
      default: 1,
    },
    employee2: {
      default: 2,
    },
    employee3: {
      default: 3,
    },
    employee4: {
      default: 4,
    },
    Bowser: {
      default: 5,
    },
    Franklin: {
      default: 6,
    },
    Koopa: {
      default: 7,
    },
    Squirtle: {
      default: 8,
    },
    Verne: {
      default: 9,
    },
  },
};

export default config;
```

**Comment by tamaramack** [comment]
Resolved issue by downgrading version of hardhat by a major version and upgrading typechain's version to latest.
```json
    "@nomiclabs/hardhat-ethers": "^2.0.3",
    "@nomiclabs/hardhat-etherscan": "^2.1.8",
    "@nomiclabs/hardhat-waffle": "^2.0.1",
    "@typechain/ethers-v5": "^9.0.0",
    "@typechain/hardhat": "^4.0.0",
...
    "ethers": "^5.6.1",
    "hardhat": "^2.8.4",
    "hardhat-deploy": "^0.9.14",
    "hardhat-deploy-ethers": "^0.3.0-beta.11",
    "hardhat-gas-reporter": "^1.0.6",
    "hardhat-packager": "^1.3.0",
...
    "typechain": "^7.0.1",
    "typescript": "^4.5.2"
```
