### ISSUE TITLE
openssl(3.0.2) issues / fedora (linux)

### ISSUE THREAD

**Issue by ryan-sam2** [NomicFoundation/hardhat#2552]
Here are the logs:

```fish
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at hash160 (/home/ryan/Desktop/learning/nft-collection-hardhat/epic-nfts/node_modules/ethereum-cryptography/vendor/hdkey-without-crypto.js:249:21)
    at HDKey.set (/home/ryan/Desktop/learning/nft-collection-hardhat/epic-nfts/node_modules/ethereum-cryptography/vendor/hdkey-without-crypto.js:50:24)
    at Function.HDKey.fromMasterSeed (/home/ryan/Desktop/learning/nft-collection-hardhat/epic-nfts/node_modules/ethereum-cryptography/vendor/hdkey-without-crypto.js:194:20)
    at deriveKeyFromMnemonicAndPath (/home/ryan/Desktop/learning/nft-collection-hardhat/epic-nfts/node_modules/hardhat/src/internal/util/keys-derivation.ts:22:27)
    at derivePrivateKeys (/home/ryan/Desktop/learning/nft-collection-hardhat/epic-nfts/node_modules/hardhat/src/internal/core/providers/util.ts:30:52)
    at normalizeHardhatNetworkAccountsConfig (/home/ryan/Desktop/learning/nft-collection-hardhat/epic-nfts/node_modules/hardhat/src/internal/core/providers/util.ts:58:10)
    at createProvider (/home/ryan/Desktop/learning/nft-collection-hardhat/epic-nfts/node_modules/hardhat/src/internal/core/providers/construction.ts:79:59)
    at /home/ryan/Desktop/learning/nft-collection-hardhat/epic-nfts/node_modules/hardhat/src/internal/core/runtime-environment.ts:80:28 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
```
What i tried:

```fish
ryan@ghost ~/D/l/n/epic-nfts> rm -rf node_modules/
ryan@ghost ~/D/l/n/epic-nfts> ls
artifacts/  contracts/         package.json       README.md  test/
cache/      hardhat.config.js  package-lock.json  scripts/
ryan@ghost ~/D/l/n/epic-nfts> npm install
npm WARN deprecated ganache-core@2.13.2: ganache-core is now ganache; visit https://trfl.io/g7 for details
npm WARN deprecated ganache-core@2.13.2: ganache-core is now ganache; visit https://trfl.io/g7 for details
npm WARN deprecated testrpc@0.0.1: testrpc has been renamed to ganache-cli, please use this package from now on.
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated @ensdomains/ens@0.4.5: Please use @ensdomains/ens-contracts
npm WARN deprecated @ensdomains/resolver@0.2.4: Please use @ensdomains/ens-contracts

added 1407 packages, and audited 1411 packages in 2m

116 packages are looking for funding
  run `npm fund` for details

48 vulnerabilities (3 low, 12 moderate, 33 high)

To address issues that do not require attention, run:
  npm audit fix

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.
ryan@ghost ~/D/l/n/epic-nfts> npx hardhat run scripts/sample-script.js
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at hash160 (/home/ryan/Desktop/learning/nft-collection-hardhat/epic-nfts/node_modules/ethereum-cryptography/vendor/hdkey-without-crypto.js:249:21)
    at HDKey.set (/home/ryan/Desktop/learning/nft-collection-hardhat/epic-nfts/node_modules/ethereum-cryptography/vendor/hdkey-without-crypto.js:50:24)
    at Function.HDKey.fromMasterSeed (/home/ryan/Desktop/learning/nft-collection-hardhat/epic-nfts/node_modules/ethereum-cryptography/vendor/hdkey-without-crypto.js:194:20)
    at deriveKeyFromMnemonicAndPath (/home/ryan/Desktop/learning/nft-collection-hardhat/epic-nfts/node_modules/hardhat/src/internal/util/keys-derivation.ts:22:27)
    at derivePrivateKeys (/home/ryan/Desktop/learning/nft-collection-hardhat/epic-nfts/node_modules/hardhat/src/internal/core/providers/util.ts:30:52)
    at normalizeHardhatNetworkAccountsConfig (/home/ryan/Desktop/learning/nft-collection-hardhat/epic-nfts/node_modules/hardhat/src/internal/core/providers/util.ts:58:10)
    at createProvider (/home/ryan/Desktop/learning/nft-collection-hardhat/epic-nfts/node_modules/hardhat/src/internal/core/providers/construction.ts:79:59)
    at /home/ryan/Desktop/learning/nft-collection-hardhat/epic-nfts/node_modules/hardhat/src/internal/core/runtime-environment.ts:80:28 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
```

2nd:
```fish
ryan@ghost ~/D/l/n/epic-nfts> rm -rf *
ryan@ghost ~/D/l/n/epic-nfts> npm install hardhat --save-dev

added 300 packages, and audited 301 packages in 34s

53 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
ryan@ghost ~/D/l/n/epic-nfts> npx hardhat
888    888                      888 888               888
888    888                      888 888               888
888    888                      888 888               888
8888888888  8888b.  888d888 .d88888 88888b.   8888b.  888888
888    888     "88b 888P"  d88" 888 888 "88b     "88b 888
888    888 .d888888 888    888  888 888  888 .d888888 888
888    888 888  888 888    Y88b 888 888  888 888  888 Y88b.
888    888 "Y888888 888     "Y88888 888  888 "Y888888  "Y888

Welcome to Hardhat v2.9.2

✔ What do you want to do? · Create a basic sample project
✔ Hardhat project root: · /home/ryan/Desktop/learning/nft-collection-hardhat/epic-nfts

✔ Do you want to add a .gitignore? (Y/n) · y
✔ Do you want to install this sample project's dependencies with npm (@nomiclabs/hardhat-waffle ethereum-waffle chai @nomiclabs/hardhat-ethers ethers)? (Y/n) · y



npm install --save-dev @nomiclabs/hardhat-waffle@^2.0.0 ethereum-waffle@^3.0.0 chai@^4.2.0 @nomiclabs/hardhat-ethers@^2.0.0 ethers@^5.0.0
npm WARN deprecated ganache-core@2.13.2: ganache-core is now ganache; visit https://trfl.io/g7 for details
npm WARN deprecated ganache-core@2.13.2: ganache-core is now ganache; visit https://trfl.io/g7 for details
npm WARN deprecated testrpc@0.0.1: testrpc has been renamed to ganache-cli, please use this package from now on.
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated @ensdomains/ens@0.4.5: Please use @ensdomains/ens-contracts
npm WARN deprecated @ensdomains/resolver@0.2.4: Please use @ensdomains/ens-contracts

added 1107 packages, and audited 1411 packages in 2m

115 packages are looking for funding
  run `npm fund` for details

48 vulnerabilities (3 low, 12 moderate, 33 high)

To address issues that do not require attention, run:
  npm audit fix

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.

Project created
See the README.md file for some example tasks you can run.
ryan@ghost ~/D/l/n/epic-nfts> npx hardhat run scripts/sample-script.js
Compiled 2 Solidity files successfully
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at hash160 (/home/ryan/Desktop/learning/nft-collection-hardhat/epic-nfts/node_modules/ethereum-cryptography/vendor/hdkey-without-crypto.js:249:21)
    at HDKey.set (/home/ryan/Desktop/learning/nft-collection-hardhat/epic-nfts/node_modules/ethereum-cryptography/vendor/hdkey-without-crypto.js:50:24)
    at Function.HDKey.fromMasterSeed (/home/ryan/Desktop/learning/nft-collection-hardhat/epic-nfts/node_modules/ethereum-cryptography/vendor/hdkey-without-crypto.js:194:20)
    at deriveKeyFromMnemonicAndPath (/home/ryan/Desktop/learning/nft-collection-hardhat/epic-nfts/node_modules/hardhat/src/internal/util/keys-derivation.ts:22:27)
    at derivePrivateKeys (/home/ryan/Desktop/learning/nft-collection-hardhat/epic-nfts/node_modules/hardhat/src/internal/core/providers/util.ts:30:52)
    at normalizeHardhatNetworkAccountsConfig (/home/ryan/Desktop/learning/nft-collection-hardhat/epic-nfts/node_modules/hardhat/src/internal/core/providers/util.ts:58:10)
    at createProvider (/home/ryan/Desktop/learning/nft-collection-hardhat/epic-nfts/node_modules/hardhat/src/internal/core/providers/construction.ts:79:59)
    at /home/ryan/Desktop/learning/nft-collection-hardhat/epic-nfts/node_modules/hardhat/src/internal/core/runtime-environment.ts:80:28 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
ryan@ghost ~/D/l/n/epic-nfts [1]> 
```

and third attempt:
```fish
ryan@ghost ~/D/l/n/epic-nfts> npm install hardhat 

added 300 packages, and audited 301 packages in 35s

53 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
ryan@ghost ~/D/l/n/epic-nfts> npx hardhat 
888    888                      888 888               888
888    888                      888 888               888
888    888                      888 888               888
8888888888  8888b.  888d888 .d88888 88888b.   8888b.  888888
888    888     "88b 888P"  d88" 888 888 "88b     "88b 888
888    888 .d888888 888    888  888 888  888 .d888888 888
888    888 888  888 888    Y88b 888 888  888 888  888 Y88b.
888    888 "Y888888 888     "Y88888 888  888 "Y888888  "Y888

Welcome to Hardhat v2.9.2

✔ What do you want to do? · Create an advanced sample project
✔ Hardhat project root: · /home/ryan/Desktop/learning/nft-collection-hardhat/epic-nfts

✔ Do you want to add a .gitignore? (Y/n) · y
✔ Do you want to install this sample project's dependencies with npm (@nomiclabs/hardhat-waffle ethereum-waffle chai @nomiclabs/hardhat-ethers ethers @nomiclabs/hardhat-etherscan dotenv eslint eslint-config-prettier eslint-config-standard eslint-plugin-import eslint-plugin-node eslint-plugin-prettier eslint-plugin-promise hardhat-gas-reporter prettier prettier-plugin-solidity solhint solidity-coverage)? (Y/n) · y






npm install --save-dev @nomiclabs/hardhat-waffle@^2.0.0 ethereum-waffle@^3.0.0 chai@^4.2.0 @nomiclabs/hardhat-ethers@^2.0.0 ethers@^5.0.0 @nomiclabs/hardhat-etherscan@^3.0.0 dotenv@^10.0.0 eslint@^7.29.0 eslint-config-prettier@^8.3.0 eslint-config-standard@^16.0.3 eslint-plugin-import@^2.23.4 eslint-plugin-node@^11.1.0 eslint-plugin-prettier@^3.4.0 eslint-plugin-promise@^5.1.0 hardhat-gas-reporter@^1.0.4 prettier@^2.3.2 prettier-plugin-solidity@^1.0.0-beta.13 solhint@^3.3.6 solidity-coverage@^0.7.16











npm WARN deprecated ganache-core@2.13.2: ganache-core is now ganache; visit https://trfl.io/g7 for details
npm WARN deprecated ganache-core@2.13.2: ganache-core is now ganache; visit https://trfl.io/g7 for details
npm WARN deprecated testrpc@0.0.1: testrpc has been renamed to ganache-cli, please use this package from now on.
npm WARN deprecated mkdirp-promise@5.0.1: This package is broken and no longer maintained. 'mkdirp' itself supports promises now, please switch to that.
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated debug@3.2.6: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated uuid@2.0.1: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@2.0.1: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated multicodec@1.0.4: This module has been superseded by the multiformats module
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.3.2: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated multibase@0.6.1: This module has been superseded by the multiformats module
npm WARN deprecated multibase@0.7.0: This module has been superseded by the multiformats module
npm WARN deprecated multicodec@0.5.7: This module has been superseded by the multiformats module
npm WARN deprecated cids@0.7.5: This module has been superseded by the multiformats module
npm WARN deprecated @ensdomains/ens@0.4.5: Please use @ensdomains/ens-contracts
npm WARN deprecated @ensdomains/resolver@0.2.4: Please use @ensdomains/ens-contracts

added 1736 packages, and audited 2040 packages in 3m

161 packages are looking for funding
  run `npm fund` for details

48 vulnerabilities (11 moderate, 37 high)

To address issues that do not require attention, run:
  npm audit fix

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.

Project created
See the README.md file for some example tasks you can run.
ryan@ghost ~/D/l/n/epic-nfts> 
ryan@ghost ~/D/l/n/epic-nfts> 
ryan@ghost ~/D/l/n/epic-nfts> 
ryan@ghost ~/D/l/n/epic-nfts> 
ryan@ghost ~/D/l/n/epic-nfts> 
ryan@ghost ~/D/l/n/epic-nfts> 
ryan@ghost ~/D/l/n/epic-nfts> 
ryan@ghost ~/D/l/n/epic-nfts> 
ryan@ghost ~/D/l/n/epic-nfts> 
ryan@ghost ~/D/l/n/epic-nfts> 
ryan@ghost ~/D/l/n/epic-nfts> 
ryan@ghost ~/D/l/n/epic-nfts> npx hardhat run scripts/deploy.js 
Compiled 2 Solidity files successfully
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at hash160 (/home/ryan/Desktop/learning/nft-collection-hardhat/epic-nfts/node_modules/ethereum-cryptography/vendor/hdkey-without-crypto.js:249:21)
    at HDKey.set (/home/ryan/Desktop/learning/nft-collection-hardhat/epic-nfts/node_modules/ethereum-cryptography/vendor/hdkey-without-crypto.js:50:24)
    at Function.HDKey.fromMasterSeed (/home/ryan/Desktop/learning/nft-collection-hardhat/epic-nfts/node_modules/ethereum-cryptography/vendor/hdkey-without-crypto.js:194:20)
    at deriveKeyFromMnemonicAndPath (/home/ryan/Desktop/learning/nft-collection-hardhat/epic-nfts/node_modules/hardhat/src/internal/util/keys-derivation.ts:22:27)
    at derivePrivateKeys (/home/ryan/Desktop/learning/nft-collection-hardhat/epic-nfts/node_modules/hardhat/src/internal/core/providers/util.ts:30:52)
    at normalizeHardhatNetworkAccountsConfig (/home/ryan/Desktop/learning/nft-collection-hardhat/epic-nfts/node_modules/hardhat/src/internal/core/providers/util.ts:58:10)
    at createProvider (/home/ryan/Desktop/learning/nft-collection-hardhat/epic-nfts/node_modules/hardhat/src/internal/core/providers/construction.ts:79:59)
    at /home/ryan/Desktop/learning/nft-collection-hardhat/epic-nfts/node_modules/hardhat/src/internal/core/runtime-environment.ts:80:28 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
ryan@ghost ~/D/l/n/epic-nfts [1]> 
```

**Comment by fvictorio** [comment]
I believe this is a duplicate of #1988, please re-open if you think that's not the case.

**Comment by ryan-sam2** [comment]
> I believe this is a duplicate of #1988, please re-open if you think that's not the case.

Awesome. It seems to be an issue with fedora specifically. Works like a charm on OpenSuse. Leave at closed.

**Comment by ryan-sam2** [comment]
(also its not related to the node version since i used node16)
