### ISSUE TITLE
Updating `eth_call` gas limit like Geth (`rpc.gascap`)

### ISSUE THREAD

**Issue by riordant** [NomicFoundation/hardhat#2571]
Hi,
I am having a issue with using a uniswap library (https://github.com/Uniswap/smart-order-router) on a forked Hardhat node. 

The library executes several `eth_call`s, some of which exceed the default gas limit per `eth_call` on most nodes.

It is possible with Geth/Erigon to update this limit by using the RPC call `--rpc.gascap {LIMIT}`. When I call my node directly after increasing the limit, it works. However, when I fork from the node with Hardhat, the calls will fail with:

```
  TransactionExecutionError: Transaction ran out of gas
      at HardhatNode._manageErrors (project/node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:1928:14)
      at HardhatNode._gatherTraces (project/node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:1652:30)
      at async HardhatNode.runCall (project/node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:615:20)
      at async EthModule._callAction (project/node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:353:9)
      at async HardhatNetworkProvider._sendWithLogging (project/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:139:22)
      at async HardhatNetworkProvider.request (project/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:116:18)
      at async JsonRpcHandler._handleRequest (project/node_modules/hardhat/src/internal/hardhat-network/jsonrpc/handler.ts:188:20)
      at async JsonRpcHandler._handleSingleRequest (project/node_modules/hardhat/src/internal/hardhat-network/jsonrpc/handler.ts:167:17)
      at async Server.JsonRpcHandler.handleHttp (project/node_modules/hardhat/src/internal/hardhat-network/jsonrpc/handler.ts:52:21)
```

Is it possible to do update the limit in Hardhat forking mode? Nothing that I've tried has seemed to work.
Thanks

**Comment by fvictorio** [comment]
Have you tried increasing the [`blockGasLimit`](https://hardhat.org/hardhat-network/reference/#blockgaslimit) setting?

```
networks: {
  hardhat: {
    blockGasLimit: 100_000_000
```

**Comment by riordant** [comment]
Hi,
yes I tried this. It still doesn't work. 
I think the setting _should_ be `gas`, but regardless of what I set for this it doen't work.
In Ganache, the setting is `--miner.callGasLimit. reference issue: https://github.com/trufflesuite/ganache/issues/148

**Comment by fvictorio** [comment]
If you don't specify a `gasLimit` value, then `eth_call` will use the block gas limit (or a close value) as its gas limit. For example, if I deploy a contract with a function like this:

```solidity
    function gasLeft() public view {
      console.log(gasleft());
    }
```

and then I call that method after setting different `blockGasLimit` values, the logged number changes accordingly. So in principle changing the block gas limit should help if you don't want to manually set a `gasLimit` for all your calls.

I'm not really sure how I can help here. If you create a minimal reproduction example of the problem you're having, I will take a deeper look.

**Comment by fvictorio** [comment]
Closing this for now. @riordant please re-open if you can provide more info.
