### ISSUE TITLE
why i install the ls current version of nodejs 17.9.0 and still getting the : You are using a version of Node.js?

### ISSUE THREAD

**Issue by mohamedtb20** [NomicFoundation/hardhat#2586]
C:\Users\DELL\nft_marketplace>npx hardhat test
You are using a version of Node.js that is not supported by Hardhat, and it may work incorrectly, or not work at all.

Please, make sure you are using a supported version of Node.js.

To learn more about which versions of Node.js are supported go to https://hardhat.org/nodejs-versions
An unexpected error occurred:

C:\Users\DELL\nft_marketplace\hardhat.config.js:10
    mumbai: {
    ^^^^^^

SyntaxError: Unexpected identifier
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1027:15)
    at Module._compile (node:internal/modules/cjs/loader:1063:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at importCsjOrEsModule (C:\Users\DELL\nft_marketplace\node_modules\hardhat\src\internal\core\config\config-loading.ts:24:20)
    at loadConfigAndTasks (C:\Users\DELL\nft_marketplace\node_modules\hardhat\src\internal\core\config\config-loading.ts:76:18)

C:\Users\DELL\nft_marketplace>node -v
v17.9.0

![Screenshot (58)](https://user-images.githubusercontent.com/93258392/162600211-144acea8-48ea-49d0-9c07-8170a3666d6a.png)

**Comment by alcuadrado** [comment]
There are two things going on here. One is that you are using an unsupported version of node (17), and the other one is that you have a syntax error in your hardhat config.
