### ISSUE TITLE
hat=rdhat issue 

### ISSUE THREAD

**Issue by mohamedtb20** [NomicFoundation/hardhat#2587]
C:\Users\DELL\nft_marketplace\hardhat.config.js:10
    mumbai: {
    ^^^^^^

SyntaxError: Unexpected identifier
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1032:15)
    at Module._compile (node:internal/modules/cjs/loader:1067:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at importCsjOrEsModule (C:\Users\DELL\nft_marketplace\node_modules\hardhat\src\internal\core\config\config-loading.ts:24:20)
    at loadConfigAndTasks (C:\Users\DELL\nft_marketplace\node_modules\hardhat\src\internal\core\config\config-loading.ts:76:18)

**Comment by alcuadrado** [comment]
Closed as it's not properly stated
