### ISSUE TITLE
Add job in hardhat cli task 'clean', removeDir '.openzeppelin'.

### ISSUE THREAD

**Issue by dbadoy** [NomicFoundation/hardhat#2603]
## Summary
If used method hardhat.upgrades.deployProxy(), created directory '.openzeppelin' in root path in project.
Also, generated json file in directory. example below,

unknown-1337.json (network name + chain id + .json)

If generate new network after network initialization (reset network and 'npx hardhat clean') , hardhat is set up with the '.openzeppelin' directory you created in the old network. furthermore if you set the same chain id as the previous network, it make problem when request method upgrades.deployProxy() on newly network.

```typescript
// validateStoredDeployment()
.
.
. 
const tx = await getTransactionByHash(provider, txHash);
if (tx !== null) {
  debug('resuming previous deployment', txHash);
  if (merge) {
       waitAndValidateDeployment(provider, stored, type, opts);
    }
} else {
      // ****** error ****** 
      throw new InvalidDeployment(stored);
}


```

The txHash in .openzeppelin/network-chainid.json is not exist in newly network because it created previous network.

## Suggest
Add job in hardhat cli task 'clean'.

As-is : Remove directory 'artifacts', emptyDir 'cache'.
Suggest : Remove directory 'artifacts', emptyDir 'cache', **'.openzeppelin'**.

**Comment by dbadoy** [comment]
Example error log)

```
InvalidDeployment [Error]: No contract at address 0xF9D27018333febFf046ddE143E23F721EDeB9645 (Removed from manifest)
    at validateStoredDeployment (/Users/temp_pj/node_modules/@openzeppelin/upgrades-core/src/deployment.ts:124:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async validateCached (/Users/temp_pj/node_modules/@openzeppelin/upgrades-core/src/deployment.ts:85:7)
    at async resumeOrDeploy (/Users/temp_pj/node_modules/@openzeppelin/upgrades-core/src/deployment.ts:65:21)
    at async /Users/temp_pj/node_modules/@openzeppelin/upgrades-core/src/impl-store.ts:54:23
    at async Manifest.lockedRun (/Users/temp_pj/node_modules/@openzeppelin/upgrades-core/src/manifest.ts:122:14)
    at async fetchOrDeployGeneric (/Users/temp_pj/node_modules/@openzeppelin/upgrades-core/src/impl-store.ts:43:24)
    at async deployImpl (/Users/temp_pj/node_modules/@openzeppelin/hardhat-upgrades/src/utils/deploy-impl.ts:114:16)
    at async Proxy.deployProxy (/Users/temp_pj/node_modules/@openzeppelin/hardhat-upgrades/src/deploy-proxy.ts:42:28)
```
