### ISSUE TITLE
Transaction Reverted without a reason string/  GanacheGasMultiplierProvider.request?

### ISSUE THREAD

**Issue by grapevinegizmos** [NomicFoundation/hardhat#2647]
I'm not certain this is a hardhat issue, but I get the following error when I am trying to deploy a contract from a factory created with await factory.deploy(abi, bytecode,signer). 

But I am wondering if the error I am receiving on the console in VS code is meaningful:  I note that it says an error occurred in the GanacheGasMultiplierProvider but I am not using Ganache at all.

```
ProviderError: Error: Transaction reverted without a reason string
    at HttpProvider.request (/Users/joshkramer/Documents/VSCodeProjects/BKopy/bkopy-embedded-contracts/node_modules/hardhat/src/internal/core/providers/http.ts:74:19)
    at GanacheGasMultiplierProvider.request (/Users/joshkramer/Documents/VSCodeProjects/BKopy/bkopy-embedded-contracts/node_modules/hardhat/src/internal/core/providers/gas-providers.ts:312:34)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

This is the line in script which is producing this error:
```
   let abi = bindingcatalogJson.abi;    //imported json from artifacts/contracts folder of the contract from which I am getting the code on the next line.
 //can't use bytecode bindingcatatalJson because it contains link references.  
 let bytecode = await ethers.provider.getCode(localTemplate);  //localtemplate is the address of a previously deployed contract with the same abi
   let [signer] = await ethers.getSigners(); 
   let factory = new ethers.ContractFactory(abi,bytecode,signer);
   let con = await factory.deploy(signer.address, localEmbedRoot, {gasLimit: 5000000})   //  <<fails here
```
In the local node I get this error:
```
eth_sendTransaction
  Contract deployment: <UnrecognizedContract>
  Transaction:         0xd0079e7c7fb787c24ccd051a76e233e783c66855cba19349cdc91b5cea3b3659
  From:                0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266
  Value:               0 ETH
  Gas used:            373838 of 5000000
  Block #181:          0xf7e8676c27991c1bca724161b43352395ab6ff9cf7cb3537c9ba0c978d2bdad9

  Error: Transaction reverted without a reason string
      at <UnrecognizedContract>.constructor (unknown)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at async HardhatNode._mineBlockWithPendingTxs (/Users/joshkramer/Documents/VSCodeProjects/BKopy/contracts/node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:1598:23)
      at async HardhatNode.mineBlock (/Users/joshkramer/Documents/VSCodeProjects/BKopy/contracts/node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:435:16)
      at async EthModule._sendTransactionAndReturnHash (/Users/joshkramer/Documents/VSCodeProjects/BKopy/contracts/node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:1494:18)
      at async HardhatNetworkProvider._sendWithLogging (/Users/joshkramer/Documents/VSCodeProjects/BKopy/contracts/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:129:22)
      at async HardhatNetworkProvider.request (/Users/joshkramer/Documents/VSCodeProjects/BKopy/contracts/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:106:18)
```

**Comment by grapevinegizmos** [comment]
Have been working to try workarounds, and managed to get the contract deployed, and can read from the contract, but when I attempt to call a non-view function that sets state variables, I still get this error in the VS code console referring to GanacheGasMultipler provider, below:

```
ProviderError: Error: Transaction reverted without a reason string
    at HttpProvider.request (/Users/joshkramer/Documents/VSCodeProjects/BKopy/bkopy-embedded-contracts/node_modules/hardhat/src/internal/core/providers/http.ts:74:19)
    at GanacheGasMultiplierProvider.request (/Users/joshkramer/Documents/VSCodeProjects/BKopy/bkopy-embedded-contracts/node_modules/hardhat/src/internal/core/providers/gas-providers.ts:312:34)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Joshs-MacBook-Pro:bkopy-embedded-contracts joshkramer$ 
```
Here is the log from the terminal running hardhat node:
```
eth_estimateGas
  Contract call:       <UnrecognizedContract>
  From:                0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266
  To:                  0xe86517f38f6c57e3ce0b009c8a777fad6049a96c
  Value:               0 ETH

  Error: Transaction reverted without a reason string
      at <UnrecognizedContract>.<unknown> (0xe86517f38f6c57e3ce0b009c8a777fad6049a96c)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at async EthModule._estimateGasAction (/Users/joshkramer/Documents/VSCodeProjects/BKopy/contracts/node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:425:7)
      at async HardhatNetworkProvider._sendWithLogging (/Users/joshkramer/Documents/VSCodeProjects/BKopy/contracts/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:129:22)
      at async HardhatNetworkProvider.request (/Users/joshkramer/Documents/VSCodeProjects/BKopy/contracts/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:106:18)
      at async JsonRpcHandler._handleRequest (/Users/joshkramer/Documents/VSCodeProjects/BKopy/contracts/node_modules/hardhat/src/internal/hardhat-network/jsonrpc/handler.ts:188:20)
      at async JsonRpcHandler._handleSingleRequest (/Users/joshkramer/Documents/VSCodeProjects/BKopy/contracts/node_modules/hardhat/src/internal/hardhat-network/jsonrpc/handler.ts:167:17)
```

**Comment by fvictorio** [comment]
"Transaction reverted without a reason string" means that the transaction reverted and there wasn't a reason string. This happens, for example, if you hit a `require(false)` (notice that it doesn't have the second argument, the reason string).

Why did it happen? That depends on your project. The stack trace gives you a hint: `<UnrecognizedContract>.<unknown> (0xe86517f38f6c57e3ce0b009c8a777fad6049a96c)`. This typically happens when you are using mainnet forking and there is a revert in a contract you are interacting with, but that is not part of your project (and therefore it's unrecognized).

> I note that it says an error occurred in the GanacheGasMultiplierProvider but I am not using Ganache at all.

That's an internal Hardhat class, even if it's called like that (I think the name comes from the fact that it mimics some behavior from ganache, but I'm not really sure)

I'm going to close this now because it's not an issue with Hardhat.
