### ISSUE TITLE
Could not generate stack trace. Please report this to help us improve Hardhat

### ISSUE THREAD

**Issue by dadaphl** [NomicFoundation/hardhat#2671]
I got a `Failed to generate 1 stack trace. Run Hardhat with --verbose to learn more.` during testing
Unfortunately I am not able to provide much context.

I started noticing some weird behavior when I tested some deposit / withdraw logic. The contract is complex but the logic in question is banal so it's omitted.

The following test works. But if i remove the line `const contractBalance = await ethers.provider.getBalance(someContract.address);` it fails with oldBalance and newBalance both being 1000.

```javascript
describe("Withdraw", async function () {
  let allSigners;
  let manager, addr1, addr2, addr3;

  before(async () => {
    allSigners = await ethers.getSigners();
    [manager, addr1, addr2, addr3] = allSigners;
  })

  it("can be withdrawn by manager", async function () {
    const depositValue = ethers.utils.parseEther("0.06");
    allSigners.forEach(async account => {
      const call = someContract.connect(account).deposit({value:depositValue});
      await expect(call).to.not.be.reverted;
    });
    const contractBalance = await ethers.provider.getBalance(someContract.address);
    console.log(contractBalance) // is 0 for some reason?

    const oldBalance = await addr3.getBalance();
    await expect(
      someContract.connect(manager).withdraw(addr3.address)
    ).not.to.be.reverted;
    const newBalance = await addr3.getBalance()

    expect(
      newBalance
    ).to.be.equal(
      depositValue.mul(notAllowList.length).add(oldBalance)
    );
  })
})

```

Here is the output of --verbose. 
```
hardhat:core:hardhat-network:node Could not generate stack trace. Please report this to help us improve Hardhat.
hardhat:core:hardhat-network:node  Error: There's no instruction at pc 20411
  at Bytecode.getInstruction (/PROJECTROOT/node_modules/hardhat/src/internal/hardhat-network/stack-traces/model.ts:329:13)
  at SolidityTracer._rawTraceEvmExecution (/PROJECTROOT/node_modules/hardhat/src/internal/hardhat-network/stack-traces/solidityTracer.ts:174:37)
  at SolidityTracer._traceEvmExecution (/PROJECTROOT/node_modules/hardhat/src/internal/hardhat-network/stack-traces/solidityTracer.ts:149:29)
  at SolidityTracer._getCallMessageStackTrace (/PROJECTROOT/node_modules/hardhat/src/internal/hardhat-network/stack-traces/solidityTracer.ts:72:17)
  at SolidityTracer.getStackTrace (/PROJECTROOT/node_modules/hardhat/src/internal/hardhat-network/stack-traces/solidityTracer.ts:56:19)
  at SolidityTracer._getUnrecognizedMessageStackTrace (/PROJECTROOT/node_modules/hardhat/src/internal/hardhat-network/stack-traces/solidityTracer.ts:100:44)
  at SolidityTracer.getStackTrace (/PROJECTROOT/node_modules/hardhat/src/internal/hardhat-network/stack-traces/solidityTracer.ts:59:17)
  at HardhatNode._manageErrors (/PROJECTROOT/node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:1895:41)
  at HardhatNode._gatherTraces (/PROJECTROOT/node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:1652:30)
  at HardhatNode._mineBlockWithPendingTxs (/PROJECTROOT/node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:1772:23) +0ms
```

```
Hardhat version 2.9.3
M1 Mac
Solidity 0.8.4
```

```
  "devDependencies": {
    "@nomiclabs/hardhat-ethers": "^2.0.5",
    "@nomiclabs/hardhat-solhint": "^2.0.0",
    "@nomiclabs/hardhat-waffle": "^2.0.3",
    "chai": "^4.3.6",
    "dotenv": "^16.0.0",
    "ethereum-waffle": "^3.4.0",
    "ethers": "^5.5.4",
    "hardhat": "^2.9.1",
    "hardhat-deploy": "^0.11.2",
    "hardhat-deploy-ethers": "^0.3.0-beta.13",
    "mocha": "^9.2.2",
    "solidity-coverage": "^0.7.20"
  },
...
```

**Comment by mikedizon** [comment]
I'm seeing a similar issue with an arithmetic issue. adding the verbose flag returns the error above. my test fails as I am checking for invalid opcode. tests now return `Transaction reverted without a reason`
