### ISSUE TITLE
Error: Transaction reverted and Hardhat couldn't infer the reason. Please report this to help us improve Hardhat.

### ISSUE THREAD

**Issue by Airwave1981** [NomicFoundation/hardhat#2676]
Hi all,

I'm ending up in an error that sometimes occurs.
At the moment I've not identified, when this happens an when not. But it says I should report it.

Running via test on an local hardhat node.

As you see two contracts are interacting with each other.

Strange is for me, that the last first line  
at BBAUplevel_V2.getUplevel (contracts/BBAUplevel.sol:660)
is NOT called within setTokenURITransformed 

Maybe you have a hint for me to prevent this issue?

Thanks in advance

`

eth_sendTransaction
  Contract call:       <UnrecognizedContract>
  Transaction:         0x680e4584e553368fa66aeb3bfee092c330fdb14780ab3b18364bec3c322932aa
  From:                0x70997970c51812dc3a010c7d01b50e0d17dc79c8
  To:                  0xe7f1725e7734ce288f8367e1bb143e90bb3f0512
  Value:               0 ETH
  Gas used:            1376483 of 1411360
  Block #59:           0x226901835666096b6bb3d46674291c0d9bee6d4be17c7f9d6458a6b2ea858e84

  Error: Transaction reverted and Hardhat couldn't infer the reason. Please report this to help us improve Hardhat.
      at BBAUplevel_V2.getUplevel (contracts/BBAUplevel.sol:660)
      at BBAUplevel_V2.setTokenURITransformed (contracts/BBAUplevel.sol:146)
      at BBAUplevel_V2.registerMintedToken (contracts/BBAUplevel.sol:278)
      at <UnrecognizedContract>.<unknown> (0xe7f1725e7734ce288f8367e1bb143e90bb3f0512)
      at BitBlockArts_V3.safeMintExtend (contracts/BitBlockArts.sol:233)
      at <UnrecognizedContract>.<unknown> (0xcf7ed3acca5a467e9e704c703e8d87f634fb0fc9)
      at BBAUplevel_V2._safeMintExtend (contracts/BBAUplevel.sol:91)
      at BBAUplevel_V2.mintUplevelRandoom (contracts/BBAUplevel.sol:1032)
      at <UnrecognizedContract>.<unknown> (0xe7f1725e7734ce288f8367e1bb143e90bb3f0512)
      at HardhatNode._mineBlockWithPendingTxs (/home/airwave/_NFT/nft-backend/hardhat/node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:1772:23)
      at HardhatNode.mineBlock (/home/airwave/_NFT/nft-backend/hardhat/node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:466:16)
      at EthModule._sendTransactionAndReturnHash (/home/airwave/_NFT/nft-backend/hardhat/node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:1496:18)
      at HardhatNetworkProvider._sendWithLogging (/home/airwave/_NFT/nft-backend/hardhat/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:139:22)
      at HardhatNetworkProvider.request (/home/airwave/_NFT/nft-backend/hardhat/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:116:18)
      at JsonRpcHandler._handleRequest (/home/airwave/_NFT/nft-backend/hardhat/node_modules/hardhat/src/internal/hardhat-network/jsonrpc/handler.ts:188:20)
      at JsonRpcHandler._handleSingleRequest (/home/airwave/_NFT/nft-backend/hardhat/node_modules/hardhat/src/internal/hardhat-network/jsonrpc/handler.ts:167:17)
`

**Comment by Airwave1981** [comment]
This is happening not every run, every second,  third run.
Researched a bit. Could that have to do with gas setting?

The method is quite big in which that happens. Gas Fee Calculator says 442915 gas in average.

Setting of the network is just:

module.exports = {
  defaultNetwork: "localhost",
  networks: {
    localhost: {
      url: "http://127.0.0.1:8545",
      gas: 2100000,
      gasPrice: 8000000000
    },...

**Comment by Airwave1981** [comment]
Okay I tried more around. Seems its just gas, that I need to adjust. 
Its now      gas: 10000000 . Can anybody confirm?

But **### sometimes** then  I get a Bigint error with the .deployProxy command.
Stragely is then, that only this error occurs and all tests run fine.

As it only raises sometimes I'll post the detailed error later.

**Comment by Airwave1981** [comment]
Its this error:

     Deploy MyContract v1:
     Error: overflow (fault="overflow", operation="BigNumber.from", value=15102608000000000, code=NUMERIC_FAULT, version=bignumber/5.5.0)
      at Logger.makeError (node_modules/@ethersproject/logger/src.ts/index.ts:225:28)
      at Logger.throwError (node_modules/@ethersproject/logger/src.ts/index.ts:237:20)
      at throwFault (node_modules/@ethersproject/bignumber/src.ts/bignumber.ts:358:19)
      at Function.BigNumber.from (node_modules/@ethersproject/bignumber/src.ts/bignumber.ts:249:17)
      at formatFixed (node_modules/@ethersproject/bignumber/src.ts/fixednumber.ts:47:23)
      at formatUnits (node_modules/@ethersproject/units/src.ts/index.ts:69:23)
      at Object.formatEther (node_modules/@ethersproject/units/src.ts/index.ts:84:12)
      at Context.<anonymous> (test/MyContract-test.js:157:47)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
