### ISSUE TITLE
Numeric overflow encountered when increased blockGasLimit in the Hardhat Network

### ISSUE THREAD

**Issue by marekyggdrasil** [NomicFoundation/hardhat#2683]
Reproduction steps

```sh
mkdir hardhat-reproduce
cd hardhat-reproduce/
npm init --yes
npm install --save-dev hardhat
npx hardhat
```

now select `Create a basic sample project` and wait for it to finish, then run

```sh
npx hardhat test
```

and observe that the test is passing. Now update your `hardhat.config.js` to increase the `blockGasLimit`

```js
require("@nomiclabs/hardhat-waffle");

// This is a sample Hardhat task. To learn how to create your own go to
// https://hardhat.org/guides/create-task.html
task("accounts", "Prints the list of accounts", async (taskArgs, hre) => {
  const accounts = await hre.ethers.getSigners();

  for (const account of accounts) {
    console.log(account.address);
  }
});

// You need to export an object to set up your config
// Go to https://hardhat.org/config/ to learn more

/**
 * @type import('hardhat/config').HardhatUserConfig
 */
module.exports = {
  networks: {
    hardhat: {
      blockGasLimit: 0x1fffffffffffff
    }
  },
  solidity: "0.8.4",
};
```

and run the test again

```sh
npx hardhat test
```

what I get is

```sh


  Greeter
    1) Should return the new greeting once it's changed


  0 passing (770ms)
  1 failing

  1) Greeter
       Should return the new greeting once it's changed:
     Error: overflow [ See: https://links.ethers.org/v5-errors-NUMERIC_FAULT-overflow ] (fault="overflow", operation="BigNumber.from", value=9007199254740991, code=NUMERIC_FAULT, version=bignumber/5.6.0)
      at Logger.makeError (node_modules/@ethersproject/logger/src.ts/index.ts:261:28)
      at Logger.throwError (node_modules/@ethersproject/logger/src.ts/index.ts:273:20)
      at throwFault (node_modules/@ethersproject/bignumber/src.ts/bignumber.ts:358:19)
      at Function.BigNumber.from (node_modules/@ethersproject/bignumber/src.ts/bignumber.ts:249:17)
      at addGasToAbiMethodsIfNecessary (node_modules/@nomiclabs/hardhat-ethers/src/internal/helpers.ts:372:30)
      at getContractFactoryByAbiAndBytecode (node_modules/@nomiclabs/hardhat-ethers/src/internal/helpers.ts:284:27)
      at Context.<anonymous> (test/sample-test.js:6:21)
```

my Node is

```sh
node -v
v16.15.0
```

thanks in advance for investigating!

**Comment by fvictorio** [comment]
Thanks @marekyggdrasil, this is indeed an issue.

I think there are two things we should do here:

1. Throw a better error if an unsafe integer is used
2. Accept more kinds of values (at the very least native bigints)
