### ISSUE TITLE
TypeError: Cannot read property 'negative' of undefined while using debug_traceTransaction

### ISSUE THREAD

**Issue by zemse** [NomicFoundation/hardhat#2701]
In hardhat tracer, there's a [trace task](https://github.com/zemse/hardhat-tracer#trace) that uses debug_tt in a way mentioned [here](https://hardhat.org/hardhat-network/#the-debug-tracetransaction-method), i.e. getting access to debug_tt using mainnet fork on an archive node.

This used to work, however recently it seems to give the following error on Arbitrum and Optimism:

```
TypeError: Cannot read property 'negative' of undefined
    at BN.cmp (/Users/sohamzemse/Workspace/smart-contract-projects/issue-repro/node_modules/@ethereumjs/tx/node_modules/bn.js/lib/bn.js:2869:36)
    at BN.lt (/Users/sohamzemse/Workspace/smart-contract-projects/issue-repro/node_modules/@ethereumjs/tx/node_modules/bn.js/lib/bn.js:2919:17)
    at VM._runTx (/Users/sohamzemse/Workspace/smart-contract-projects/issue-repro/node_modules/@ethereumjs/vm/src/runTx.ts:298:22)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at VM.runTx (/Users/sohamzemse/Workspace/smart-contract-projects/issue-repro/node_modules/@ethereumjs/vm/src/runTx.ts:204:20)
    at /Users/sohamzemse/Workspace/smart-contract-projects/issue-repro/node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:1387:15
    at VMDebugTracer.trace (/Users/sohamzemse/Workspace/smart-contract-projects/issue-repro/node_modules/hardhat/src/internal/hardhat-network/stack-traces/vm-debug-tracer.ts:76:7)
    at HardhatNode._runInBlockContext (/Users/sohamzemse/Workspace/smart-contract-projects/issue-repro/node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:2136:14)
    at HardhatNetworkProvider.request (/Users/sohamzemse/Workspace/smart-contract-projects/issue-repro/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:118:18)
    at main (/Users/sohamzemse/Workspace/smart-contract-projects/issue-repro/scripts/sample-script.js:37:17)
```

I tried to use old versions of hardhat but surprisingly the error appears in them as well. Just a bit of digging in, it seems that the logic considers the network as an EIP1559 supported network and expects `block.header.baseFeePerGas` to be present but it's undefined.

I've put up a minimal reproduction here: https://github.com/zemse/hardhat-debug-tt-issue-repro

**Comment by zemse** [comment]
The issue still exists, would be great if it's looked at. I have also provided a [minimal reproduction](https://github.com/zemse/hardhat-debug-tt-issue-repro) to make it easier to see.

**Comment by fvictorio** [comment]
Closing in favor of https://github.com/NomicFoundation/hardhat/issues/3479 and https://github.com/NomicFoundation/hardhat/issues/3478
