### ISSUE TITLE
Error: Transaction reverted: function selector was not recognized and there's no fallback function

### ISSUE THREAD

**Issue by PatrickAlphaC** [NomicFoundation/hardhat#2708]
I have a small contract that looks like such:

```solidity
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

contract FundMe {
    address public s_someAddress;

    constructor(address someAddress) {
        s_someAddress = someAddress;
    }

    function fund() public payable {
        // do stuff
    }
}
```

That is deployed to the hardhat network. When I call `fund` from the frontend using [ethers](https://docs.ethers.io/v5/getting-started/#getting-started--importing--web-browser), I get the following error in the terminal my hardhat node is running:

```
eth_call
  Contract call:       <UnrecognizedContract>
  From:                0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266
  To:                  0xe7f1725e7734ce288f8367e1bb143e90bb3f0512

  Error: Transaction reverted without a reason string
      at <UnrecognizedContract>.<unknown> (0xe7f1725e7734ce288f8367e1bb143e90bb3f0512)
      at HardhatNode.runCall (/DIR/node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:615:20)
      at EthModule._callAction (/DIR/node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:353:9)
      at HardhatNetworkProvider._sendWithLogging (/DIR/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:139:22)
      at HardhatNetworkProvider.request (/DIR/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:116:18)
      at JsonRpcHandler._handleRequest (/DIR/node_modules/hardhat/src/internal/hardhat-network/jsonrpc/handler.ts:188:20)
      at JsonRpcHandler._handleSingleRequest (/DIR/node_modules/hardhat/src/internal/hardhat-network/jsonrpc/handler.ts:167:17)
      at Server.JsonRpcHandler.handleHttp (/DIR/node_modules/hardhat/src/internal/hardhat-network/jsonrpc/handler.ts:52:21)
```

However, if I approve the transaction on the front end, it goes through fine. Any code that I have in the `fund` function is successful.

What is happening? 

I have reset my metamask account several times. Here is how I'm calling this function from the front end:

```javascript
async function fund() {
  const ethAmount = "0.1"
  console.log(`Funding with ${ethAmount}`)
  if (typeof window.ethereum !== "undefined") {
    const provider = new ethers.providers.Web3Provider(window.ethereum)
    const signer = provider.getSigner()
    const contract = new ethers.Contract(contractAddress, abi, signer)
    const transactionResponse = await contract.fund({
      value: ethers.utils.parseEther(ethAmount),
    })
  }
}
```

**Comment by feuGeneA** [comment]
Thank you for using Hardhat. GitHub Issues are intended to be used only for known or suspected problems with Hardhat, or for feature requests.  For questions or other help, please use either [our Discord server](https://hardhat.org/discord) or [the GitHub Discussions feature](https://github.com/nomiclabs/hardhat/discussions/) instead.

**Comment by aliveli186** [comment]
I have the same issue. Suspecting that `MetaMask` is trying to send requests to the contract like `supportsInterface` to determine whether it is a NFT or not.
But it's just my guess.

**Comment by FrankFan** [comment]
the same issue for me. Wish someone experienced could help fix this problem. thanks

**Comment by system32uwu** [comment]
This also happens server-side (node.js), so definitely not a metamask issue
