### ISSUE TITLE
`getStorageAt()` rejects properly padded storage addresses starting with zeros

### ISSUE THREAD

**Issue by cameel** [NomicFoundation/hardhat#2709]
Og Hardhat 2.9.5 this code causes an error despite the storage address being correctly padded to 66 characters

```
await ethers.provider.getStorageAt(
    address,
    "0x0000000000000000000000000000000000000000000000000000000000000006"
)
```
```
InvalidArgumentsError: Errors encountered in param 1: Storage slot argument must have a length of 66 ("0x" + 32 bytes), but '0x6' has a length of 3
```

As I understand it something like "0x6" should be rejected but a number with all the leading zeros should not cause this error. Currently both are rejected.

### How to reproduce
Run this in the shell:
```bash
mkdir test/ contracts/

cat <<EOF > hardhat.config.js
require("@nomiclabs/hardhat-waffle");

module.exports = {
    solidity: {
        compilers: [{
            version: "0.8.13",
            settings: {
                viaIR: true,
                optimizer: { enabled: true },
            },
        }]
    }
};
EOF

cat <<EOF > test/GetStorageAtTest.js
const { ethers } = require("hardhat");

const address = "0x1111111111222222222233333333334444444444";

it("getStorageAt() without leading zeros", async () => {
    await ethers.provider.getStorageAt(address, "0x12");
});

it("getStorageAt() with leading zeros", async () => {
    await ethers.provider.getStorageAt(address, "0x00" + "".padEnd(60, "0") + "12");
});

it("getStorageAt() with leading non-zeros", async () => {
    await ethers.provider.getStorageAt(address, "0x12" + "".padEnd(60, "0") + "12");;
});
EOF

cat <<EOF > contracts/C.sol
contract C {}
EOF

npm install hardhat @nomiclabs/hardhat-waffle chai
npx hardhat test
```

Output:
```
  1) getStorageAt() without leading zeros
  2) getStorageAt() with leading zeros
  ✔ getStorageAt() with leading non-zeros

  1 passing (537ms)
  2 failing

  1) getStorageAt() without leading zeros:
     InvalidArgumentsError: Errors encountered in param 1: Storage slot argument must have a length of 66 ("0x" + 32 bytes), but '0x12' has a length of 4
      at validateParams (node_modules/hardhat/src/internal/core/jsonrpc/types/input/validation.ts:64:13)
      at EthModule._getStorageAtParams (node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:695:26)
      at EthModule.processRequest (node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:185:49)
      at HardhatNetworkProvider._send (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:195:31)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at runNextTicks (node:internal/process/task_queues:65:3)
      at listOnTimeout (node:internal/timers:528:9)
      at processTimers (node:internal/timers:502:7)
      at HardhatNetworkProvider.request (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:118:18)
      at EthersProviderWrapper.send (node_modules/@nomiclabs/hardhat-ethers/src/internal/ethers-provider-wrapper.ts:13:20)

  2) getStorageAt() with leading zeros:
     InvalidArgumentsError: Errors encountered in param 1: Storage slot argument must have a length of 66 ("0x" + 32 bytes), but '0x12' has a length of 4
      at validateParams (node_modules/hardhat/src/internal/core/jsonrpc/types/input/validation.ts:64:13)
      at EthModule._getStorageAtParams (node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:695:26)
      at EthModule.processRequest (node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:185:49)
      at HardhatNetworkProvider._send (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:195:31)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at runNextTicks (node:internal/process/task_queues:65:3)
      at listOnTimeout (node:internal/timers:528:9)
      at processTimers (node:internal/timers:502:7)
      at HardhatNetworkProvider.request (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:118:18)
      at EthersProviderWrapper.send (node_modules/@nomiclabs/hardhat-ethers/src/internal/ethers-provider-wrapper.ts:13:20)
```

**Comment by haardikk21** [comment]
Facing the same issue, looks like ethers.js is actually trimming zeroes from the padded string.

**Comment by stobiewan** [comment]
hardhat-ethers 2.0.6 strips the zeros in index.ts:hexValue(), and hardhat 2.9.5 changed the type of slot from quantity to Storageslot which requires all the leading zeros in the validation function.

**Comment by fvictorio** [comment]
I think this comes from ethers. See [this issue](https://github.com/ethers-io/ethers.js/issues/2982). This was working before because both us and ethers were going together against the spec :sweat_smile:

By the way, we recently released a new package (in beta) to help with things like these. If anyone is interested in trying it, check [this doc](https://nomiclabs.notion.site/Public-Hardhat-Network-Helpers-216cf3c665124895bf1f6e2f9343f86f).

I'm going to close this issue now since there's not much we can do on our side.
