### ISSUE TITLE
TypeError: state.buffer is not iterable

### ISSUE THREAD

**Issue by johnmesh** [NomicFoundation/hardhat#2748]
Hardhat throws an error when I try to deploy my smart contract on a different network, other than hardhat network. I've tried everything to no avail. The same issue was reported here https://stackoverflow.com/questions/71435727/typeerror-state-buffer-is-not-iterable-when-using-hardhat. Upgrading node version to 16 didn't work either.
This is the error.
 ```
Uncaught TypeError: state.buffer is not iterable
      at consumeStart (node_modules/undici/lib/api/readable.js:211:29)
      at processTicksAndRejections (internal/process/task_queues.js:84:9)
```
I'm using `hardhat ^2.9.6`

**Comment by johnmesh** [comment]
using node v14.0.0 worked.
