### ISSUE TITLE
Stacktraces do not show the js source location on Solidity revert

### ISSUE THREAD

**Issue by lukehutch** [NomicFoundation/hardhat#2754]
When a transaction is reverted within a contract, the js line containing the contract method call is not shown in the stacktrace. Instead only Hardhat block mining methods are shown:

```
     Error: VM Exception while processing transaction: reverted with reason string 'Some Solidity revert message'
      at MyContract.someMethod (contracts/main/MyContract.sol:100)
      at async HardhatNode._mineBlockWithPendingTxs (node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:1773:23)
      at async HardhatNode.mineBlock (node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:466:16)
      at async EthModule._sendTransactionAndReturnHash (node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:1504:18)
      at async HardhatNetworkProvider.request (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:118:18)
      at async EthersProviderWrapper.send (node_modules/@nomiclabs/hardhat-ethers/src/internal/ethers-provider-wrapper.ts:13:20)
```

**Comment by lukehutch** [comment]
Another example:

```
     Error: call revert exception; VM Exception while processing transaction: reverted with reason string "Some revert message" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="someMethod()", data="some hex data", errorArgs=["Some revert message"], errorName="Error", errorSignature="Error(string)", reason="Some revert message", code=CALL_EXCEPTION, version=abi/5.6.3)
      at Logger.makeError (node_modules/@ethersproject/logger/src.ts/index.ts:261:28)
      at Logger.throwError (node_modules/@ethersproject/logger/src.ts/index.ts:273:20)
      at Interface.decodeFunctionResult (node_modules/@ethersproject/abi/src.ts/interface.ts:427:23)
      at Contract.<anonymous> (node_modules/@ethersproject/contracts/src.ts/index.ts:400:44)
      at step (node_modules/@ethersproject/contracts/lib/index.js:48:23)
      at Object.next (node_modules/@ethersproject/contracts/lib/index.js:29:53)
      at fulfilled (node_modules/@ethersproject/contracts/lib/index.js:20:58)
```

**Comment by lukehutch** [comment]
Still an issue

**Comment by lukehutch** [comment]
Correct, I'm using Ethers for tests, Hardhat for execution. The first stackrace I showed was a Hardhat stacktrace, the second was an ethers stacktrace, both showing the same problem of not including the js line that made the Solidity method invocation.

Ethers 6 is a major revamp, so maybe the situation will improve?

**Comment by hiroshitash** [comment]
Yes, it could be. The stacktrace is thrown by ether.js [here](https://github.com/ethers-io/ethers.js/blob/ec1b9583039a14a0e0fa15d0a2a6082a2f41cf5b/packages/providers/src.ts/json-rpc-provider.ts#L55).

Hardhat should not process the stacktrace message. If we do, we get different error messages depending on deploying on Hardhat or mainnet, which is confusing for debugging.
