### ISSUE TITLE
`npx hardhat test --parallel --network hardhat` ignores command-line network option

### ISSUE THREAD

**Issue by merikonjatta** [NomicFoundation/hardhat#2756]
### Expected behavior:
When you have `defaultNetwork` set in `hardhat.config.js`, and you run `npx hardhat test --parallel --network hardhat`, it should use the network specified in the command line option, not the one in the config file.

### Actual behavior:
It tries to connect to the local network instead and results in `HardhatError: HH108: Cannot connect to the network local.`

### Steps to reproduce:

```
$ mkdir reproduce && cd reproduce
$ npx hardhat
---Choose Create a basic sample project---


$ vim hardhat.config.js
---snip---
module.exports = {
  defaultNetwork: "local",
  solidity: "0.8.4",
  local: {
      url: 'http://127.0.0.1:8545/',
  },
};
---save and quit---


$ npx hardhat test --network hardhat
  Greeter
Deploying a Greeter with greeting: Hello, world!
Changing greeting from 'Hello, world!' to 'Hola, mundo!'
    ✔ Should return the new greeting once it's changed (759ms)
  1 passing (763ms)


$ npx hardhat test --parallel --network hardhat
  Greeter
    1) Should return the new greeting once it's changed
  0 passing (817ms)
  1 failing

  1) Greeter
       Should return the new greeting once it's changed:
     HardhatError: HH108: Cannot connect to the network local.
Please make sure your node is running, and check your internet connection and networks config
      at HttpProvider._fetchJsonRpcResponse (node_modules/hardhat/src/internal/core/providers/http.ts:209:15)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at HttpProvider.request (node_modules/hardhat/src/internal/core/providers/http.ts:84:29)
      at GanacheGasMultiplierProvider._isGanache (node_modules/hardhat/src/internal/core/providers/gas-providers.ts:317:30)
      at GanacheGasMultiplierProvider.request (node_modules/hardhat/src/internal/core/providers/gas-providers.ts:306:23)
      at EthersProviderWrapper.send (node_modules/@nomiclabs/hardhat-ethers/src/internal/ethers-provider-wrapper.ts:13:20)
      at getSigners (node_modules/@nomiclabs/hardhat-ethers/src/internal/helpers.ts:45:20)
      at getContractFactoryByAbiAndBytecode (node_modules/@nomiclabs/hardhat-ethers/src/internal/helpers.ts:280:21)
      at Context.<anonymous> (test/sample-test.js:6:21)
```

(Whitespace in output edited for brevity)

I've tried with different positions for command line options, including

`npx hardhat --network hardhat test --parallel`
`npx hardhat test --parallel --network hardhat`
`npx hardhat test --network hardhat --parallel`

but it doesn't seem to make a difference.

**Comment by fvictorio** [comment]
Thanks a lot for the report @merikonjatta, I can confirm this.

Note for ourselves: the problem is that the global flags are not being propagated to the sub-processes:

https://github.com/NomicFoundation/hardhat/blob/6f291668d5791bf7a3471f465a93326931e4282c/packages/hardhat-core/src/builtin-tasks/test.ts#L90

I wonder if this should be fixed in the core of hardhat instead of the built-in task. That is, maybe Hardhat should have an invariant that, if you can configure something with the environment variable X, then that envvar X will be set in after the runtime is initialized. @alcuadrado thoughts?

**Comment by univerbil** [comment]
passei esses codigos dentro dessa pasta que baixei ignition/modules/solidity-typescript-hardhat-template/node_modules/@ensdomains/ens/contracts$ 
Pegou tudo
