### ISSUE TITLE
abi.decode always reverts

### ISSUE THREAD

**Issue by sirpy** [NomicFoundation/hardhat#2821]
The following contract works fine on remix but reverts on abi.decode when tested using hardhat
```
contract TestDecode {
	event Ratio(uint256 ratio, bytes data);

	function testDecode(		
		bytes calldata data
	) external returns (bool success) {
		uint32 dr = abi.decode(data, (uint32));
		emit Ratio(dr, data);
		return true;
	}
}
```

reverting test:
```
import { ethers } from "hardhat";
describe("testdecode", () => {
  it("should decode", async () => {
    const t = await ethers.getContractFactory("TestDecode");
    const testDecode = await t.deploy();
    await testDecode.testDecode(35);
  });
});
```

revert message
```
 1) testdecode
       should decode:
     Error: Transaction reverted and Hardhat couldn't infer the reason. Please report this to help us improve Hardhat.
      at TestDecode.testDecode (contracts/mocks/TestDecode.sol:5)
      at async HardhatNode._mineBlockWithPendingTxs (node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:1773:23)
      at async HardhatNode.mineBlock (node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:466:16)
      at async EthModule._sendTransactionAndReturnHash (node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:1504:18)
      at async HardhatNetworkProvider.request (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:118:18)
      at async EthersProviderWrapper.send (node_modules/@nomiclabs/hardhat-ethers/src/internal/ethers-provider-wrapper.ts:13:20)
```

**Comment by sirpy** [comment]
seems to be working, probably needed to encode input instead of passing plain 35
