### ISSUE TITLE
signature Error when deploy contract to Ethereum forking environment

### ISSUE THREAD

**Issue by Yihen-Liu** [NomicFoundation/hardhat#2874]
1. hardhat.config.ts content as follow:
```
const config: HardhatUserConfig = {
  defaultNetwork: "hardhat",
  networks: {
    hardhat: {
      forking: {
        url: ALCHEMY_MAINNET,
        blockNumber: 15005580,
      },
      chainId: 1337,
    },
  },
  solidity: {
    version: "0.7.5",
    settings: {
      optimizer: {
        enabled: true,
        runs: 200,
      },
    },
  },
  mocha: {
    timeout: 600000,
  },
  gasReporter: {
    currency: "USD",
    gasPrice: 100,
    coinmarketcap: COINMARKETCAP,
  },
  typechain: {
    outDir: "typechain",
    target: "ethers-v5",
  },
  tenderly: {
    username: "gg2001",
    project: "flashloans",
  },
};
```

2. js deploy script  as follow:
```
async function main() {
	await hre.network.provider.request({
		method: "hardhat_impersonateAccount",
		params: ["0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"]}
	)

	const deployer = await ethers.provider.getSigner("0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266");
  const uniswapFactory: Uniswap__factory = (await ethers.getContractFactory(
    "contracts/Uniswap/Uniswap.sol:Uniswap",
    deployer,
  )) as Uniswap__factory;
  const uniswap: Uniswap = await uniswapFactory.deploy(uniswapFactoryAddress);

  console.log("Uniswap address:", uniswap.address);
}

main()
  .then(() => process.exit(0))
  .catch(error => {
    console.error(error);
    process.exit(1);
  });
```

3. hardhat node start command:
```
npx hardhat node 
```
4. start deploying command:
```
npx hardhat run scripts/Uniswap.ts
```

ERROR INFORMATION:
```
Creating Typechain artifacts in directory typechain for target ethers-v5
Successfully generated Typechain artifacts!
Error: Invalid signature v value
    at Object.exports.ecrecover (/Users/geeker/workspace/DeFi/flashloans/node_modules/hardhat/node_modules/ethereumjs-util/src/signature.ts:46:11)
    at new ForkTransaction (/Users/geeker/workspace/DeFi/flashloans/node_modules/hardhat/src/internal/hardhat-network/provider/fork/ForkTransaction.ts:32:26)
    at ForkBlockchain._processRemoteBlock (/Users/geeker/workspace/DeFi/flashloans/node_modules/hardhat/src/internal/hardhat-network/provider/fork/ForkBlockchain.ts:250:9)
    at ForkBlockchain._getBlockByNumber (/Users/geeker/workspace/DeFi/flashloans/node_modules/hardhat/src/internal/hardhat-network/provider/fork/ForkBlockchain.ts:226:17)
    at ForkBlockchain.getLatestBlock (/Users/geeker/workspace/DeFi/flashloans/node_modules/hardhat/src/internal/hardhat-network/provider/fork/ForkBlockchain.ts:40:19)
    at HardhatNode.takeSnapshot (/Users/geeker/workspace/DeFi/flashloans/node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:645:20)
    at HardhatNode._runInPendingBlockContext (/Users/geeker/workspace/DeFi/flashloans/node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:1417:24)
    at HardhatNode.estimateGas (/Users/geeker/workspace/DeFi/flashloans/node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:459:20)
    at EthModule._estimateGasAction (/Users/geeker/workspace/DeFi/flashloans/node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:396:9)
    at HardhatNetworkProvider.request (/Users/geeker/workspace/DeFi/flashloans/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:100:18)
```

**Comment by FreezyEx** [comment]
Ca you try to run the script as a test? so place it in test folder and run with "test"

**Comment by fvictorio** [comment]
Hi @Yihen-Liu, I don't think there's enough information here to reproduce your problem. Could you please create a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)?

**Comment by fvictorio** [comment]
Closing for lack of MRE.
