### ISSUE TITLE
How to pass array as parameter to CLI plugin

### ISSUE THREAD

**Issue by sunliang711** [NomicFoundation/hardhat#2881]
Hello, I wrote a plugin to deploy contract
```
    task("Deploy", "deploy contract", async (args, hre, runSuper) => {
        const networkName = hre.network.name;
        const networkUrl = hre.network.config.url
        console.log(">> Network Name: ", networkName)
        console.log(">> Network URL: ", networkUrl)
        for (const arg of args.args) {
            console.log(`arg: ${arg}`)
        }

        await hre.run('compile')

        const [...signers] = await hre.ethers.getSigners()
        const owner = signers[0]
        const factory = await hre.ethers.getContractFactory(args.name, owner)
        if (args.args && args.args.length > 0) {
            contract = await factory.deploy(...args.args)
        } else {
            contract = await factory.deploy()
        }
        await contract.deployed()
        const deployTransaction = contract.deployTransaction
        console.log("contract address:", contract.address)
        console.log("tx hash:", deployTransaction.hash)

    })
        .addParam("name", "contract name (Token20, Token721, Token1155)")
        .addOptionalVariadicPositionalParam("args", "constructor arguments")
```

if the contract I want to deploy has a constructor of this form 
```
    constructor(address[] memory signers_) {
        require(signers_.length == 3, "Invalid number of signers");

        for (uint8 i = 0; i < signers_.length; i++) {
            require(signers_[i] != address(0), "Invalid signer");
            signers[signers_[i]] = true;
        }
    }
```

how to pass CLI parameter to my Deploy plugin?

I used 
npx hardhat Deploy --name MultiSig "[0xCe6512491Ad9D7F87b4bdE76368c5C8920600759,0xB44E0D2F23059F93CF4b74025085C93e9df2b5a0,0xB37B8122eDefab3268aE4EaD6B1d2941E08aB4eb]" 
but hardhat notify me with this error msg:
```
An unexpected error occurred:

Error: invalid value for array (argument="value", value="[0xCe6512491Ad9D7F87b4bdE76368c5C8920600759,0xB44E0D2F23059F93CF4b74025085C93e9df2b5a0,0xB37B8122eDefab3268aE4EaD6B1d2941E08aB4eb]", code=INVALID_ARGUMENT, version=contracts/5.5.0)
    at Logger.makeError (/home/eagle/Workspace/node/standard-tokens/node_modules/@ethersproject/logger/src.ts/index.ts:225:28)
    at /home/eagle/Workspace/node/standard-tokens/node_modules/@ethersproject/contracts/src.ts/index.ts:165:42
    at step (/home/eagle/Workspace/node/standard-tokens/node_modules/@ethersproject/contracts/lib/index.js:48:23)
    at Object.next (/home/eagle/Workspace/node/standard-tokens/node_modules/@ethersproject/contracts/lib/index.js:29:53)
    at /home/eagle/Workspace/node/standard-tokens/node_modules/@ethersproject/contracts/lib/index.js:23:71
    at new Promise (<anonymous>)
    at __awaiter (/home/eagle/Workspace/node/standard-tokens/node_modules/@ethersproject/contracts/lib/index.js:19:12)
    at resolveAddresses (/home/eagle/Workspace/node/standard-tokens/node_modules/@ethersproject/contracts/lib/index.js:118:12)
    at /home/eagle/Workspace/node/standard-tokens/node_modules/@ethersproject/contracts/src.ts/index.ts:147:20
    at Array.map (<anonymous>) {
  reason: 'invalid value for array',
  code: 'INVALID_ARGUMENT',
  argument: 'value',
  value: '[0xCe6512491Ad9D7F87b4bdE76368c5C8920600759,0xB44E0D2F23059F93CF4b74025085C93e9df2b5a0,0xB37B8122eDefab3268aE4EaD6B1d2941E08aB4eb]'
}
```

**Comment by SfyMantissa** [comment]
Hello!

The "array" you're passing to your task is still just a string for JS.
In order to correctly parse the input as an array, you need to first split the input string.

Let's take [one of my pet projects as an example](https://github.com/SfyMantissa/TokenMarketplace).

Here I have task _balanceOfBatchSatsuki_ which takes mandatory arguments _accounts_ and _tokenids_ with "arrays" of addresses and token IDs.

As you may see, it works just fine:

```
sfy@neonblaze: ~/repos/TokenMarketplace ❱❱ hh balanceOfBatchSatsuki --accounts "0x9271EfD9709270334721f58f722DDc5C8Ee0E3DF,0x9271EfD9709270334721f58f722DDc5C8Ee0E3DF,0x9271EfD9709270334721f58f722DDc5C8Ee0E3DF" --tokenids "1,2,3"
0x9271EfD9709270334721f58f722DDc5C8Ee0E3DF has 21 of Satsuki tokens with ID 1.
0x9271EfD9709270334721f58f722DDc5C8Ee0E3DF has 101 of Satsuki tokens with ID 2.
0x9271EfD9709270334721f58f722DDc5C8Ee0E3DF has 1 of Satsuki tokens with ID 3.
```

Now let's look at the code of my task:

```
import "@nomiclabs/hardhat-ethers";
import { task } from "hardhat/config";
import config from '../../config';

task("balanceOfBatchSatsuki",
  "Get the Satsuki batch balance for multiple accounts and tokens.")
  .addParam("accounts", "User addresses array.")
  .addParam("tokenids", "IDs of the token collections array.")
  .setAction(async (args, { ethers }) => {
    const Satsuki = await ethers.getContractFactory("Satsuki");
    const satsuki = Satsuki.attach(config.SATSUKI_ADDRESS);

    let accounts = args.accounts.split(',');
    let tokenIds = args.tokenids.split(',');

    const balanceOf = await satsuki.balanceOfBatch(accounts, tokenIds);

    for (let i = 0; i < accounts.length; i++) {
      console.log(accounts[i] + ' has ' + balanceOf[i]
        + ' of Satsuki tokens with ID ' + tokenIds[i] + '.');
    }
  });
```

In

```
    ...
    let accounts = args.accounts.split(',');
    let tokenIds = args.tokenids.split(',');
    ...
```

I parse the input strings to work with them as proper arrays.
I think you need to try doing the same.

Hope this helps.

**Comment by sunliang711** [comment]
Great, thanks !
