### ISSUE TITLE
Bug: Ethers create random broke in new hardhat version

### ISSUE THREAD

**Issue by 0xged** [NomicFoundation/hardhat#2923]
Hey guys! 

When using `ethers` way of creating a random wallet, there is a conflict in `crypto/hash`.

Reproduction:

```typescript
import { ethers } from 'hardhat';
await ethers.Wallet.createRandom()
```

Throws:
```
Error: error:0308010C:digital envelope routines::unsupported
      at new Hash (node:internal/crypto/hash:67:19)
      at createHash (node:crypto:133:10)
      at ripemd160 (node_modules/@ethersproject/sha2/src.ts/sha2.ts:14:29)
      at new HDNode (node_modules/@ethersproject/hdnode/src.ts/index.ts:115:67)
      at Function.HDNode._fromSeed (node_modules/@ethersproject/hdnode/src.ts/index.ts:258:16)
      at Function.HDNode.fromMnemonic (node_modules/@ethersproject/hdnode/src.ts/index.ts:269:23)
      at Function.Wallet.fromMnemonic (node_modules/@ethersproject/wallet/src.ts/index.ts:192:34)
      at Function.Wallet.createRandom (node_modules/@ethersproject/wallet/src.ts/index.ts:177:23)
      at generateRandom (test/utils/wallet.ts:8:23)
      at Context.<anonymous> (test/unit/Greeter.spec.ts:16:25)
      at processImmediate (node:internal/timers:471:21)
```
 

I'm trying to get up to date defi-wonderland solidity-boilerplate: https://github.com/defi-wonderland/solidity-boilerplate/pull/77

**Comment by alcuadrado** [comment]
Have you upgraded node? I'm fairly confident that error comes from Node 17's OpenSSL changes

**Comment by alcuadrado** [comment]
I just checked the PR, and I can confirm that. Do you mind reporting it to ethers and tagging me?

**Comment by 0xged** [comment]
@alcuadrado will do sir!

**Comment by 0xged** [comment]
Issue arises from `ethers` compatibility with node17 and node18 openssl changes, it's not on Nomics Foundation domain.
