### ISSUE TITLE
HardhatError: HH5: HardhatContext is not created.

### ISSUE THREAD

**Issue by EmreYavuzalp** [NomicFoundation/hardhat#2967]
It said to me that this should be reported so this is the error. What I did was to just follow this guide exactly, https://www.freecodecamp.org/news/how-to-make-an-nft/amp/

I typed "node ./scripts/deploy.js" into terminal and it gave me this.

/home/emre/Belgeler/nft-project/ethereum/node_modules/hardhat/internal/context.js:35
            throw new errors_1.HardhatError(errors_list_1.ERRORS.GENERAL.CONTEXT_NOT_CREATED);
            ^

HardhatError: HH5: HardhatContext is not created.
    at Function.getHardhatContext (/home/emre/Belgeler/nft-project/ethereum/node_modules/hardhat/internal/context.js:35:19)
    at extendEnvironment (/home/emre/Belgeler/nft-project/ethereum/node_modules/hardhat/internal/core/config/config-env.js:60:42)
    at Object.<anonymous> (/home/emre/Belgeler/nft-project/ethereum/node_modules/@nomiclabs/hardhat-ethers/internal/index.js:13:32)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/emre/Belgeler/nft-project/ethereum/scripts/deploy.js:1:1) {
  parent: undefined,
  errorDescriptor: {
    number: 5,
    message: 'HardhatContext is not created.',
    title: "Hardhat wasn't initialized",
    description: 'Hardhat initialization failed. This is a bug.\n' +
      '\n' +
      'Please [report it](https://github.com/nomiclabs/hardhat/issues/new) to help us improve Hardhat.',
    shouldBeReported: true
  },
  number: 5,
  messageArguments: {},
  _isHardhatError: true
}

**Comment by feuGeneA** [comment]
Thank you for reporting this. The more information you can provide, the better. Did you double-check that you followed all the instructions in the tutorial? If you found your mistake in following the tutorial, and you've gotten it working now, it may be helpful to report here on what you did, so that we might improve that error message. Thanks again.

**Comment by EmreYavuzalp** [comment]
I will try on another pc some time later. I've been too busy with another projects. Can you not close this just yet?

**Comment by feuGeneA** [comment]
Hi again @EmreYavuzalp . Just checking whether you still intend to pursue this. Thanks again.

**Comment by fvictorio** [comment]
Closing for lack of reproduction steps.
