### ISSUE TITLE
HH1006 error trying to use Chainlink library

### ISSUE THREAD

**Issue by yl0681** [NomicFoundation/hardhat#2983]
user@pop-os:~/.../src$ npx hardhat compile --show-stack-traces
Error HH1006: The file /home/.../contracts/node_modules/@chainlink/contracts/abi/@openzeppelin/contracts/proxy/Proxy.sol is treated as local but is inside a node_modules directory

HardhatError: HH1006: The file /home/.../contracts/node_modules/@chainlink/contracts/abi/@openzeppelin/contracts/proxy/Proxy.sol is treated as local but is inside a node_modules directory
    at localPathToSourceName (/home/.../node_modules/hardhat/src/utils/source-names.ts:132:11)
    at /home/.../node_modules/hardhat/src/builtin-tasks/compile.ts:141:53
    at Array.map (<anonymous>)
    at SimpleTaskDefinition.action (/home/.../node_modules/hardhat/src/builtin-tasks/compile.ts:141:21)
    at Environment._runTaskDefinition (/home/.../node_modules/hardhat/src/internal/core/runtime-environment.ts:219:35)
    at Environment.run (/home/.../node_modules/hardhat/src/internal/core/runtime-environment.ts:131:25)
    at SimpleTaskDefinition.action (/home/.../node_modules/hardhat/src/builtin-tasks/compile.ts:1311:43)
    at Environment._runTaskDefinition (/home/.../node_modules/hardhat/src/internal/core/runtime-environment.ts:219:14)
    at Environment.run (/home/.../node_modules/hardhat/src/internal/core/runtime-environment.ts:131:14)
    at SimpleTaskDefinition.action (/home/.../node_modules/hardhat/src/builtin-tasks/compile.ts:1438:7)

**Comment by yl0681** [comment]
user@pop-os:~/.../src$ npx hardhat --verbose compile
  hardhat:core:config Loading Hardhat config from /home/.../src/hardhat.config.js +0ms
  hardhat:core:global-dir Looking up Client Id at /home/$USER/.local/share/hardhat-nodejs/analytics.json +0ms
  hardhat:core:global-dir Client Id found: 0d39cb56-a55f-4497-ba9a-04e6f4bd4d66 +1ms
  hardhat:core:analytics Sending hit for /task/builtin +0ms
  hardhat:core:analytics Hit payload: {"v":"1","t":"pageview","tid":"UA-117668706-3","cid":"0d39cb56-a55f-4497-ba9a-04e6f4bd4d66","dp":"/task/builtin","dh":"cli.hardhat.org","ua":"Node/v16.15.0 (X11; Linux x86_64)","cs":"Developer","cm":"User Type","cd1":"hardhat-project","cd2":"Developer","cd3":"Hardhat 2.10.1"} +1ms
  hardhat:core:hre Creating HardhatRuntimeEnvironment +0ms
  hardhat:core:hre Running task compile +0ms
  hardhat:core:hre Running task compile:get-compilation-tasks +0ms
  hardhat:core:hre Running task compile:solidity +0ms
  hardhat:core:hre Running task compile:solidity:get-source-paths +0ms
  hardhat:core:hre Running task compile:solidity:get-source-names +52ms
Error HH1006: The file /home/.../src/contracts/node_modules/@chainlink/contracts/abi/@openzeppelin/contracts/proxy/Proxy.sol is treated as local but is inside a node_modules directory

For more info go to https://hardhat.org/HH1006 or run Hardhat with --show-stack-traces
  hardhat:sentry:subprocess starting subprocess +0ms
  hardhat:sentry:subprocess sentry event was sent +8ms

**Comment by alcuadrado** [comment]
Can you please share your project?

**Comment by feuGeneA** [comment]
Hi again @yl0681 . Just checking whether you still intend to pursue this? Thanks.
