### ISSUE TITLE
Hardhat not intercepting eth_getTransactionReceipt RPC call, forwarding it to Alchemy

### ISSUE THREAD

**Issue by robwilkes** [NomicFoundation/hardhat#3000]
I believe I've stumbled upon a bug, it worked fine yesterday, but now isn't.
I've forked mainnet at a specific block, I'm able to submit a transaction, I get back a transaction object with hash, however when I call `.wait()` on that object Hardhat is not intercepting the call and is instead forwarding it to Alchemy, which obviously rejects the request as Hardhat handled the initial transaction request.

Hardhat subsequently goes on to "mine" the transaction, which matches the transactionHash of the transaction request, and the receipt which it proxied to Alchemy.

What I find most confusing is that it was intercepting and handling the eth_getTransactionReceipt calls yesterday.
I cleaned my node_modules and yarn cache and reinstalled everything from scratch, it is still occuring.

script output:
```
{
  hash: '0x49c82f275d7eaff61c09f7fcc73f08f25d103fd6cf3521d8e5ba85120835b47f',
  type: 2,
  accessList: [],
  blockHash: null,
  blockNumber: null,
  transactionIndex: null,
  confirmations: 0,
  from: '0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266',
  gasPrice: BigNumber { value: "23114094422" },
  maxPriorityFeePerGas: BigNumber { value: "1000000000" },
  maxFeePerGas: BigNumber { value: "23114094422" },
  gasLimit: BigNumber { value: "159791" },
  to: '0x00000000006c3852cbEf3e08E8dF289169EdE581',
  value: BigNumber { value: "470000000000000000" },
  nonce: 261,
  data: '0xfb0f3ee100000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000005b50db233e1200000000000000000000000000073e0df1fa0aa2579ad94633ad5b6a32d13d219d4000000000000000000000000004c00500000ad104d7dbd00e3ae0a5c00560c00000000000000000000000000f02edadfe0ccf03d59a70d621d2dae8984a0b67200000000000000000000000000000000000000000000000000000000000001a1000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000062e3535400000000000000000000000000000000000000000000000000000000630c2c4600000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000054b0b1be0a95b30000007b02230091a7ed01230072f7006a004d60a8d4e71d599b8104250f000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000024000000000000000000000000000000000000000000000000000000000000002e000000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000029be90101c60000000000000000000000000008de9c5a032463c561423387a9648c5c7bcc5bc9000000000000000000000000000000000000000000000000000a6fa404071800000000000000000000000000064b43ba3fa45d5fd16a87e6ccc07e14c505247ae00000000000000000000000000000000000000000000000000000000000000417d830529213dc06864800226e3add4716de4cf0e84013a6219b407765dbf417333977cf34ce09056cb5cf5f99ef7414cd8755e8898e96cd280b9ac1d170daafa1b00000000000000000000000000000000000000000000000000000000000000',
  r: '0x2d047a54e002272322965fb2480eccd9617752f20c15c5ccf2ea63663a46a389',
  s: '0x3651a1202b6ee9f182161db547634ee41d6b3687c092c77a3dbbf0420f497442',
  v: 0,
  creates: null,
  chainId: 1,
  wait: [Function (anonymous)]
}
Error: processing response error (body="{\"jsonrpc\":\"2.0\",\"id\":54,\"error\":{\"code\":-32603,\"message\":\"HardhatError: HH110: Invalid JSON-RPC response received: {\\\"jsonrpc\\\":\\\"2.0\\\",\\\"id\\\":4}\",\"data\":{\"message\":\"HardhatError: HH110: Invalid JSON-RPC response received: {\\\"jsonrpc\\\":\\\"2.0\\\",\\\"id\\\":4}\"}}}", error={"code":-32603,"data":{"message":"HardhatError: HH110: Invalid JSON-RPC response received: {\"jsonrpc\":\"2.0\",\"id\":4}"}}, requestBody="{\"method\":\"eth_getTransactionReceipt\",\"params\":[\"0x49c82f275d7eaff61c09f7fcc73f08f25d103fd6cf3521d8e5ba85120835b47f\"],\"id\":54,\"jsonrpc\":\"2.0\"}", requestMethod="POST", url="http://localhost:8545", code=SERVER_ERROR, version=web/5.6.1)
    at Logger.makeError (/home/rob/src/opensea-order-fulfiller/node_modules/@ethersproject/logger/src.ts/index.ts:261:28)
    at Logger.throwError (/home/rob/src/opensea-order-fulfiller/node_modules/@ethersproject/logger/src.ts/index.ts:273:20)
    at /home/rob/src/opensea-order-fulfiller/node_modules/@ethersproject/web/src.ts/index.ts:329:28
    at step (/home/rob/src/opensea-order-fulfiller/node_modules/@ethersproject/web/lib/index.js:33:23)
    at Object.next (/home/rob/src/opensea-order-fulfiller/node_modules/@ethersproject/web/lib/index.js:14:53)
    at fulfilled (/home/rob/src/opensea-order-fulfiller/node_modules/@ethersproject/web/lib/index.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  reason: 'processing response error',
  code: 'SERVER_ERROR',
  body: '{"jsonrpc":"2.0","id":54,"error":{"code":-32603,"message":"HardhatError: HH110: Invalid JSON-RPC response received: {\\"jsonrpc\\":\\"2.0\\",\\"id\\":4}","data":{"message":"HardhatError: HH110: Invalid JSON-RPC response received: {\\"jsonrpc\\":\\"2.0\\",\\"id\\":4}"}}}',
  error: Error: HardhatError: HH110: Invalid JSON-RPC response received: {"jsonrpc":"2.0","id":4}
      at getResult (/home/rob/src/opensea-order-fulfiller/node_modules/@ethersproject/providers/src.ts/json-rpc-provider.ts:142:28)
      at processJsonFunc (/home/rob/src/opensea-order-fulfiller/node_modules/@ethersproject/web/src.ts/index.ts:371:22)
      at /home/rob/src/opensea-order-fulfiller/node_modules/@ethersproject/web/src.ts/index.ts:308:42
      at step (/home/rob/src/opensea-order-fulfiller/node_modules/@ethersproject/web/lib/index.js:33:23)
      at Object.next (/home/rob/src/opensea-order-fulfiller/node_modules/@ethersproject/web/lib/index.js:14:53)
      at fulfilled (/home/rob/src/opensea-order-fulfiller/node_modules/@ethersproject/web/lib/index.js:5:58)
      at processTicksAndRejections (node:internal/process/task_queues:96:5) {
    code: -32603,
    data: {
      message: 'HardhatError: HH110: Invalid JSON-RPC response received: {"jsonrpc":"2.0","id":4}'
    }
  },
  requestBody: '{"method":"eth_getTransactionReceipt","params":["0x49c82f275d7eaff61c09f7fcc73f08f25d103fd6cf3521d8e5ba85120835b47f"],"id":54,"jsonrpc":"2.0"}',
  requestMethod: 'POST',
  url: 'http://localhost:8545'
}
error Command failed with exit code 1.
```

hardhat node output:
```
eth_chainId (2)
eth_getBlockByNumber
eth_accounts
eth_call
  Contract call: <UnrecognizedContract>
  From:          0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266
  To:            0xd130b43062d875a4b7af3f8fc036bc6e9d3e1b3e

eth_blockNumber
eth_chainId (2)
eth_estimateGas
eth_sendTransaction
eth_chainId
eth_getTransactionByHash
eth_chainId
eth_getTransactionReceipt

  If you think this is a bug in Hardhat, please report it here: https://hardhat.org/report-bug

Mined block #15235531
  Block: 0x25f1f42ae678da4f36d31a32ae9b39703a99d332d7663464d506d0fb2c704d5b
    Base fee: 11057047211
    Transaction:     0x49c82f275d7eaff61c09f7fcc73f08f25d103fd6cf3521d8e5ba85120835b47f
      Contract call: <UnrecognizedContract>
      From:          0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266
      To:            0x00000000006c3852cbef3e08e8df289169ede581
      Value:         0.47 ETH
      Gas used:      149841 of 159791
```

Here is the request that was forwarded to Alchemy rather than being intercepted:
![image](https://user-images.githubusercontent.com/4636768/181699614-c5cf351d-2293-48aa-83a2-e39e59f5dfcf.png)

scripts/main.ts
```typescript
import { ethers } from "hardhat";
import { Seaport } from "@opensea/seaport-js/lib/seaport";
import { OrderWithCounter } from "@opensea/seaport-js/lib/types";
import { assert } from "console";

async function main() {
    const wallet = new ethers.Wallet(
        "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80",
        ethers.provider
    );
    const seaport = new Seaport(ethers.provider);

    const order: OrderWithCounter = JSON.parse(
        `{"parameters": {"offerer": "0x73e0df1fa0aa2579ad94633ad5b6a32d13d219d4", "offer": [{"itemType": 2, "token": "0xf02EDAdfe0ccf03d59A70d621D2DAE8984a0B672", "identifierOrCriteria": "417", "startAmount": "1", "endAmount": "1"}], "consideration": [{"itemType": 0, "token": "0x0000000000000000000000000000000000000000", "identifierOrCriteria": "0", "startAmount": "411250000000000000", "endAmount": "411250000000000000", "recipient": "0x73E0DF1fA0aA2579aD94633aD5B6a32D13D219D4"}, {"itemType": 0, "token": "0x0000000000000000000000000000000000000000", "identifierOrCriteria": "0", "startAmount": "11750000000000000", "endAmount": "11750000000000000", "recipient": "0x8De9C5A032463C561423387a9648c5C7BCC5BC90"}, {"itemType": 0, "token": "0x0000000000000000000000000000000000000000", "identifierOrCriteria": "0", "startAmount": "47000000000000000", "endAmount": "47000000000000000", "recipient": "0x64b43Ba3Fa45D5fd16A87E6cCc07E14c505247aE"}], "startTime": "1659065172", "endTime": "1661742150", "orderType": 2, "zone": "0x004C00500000aD104D7DBd00e3ae0A5C00560C00", "zoneHash": "0x0000000000000000000000000000000000000000000000000000000000000000", "salt": "23838175487759795", "conduitKey": "0x0000007b02230091a7ed01230072f7006a004d60a8d4e71d599b8104250f0000", "totalOriginalConsiderationItems": 3, "counter": 0}, "signature": "0x7d830529213dc06864800226e3add4716de4cf0e84013a6219b407765dbf417333977cf34ce09056cb5cf5f99ef7414cd8755e8898e96cd280b9ac1d170daafa1b"}`
    );

    const { actions } = await seaport.fulfillOrder({
        order: order,
        accountAddress: wallet.address,
    });

    assert(actions.length === 1);
    const action = actions[0];
    assert(action.type === "exchange");

    const transaction = await action.transactionMethods.transact();
    console.log(transaction);
    const receipt = await transaction.wait();
    console.log(receipt);
}

main()
    .then(() => process.exit(0))
    .catch((error) => {
        console.error(error);
        process.exit(1);
    });
```

hardhat.config.ts:
```typescript
import { HardhatUserConfig } from "hardhat/config";
import "@nomicfoundation/hardhat-toolbox";

const config: HardhatUserConfig = {
  solidity: "0.8.9",
  defaultNetwork: "hardhat",
  networks: {
    hardhat: {
      mining: {
        auto: false,
        interval: 12000
      },
      forking: {
        url: "<removed>",
        blockNumber: 15235530,
      },
      gas: 6721975,
      chainId: 1
    }
  }
};

export default config;
```

**Comment by robwilkes** [comment]
Just as an FYI, if I point it at Ganache it works, so it definitely appears to be an issue with Hardhat, and Hardhat had been working fine all week, it just started doing this about 6 hours ago which is very strange since the package versions and code being run are unchanged

**Comment by robwilkes** [comment]
This was it working 2 days ago... The sequence of events on Hardhat node...

![image](https://user-images.githubusercontent.com/4636768/181708055-ed39f21e-5c66-43eb-9cea-3d1a8e54329d.png)

**Comment by peteMint** [comment]
Seeing same errors here in our projects.  Using alchemy RPC endpoint we see the error (empty response in getTransactionReceipt).  However if we switch to a public or infura endpoint our deployment will work.  So either Alchemy incorrectly forming the null response or hardhat too strict in handling it?

**Comment by robwilkes** [comment]
> Seeing same errors here in our projects. Using alchemy RPC endpoint we see the error (empty response in getTransactionReceipt). However if we switch to a public or infura endpoint our deployment will work. So either Alchemy incorrectly forming the null response or hardhat too strict in handling it? We see this across both Rinkeby and polygon Mumbai when using the Alchemy RPC endpoints via hardhat

Thanks for point this out! By the way it's working again with Alchemy now. Seems Hardhat is expecting a `"result": null` parameter in the response object and Alchemy wasn't providing it, if it was a bit more verbose about why it was failing I might have tried another provider haha.

Love Hardhat, the time it's saved me more than makes up for the time lost today due to an obscure error response.

![image](https://user-images.githubusercontent.com/4636768/181801280-973166ce-c313-4c96-82f1-2710519251a6.png)

**Comment by adatta02** [comment]
FYI something similar is happening with me on Truffle with Alchemy when I try to deploy a contract. This only started happening in the last 2 weeks.

The contract TX is successful but the "eth_getTransactionReceipt" call returns a -3200 from Alchemy. Truffle seems to never retry the eth_getTransactionReceipt call after receiving the -3200 response so I assume its not expected. If I re-run that request manually after a minute or two the expected response comes back.

![Screenshot from 2022-10-03 15-16-30](https://user-images.githubusercontent.com/51879/193660187-6fe8a6c9-30b5-4d0e-970c-a28172496d7f.png)
