### ISSUE TITLE
Plugin reports invalid API key on valid key

### ISSUE THREAD

**Issue by WarTech9** [NomicFoundation/hardhat#3018]
Trying to verify contracts using the `@nomiclabs/hardhat-etherscan` plugin. I receive the following error: 

`caught verification error [depositoryImpl] NomicLabsHardhatPluginError: Invalid API Key`

```
at verifyContract (.../node_modules/@nomiclabs/hardhat-etherscan/src/etherscan/EtherscanService.ts:70:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async attemptVerification (.../node_modules/@nomiclabs/hardhat-etherscan/src/index.ts:461:20)
    at async SimpleTaskDefinition.action (.../node_modules/@nomiclabs/hardhat-etherscan/src/index.ts:765:48)
    at async Environment._runTaskDefinition (.../node_modules/hardhat/src/internal/core/runtime-environment.ts:219:14)
    at async Environment.run (.../node_modules/hardhat/src/internal/core/runtime-environment.ts:131:14)
    at async SimpleTaskDefinition.verifySubtask [as action] (.../node_modules/@nomiclabs/hardhat-etherscan/src/index.ts:299:28)
    at async Environment._runTaskDefinition (.../node_modules/hardhat/src/internal/core/runtime-environment.ts:219:14)
    at async Object.Environment.run (.../node_modules/hardhat/src/internal/core/runtime-environment.ts:131:14)
```

This seems to be a regression because I was using the same verification script and API key for several months without any errors. Also validated that the API key is still valid by making http requests directly to etherscan using that key and they still work, but the plugin reports the key as invalid. 
The contracts being verified are on optimism kovan network.

**Comment by Enigmatic331** [comment]
Hi @WarTech9 - Could you give it another shot please? We've recently fixed up a couple bugs with OP-Kovan's contract verification endpoint which also solve issues with intermittent invalid api keys - Feel free to reach out if it might still be persisting, and will take a look as well.

**Comment by WarTech9** [comment]
This

> Hi @WarTech9 - Could you give it another shot please? We've recently fixed up a couple bugs with OP-Kovan's contract verification endpoint which also solve issues with intermittent invalid api keys - Feel free to reach out if it might still be persisting, and will take a look as well.

I can confirm I am not having this issue anymore. Thanks for your quick resolution
