### ISSUE TITLE
unintelligible error:  Internal exception in StandardCompiler::compile:

### ISSUE THREAD

**Issue by grapevinegizmos** [NomicFoundation/hardhat#3022]
The last time I compiled, I got this error.  I have 15 or so contracts in my project, and the error message is no help telling me where the error might be happening, or why, So pretty much impossible to provide minimal reproducible.

Any ideas?

```
 Internal exception in StandardCompiler::compile: /Users/distiller/project/libsolidity/ast/Types.cpp(2231): Throw in function virtual MemberList::MemberMap solidity::frontend::StructType::nativeMembers(const solidity::frontend::ASTNode *) const
Dynamic exception type: boost::wrapexcept<solidity::langutil::InternalCompilerError>
std::exception::what: 
[solidity::util::tag_comment*] = 

Error HH600: Compilation failed

HardhatError: HH600: Compilation failed
    at SimpleTaskDefinition.action (/Users/joshkramer/Documents/VSCodeProjects/BKopy/bkopy-embedded-contracts/node_modules/hardhat/src/builtin-tasks/compile.ts:470:15)
    at async Environment._runTaskDefinition (/Users/joshkramer/Documents/VSCodeProjects/BKopy/bkopy-embedded-contracts/node_modules/hardhat/src/internal/core/runtime-environment.ts:219:14)
    at async OverriddenTaskDefinition._action (/Users/joshkramer/Documents/VSCodeProjects/BKopy/bkopy-embedded-contracts/node_modules/@typechain/hardhat/src/index.ts:30:30)
    at async Environment._runTaskDefinition (/Users/joshkramer/Documents/VSCodeProjects/BKopy/bkopy-embedded-contracts/node_modules/hardhat/src/internal/core/runtime-environment.ts:219:14)
    at async Environment.run (/Users/joshkramer/Documents/VSCodeProjects/BKopy/bkopy-embedded-contracts/node_modules/hardhat/src/internal/core/runtime-environment.ts:131:14)
    at async SimpleTaskDefinition.action (/Users/joshkramer/Documents/VSCodeProjects/BKopy/bkopy-embedded-contracts/node_modules/hardhat/src/builtin-tasks/compile.ts:1358:63)
    at async Environment._runTaskDefinition (/Users/joshkramer/Documents/VSCodeProjects/BKopy/bkopy-embedded-contracts/node_modules/hardhat/src/internal/core/runtime-environment.ts:219:14)
    at async Environment.run (/Users/joshkramer/Documents/VSCodeProjects/BKopy/bkopy-embedded-contracts/node_modules/hardhat/src/internal/core/runtime-environment.ts:131:14)
    at async SimpleTaskDefinition.action (/Users/joshkramer/Documents/VSCodeProjects/BKopy/bkopy-embedded-contracts/node_modules/hardhat/src/builtin-tasks/compile.ts:1438:7)
    at async Environment._runTaskDefinition (/Users/joshkramer/Documents/VSCodeProjects/BKopy/bkopy-embedded-contracts/node_modules/hardhat/src/internal/core/runtime-environment.ts:219:14)
```

**Comment by fvictorio** [comment]
This seems a `solc` problem. @cameel do you recognize this problem?

**Comment by cameel** [comment]
Yeah, this is a failed assert so you hit some bug in the compiler. This does not seem to be the latest compiler (otherwise the message would not be empty) so it could have already been fixed. Check out these [already fixed bugs that were triggering an assert in `nativeMembers()`](https://github.com/ethereum/solidity/issues?q=is%3Aissue+nativemembers+is%3Aclosed).

I'd suggest trying the latest compiler and if it's still happening, [please file an issue](https://github.com/ethereum/solidity/issues/new). If you have trouble trimming the repro to a reasonable size we could help, as long as the code is available somewhere.

**Comment by fvictorio** [comment]
I'm closing this since it's not related to Hardhat. Thanks a lot @cameel for chiming in!
