### ISSUE TITLE
signer.signMessage message fails when run on hardhat node.

### ISSUE THREAD

**Issue by BKopyIo** [NomicFoundation/hardhat#3056]
From looking at the history here, it seems liked this problem was solved, but when I run this test:
```
it('can sign something', async()=>{
        let message = "Hello world";
        let [signer] = await ethers.getSigners();
        let signature = await signer.signMessage(message)
    })
```
using just `hh test` it works fine, but if a I start a hardhat node on localhost and then run it using `hh test --network localhost` it fails with
```
 1) Test on localhost
       can sign something:
     ProviderError: Method personal_sign not found
      at HttpProvider.request (node_modules/hardhat/src/internal/core/providers/http.ts:78:19)
      at AutomaticSenderProvider.request (node_modules/hardhat/src/internal/core/providers/accounts.ts:351:34)
      at AutomaticGasProvider.request (node_modules/hardhat/src/internal/core/providers/gas-providers.ts:136:34)
      at AutomaticGasPriceProvider.request (node_modules/hardhat/src/internal/core/providers/gas-providers.ts:153:36)
      at BackwardsCompatibilityProviderAdapter.send (node_modules/hardhat/src/internal/core/providers/backwards-compatibility.ts:36:27)
      at EthersProviderWrapper.send (node_modules/@nomiclabs/hardhat-ethers/src/internal/ethers-provider-wrapper.ts:13:48)
      at JsonRpcSigner.<anonymous> (node_modules/@ethersproject/providers/src.ts/json-rpc-provider.ts:295:36)
      at step (node_modules/@ethersproject/providers/lib/json-rpc-provider.js:48:23)
      at Object.next (node_modules/@ethersproject/providers/lib/json-rpc-provider.js:29:53)
      at fulfilled (node_modules/@ethersproject/providers/lib/json-rpc-provider.js:20:58)
```

**Comment by feuGeneA** [comment]
Thank you for using Hardhat.

In general, if there is a problem in Hardhat, we will need a minimal reproducible example in order to investigate it. See https://stackoverflow.com/help/minimal-reproducible-example

Can you provide us with a minimal reproducible example?

**Comment by BKopyIo** [comment]
Sure, here is the test:

```
import { ethers } from "hardhat";

describe.only('Try hardhat sign on node',  () => {
    it('attempts to sign', async ()=>{
        let [signer0] = await ethers.getSigners();
        let text = "I am Foo";
        let signature = await signer0.signMessage(text);
        console.log(signature);
    });
});
```

And here is the output in the VS Code Console:
 ```
 1) Try hardhat sign on node
       attempts to sign:
     ProviderError: Method personal_sign not found
      at HttpProvider.request (node_modules/hardhat/src/internal/core/providers/http.ts:78:19)
      at AutomaticSenderProvider.request (node_modules/hardhat/src/internal/core/providers/accounts.ts:351:34)
      at AutomaticGasProvider.request (node_modules/hardhat/src/internal/core/providers/gas-providers.ts:136:34)
      at AutomaticGasPriceProvider.request (node_modules/hardhat/src/internal/core/providers/gas-providers.ts:153:36)
      at BackwardsCompatibilityProviderAdapter.send (node_modules/hardhat/src/internal/core/providers/backwards-compatibility.ts:36:27)
      at EthersProviderWrapper.send (node_modules/@nomiclabs/hardhat-ethers/src/internal/ethers-provider-wrapper.ts:13:48)
      at JsonRpcSigner.<anonymous> (node_modules/@ethersproject/providers/src.ts/json-rpc-provider.ts:295:36)
      at step (node_modules/@ethersproject/providers/lib/json-rpc-provider.js:48:23)
      at Object.next (node_modules/@ethersproject/providers/lib/json-rpc-provider.js:29:53)
      at fulfilled (node_modules/@ethersproject/providers/lib/json-rpc-provider.js:20:58)
```

And here is the terminal output which is running `npx hardhat node`
```

Account #18: 0xdd2fd4581271e230360230f9337d5c0430bf44c0 (10000 ETH)
Private Key: 0xde9be858da4a47527642_5e9262ecfc3ba460bfac56360bfa6c4c28b4ee0

Account #19: 0x8626f6940e2eb28930efb4cef49b2d1f2c9c1199 (10000 ETH)
Private Key: 0xdf57089febbacf7ba0bc___dafbffa9fc08a93fdc68e1e42411a14efcf23656e

eth_chainId (3)
eth_getBlockByNumber
eth_accounts
personal_sign - Method not supported
```

And hereis the NPM version info
```

Joshs-MacBook-Pro:bkopy-embedded-contracts joshkramer$ npm list hardhat
@bkopyio/api@0.1.16 /Users/joshkramer/Documents/VSCodeProjects/BKopy/bkopy-embedded-contracts
├─┬ @nomiclabs/hardhat-ethers@2.1.0
│ └── hardhat@2.10.0 deduped
├─┬ @nomiclabs/hardhat-etherscan@3.1.0
│ └── hardhat@2.10.0 deduped
├─┬ @nomiclabs/hardhat-waffle@2.0.3
│ └── hardhat@2.10.0 deduped
├─┬ @typechain/hardhat@2.3.1
│ └── hardhat@2.10.0 deduped
├─┬ hardhat-contract-sizer@2.5.1
│ └── hardhat@2.10.0 deduped
├─┬ hardhat-gas-reporter@1.0.8
│ └── hardhat@2.10.0 deduped
└── hardhat@2.10.0
```

**Comment by sumer-meso** [comment]
any updates on this?

**Comment by fvictorio** [comment]
I can't reproduce this using the latest versions of Hardhat and Ethers. If someone has this problem, then please:

1) Open a new issue with a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)
2) Include the versions of Hardhat,ethers.js and hardhat-ethers that you are using.
