### ISSUE TITLE
MBP M1 Pro hardhat@2.11.0 leads to Error: spawn Unknown system error -86

### ISSUE THREAD

**Issue by briannnyee** [NomicFoundation/hardhat#3126]
I'm using MBP M1 Pro. I got following error after upgrading to hardhat@2.11.0
```
Error: spawn Unknown system error -86
    at ChildProcess.spawn (node:internal/child_process:413:11)
    at spawn (node:child_process:700:9)
    at execFile (node:child_process:327:17)
    at output (/Users/0x8ri4ny33/Desktop/Projects/test/node_modules/hardhat/src/internal/solidity/compiler/index.ts:65:31)
    at new Promise (<anonymous>)
    at NativeCompiler.compile (/Users/0x8ri4ny33/Desktop/Projects/test/node_modules/hardhat/src/internal/solidity/compiler/index.ts:64:34)
    at SimpleTaskDefinition.action (/Users/0x8ri4ny33/Desktop/Projects/test/node_modules/hardhat/src/builtin-tasks/compile.ts:639:37)
    at Environment._runTaskDefinition (/Users/0x8ri4ny33/Desktop/Projects/test/node_modules/hardhat/src/internal/core/runtime-environment.ts:308:35)
    at Environment.run (/Users/0x8ri4ny33/Desktop/Projects/test/node_modules/hardhat/src/internal/core/runtime-environment.ts:156:25)
    at SimpleTaskDefinition.action (/Users/0x8ri4ny33/Desktop/Projects/test/node_modules/hardhat/src/builtin-tasks/compile.ts:700:24) {
  errno: -86,
  code: 'Unknown system error -86',
  syscall: 'spawn'
}
```

Reproduction steps,

1. `mkdir test && cd test`
2. `npm init`
3. `npm install hardhat`
4. `npx hardhat` , select `Create a JavaScript project`
5. `npx hardhat compile`
6. The error message will pop up

Fix for now,

1. type `npm install hardhat@2.10.1` instead of `npm install hardhat`

**Comment by alcuadrado** [comment]
Can you try running `npx hardhat clean --global` and try again?

**Comment by briannnyee** [comment]
Hi @alcuadrado, 

After running the command, the error becomes
```
Downloading compiler 0.8.9
Downloading compiler 0.8.9
Error HH11: An internal invariant was violated: WASM build of solc 0.8.9 isn't working

For more info go to https://hardhat.org/HH11 or run Hardhat with --show-stack-traces
```
The document describes the error as below,

>[HH11: Invariant violation](https://hardhat.org/hardhat-runner/docs/errors#HH11)
An internal invariant was violated. This is probably caused by a programming error in hardhat or in one of the used plugins.

> Please [report it](https://github.com/nomiclabs/hardhat/issues/new) to help us improve Hardhat.

For those who are having the same issue, downgrading to version 2.10.1 works just fine.

**Comment by briannnyee** [comment]
In case you guys need these to fix the thing, here are the stack traces
```
❯ hh compile --show-stack-traces                                                                                                     ─╯
Error HH11: An internal invariant was violated: WASM build of solc 0.8.9 isn't working

HardhatError: HH11: An internal invariant was violated: WASM build of solc 0.8.9 isn't working
    at assertHardhatInvariant (/Users/briannnyee/Desktop/Projects/test/node_modules/hardhat/src/internal/core/errors.ts:272:11)
    at SimpleTaskDefinition.action (/Users/briannnyee/Desktop/Projects/test/node_modules/hardhat/src/builtin-tasks/compile.ts:596:29)
    at Environment._runTaskDefinition (/Users/briannnyee/Desktop/Projects/test/node_modules/hardhat/src/internal/core/runtime-environment.ts:308:14)
    at Environment.run (/Users/briannnyee/Desktop/Projects/test/node_modules/hardhat/src/internal/core/runtime-environment.ts:156:14)
    at SimpleTaskDefinition.action (/Users/briannnyee/Desktop/Projects/test/node_modules/hardhat/src/builtin-tasks/compile.ts:678:36)
    at Environment._runTaskDefinition (/Users/briannnyee/Desktop/Projects/test/node_modules/hardhat/src/internal/core/runtime-environment.ts:308:14)
    at Environment.run (/Users/briannnyee/Desktop/Projects/test/node_modules/hardhat/src/internal/core/runtime-environment.ts:156:14)
    at Environment._runTaskDefinition (/Users/briannnyee/Desktop/Projects/test/node_modules/hardhat/src/internal/core/runtime-environment.ts:308:14)
    at Environment.run (/Users/briannnyee/Desktop/Projects/test/node_modules/hardhat/src/internal/core/runtime-environment.ts:156:14)
    at SimpleTaskDefinition.action (/Users/briannnyee/Desktop/Projects/test/node_modules/hardhat/src/builtin-tasks/compile.ts:962:37)
```

**Comment by fvictorio** [comment]
This should work with `hardhat@2.11.1`. Please upgrade and let us know if the issue is still there.

**Comment by briannnyee** [comment]
With `hardhat@2.11.1` the issue is perfectly solved! Thank you!

**Comment by alcuadrado** [comment]
@briannnyee also, I think you don't have Rosetta installed. Installing it will make hardhat compile much faster!

**Comment by briannnyee** [comment]
> @briannnyee also, I think you don't have Rosetta installed. Installing it will make hardhat compile much faster!

Just gave it a try, it compiles faster than the speed of light ;)
