### ISSUE TITLE
Bug: Polygon forking is broken with 2.11.0

### ISSUE THREAD

**Issue by egorFiNE** [NomicFoundation/hardhat#3133]
Hardhat fails to execute `eth_call` on forked Polygon network with hardhat 2.11.0 but works perfectly with 2.10.2 and earlier. Here's a test case: 

1. Fork polygon with hardhat 2.11.0:

```bash
npx hardhat node --fork https://polygon-rpc.com/ --no-deploy --port 7545 --verbose
```

2. Edit `hardhat.config.js`: 

```js
  networks: {
    forked: {
      url: 'http://127.0.0.1:7545'
    },
```

3. Call basic contract in the console: 

```
npx hardhat --network forked console

> const USDT = await ethers.getContractAt('ERC20', '0xc2132D05D31c914a87C6611C10748AEb04B58e8F'); // USDT 
undefined

> await USDT.symbol();
Uncaught:
Error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266","to":"0xc2132D05D31c914a87C6611C10748AEb04B58e8F","data":"0x95d89b41","accessList":null}, error={"name":"ProviderError","_stack":"ProviderError: HttpProviderError\n    at HttpProvider.request (/Users/egor/workspace/ariadne-v2-contracts/node_modules/hardhat/src/internal/core/providers/http.ts:78:19)\n    at AutomaticSenderProvider.request (/Users/egor/workspace/ariadne-v2-contracts/node_modules/hardhat/src/internal/core/providers/accounts.ts:341:34)\n    at AutomaticGasProvider.request (/Users/egor/workspace/ariadne-v2-contracts/node_modules/hardhat/src/internal/core/providers/gas-providers.ts:135:34)\n    at AutomaticGasPriceProvider.request (/Users/egor/workspace/ariadne-v2-contracts/node_modules/hardhat/src/internal/core/providers/gas-providers.ts:153:36)\n    at BackwardsCompatibilityProviderAdapter.send (/Users/egor/workspace/ariadne-v2-contracts/node_modules/hardhat/src/internal/core/providers/backwards-compatibility.ts:36:27)\n    at EthersProviderWrapper.send (/Users/egor/workspace/ariadne-v2-contracts/node_modules/@nomiclabs/hardhat-ethers/src/internal/ethers-provider-wrapper.ts:13:48)\n    at EthersProviderWrapper.<anonymous> (/Users/egor/workspace/ariadne-v2-contracts/node_modules/@ethersproject/providers/src.ts/json-rpc-provider.ts:642:31)\n    at step (/Users/egor/workspace/ariadne-v2-contracts/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:48:23)\n    at Object.next (/Users/egor/workspace/ariadne-v2-contracts/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:29:53)\n    at /Users/egor/workspace/ariadne-v2-contracts/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:23:71","code":-32603,"_isProviderError":true,"data":{"message":"Error: invalid amount of extra data (block header number=32720987 hash=0x331d0f05f1eda8c676a673951e2d04f875c3de329258bd63d0b8e577ffc03007 hf=arrowGlacier baseFeePerGas=98)"}}, code=CALL_EXCEPTION, version=providers/5.7.0)
    at step (/Users/egor/workspace/ariadne-v2-contracts/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:48:23)
    at EthersProviderWrapper.<anonymous> (/Users/egor/workspace/ariadne-v2-contracts/node_modules/@ethersproject/providers/src.ts/json-rpc-provider.ts:644:20)
    at checkError (/Users/egor/workspace/ariadne-v2-contracts/node_modules/@ethersproject/providers/src.ts/json-rpc-provider.ts:66:16)
    at Logger.throwError (/Users/egor/workspace/ariadne-v2-contracts/node_modules/@ethersproject/logger/src.ts/index.ts:281:20)
    at Logger.makeError (/Users/egor/workspace/ariadne-v2-contracts/node_modules/@ethersproject/logger/src.ts/index.ts:269:28) {
  reason: 'missing revert data in call exception; Transaction reverted without a reason string',
  code: 'CALL_EXCEPTION',
  data: '0x',
  transaction: {
    from: '0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266',
    to: '0xc2132D05D31c914a87C6611C10748AEb04B58e8F',
    data: '0x95d89b41',
    accessList: null
  },
  error: ProviderError: HttpProviderError
      at HttpProvider.request (/Users/egor/workspace/ariadne-v2-contracts/node_modules/hardhat/src/internal/core/providers/http.ts:78:19)
      at AutomaticSenderProvider.request (/Users/egor/workspace/ariadne-v2-contracts/node_modules/hardhat/src/internal/core/providers/accounts.ts:341:34)
      at AutomaticGasProvider.request (/Users/egor/workspace/ariadne-v2-contracts/node_modules/hardhat/src/internal/core/providers/gas-providers.ts:135:34)
      at AutomaticGasPriceProvider.request (/Users/egor/workspace/ariadne-v2-contracts/node_modules/hardhat/src/internal/core/providers/gas-providers.ts:153:36)
      at BackwardsCompatibilityProviderAdapter.send (/Users/egor/workspace/ariadne-v2-contracts/node_modules/hardhat/src/internal/core/providers/backwards-compatibility.ts:36:27)
      at EthersProviderWrapper.send (/Users/egor/workspace/ariadne-v2-contracts/node_modules/@nomiclabs/hardhat-ethers/src/internal/ethers-provider-wrapper.ts:13:48)
      at EthersProviderWrapper.<anonymous> (/Users/egor/workspace/ariadne-v2-contracts/node_modules/@ethersproject/providers/src.ts/json-rpc-provider.ts:642:31)
      at step (/Users/egor/workspace/ariadne-v2-contracts/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:48:23)
      at Object.next (/Users/egor/workspace/ariadne-v2-contracts/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:29:53)
      at /Users/egor/workspace/ariadne-v2-contracts/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:23:71
}
>
```

**Comment by fvictorio** [comment]
Thank you for the detailed report @egorFiNE, I'll take a look.

**Comment by fvictorio** [comment]
This should work with `hardhat@2.11.1`. Please upgrade and let us know if the issue is still there.

**Comment by egorFiNE** [comment]
....aaaand it works. All my tests pass. 

Thank you for such a quick response time! Much love from Ukraine!
