### ISSUE TITLE
Forked network not compatible with Arbitrum Nitro upgrade

### ISSUE THREAD

**Issue by rellfy** [NomicFoundation/hardhat#3138]
If forking an Arbitrum Nitro network (like Arbitrum One, after block `23_000_000` as an overshoot approximate -- I don't know the exact upgrade block number) then hardhat throws the following error:

```
InternalError: Unknown transaction type 106
    at ForkBlockchain._processRemoteBlock (project_path/node_modules/hardhat/src/internal/hardhat-network/provider/fork/ForkBlockchain.ts:298:15)
    at ForkBlockchain._getBlockByNumber (project_path/node_modules/hardhat/src/internal/hardhat-network/provider/fork/ForkBlockchain.ts:242:17)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ForkBlockchain.getBlock (project_path/node_modules/hardhat/src/internal/hardhat-network/provider/fork/ForkBlockchain.ts:66:13)
    at async ForkBlockchain.getLatestBlock (project_path/node_modules/hardhat/src/internal/hardhat-network/provider/BlockchainBase.ts:61:19)
    at async Function.create (project_path/node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:196:31)
    at async HardhatNetworkProvider._init (project_path/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:251:28)
    at async HardhatNetworkProvider._send (project_path/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:192:5)
    at async HardhatNetworkProvider.request (project_path/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:118:18)
error Command failed with exit code 1.
```

Steps to reproduce:
1. Fork Arbitrum One, RPC https://arb1.arbitrum.io/rpc @ block 23_000_000
2. Make an ETH call

**Comment by rellfy** [comment]
Duplicate of #2995
