### ISSUE TITLE
How to support XinFin blockchain

### ISSUE THREAD

**Issue by gzliudan** [NomicFoundation/hardhat#3163]
The address prefix of XinFin blockchain is `xdc`, not `0x`. So the hardhat report below error when deploy contract:

```text
Error: invalid address (argument="address", value="xdc0000000000000000000000000000000000000000", code=INVALID_ARGUMENT, version=address/5.7.0)
    at Logger.makeError (<DIR>/node_modules/@ethersproject/logger/src.ts/index.ts:269:28)
    at Logger.throwError (<DIR>/node_modules/@ethersproject/logger/src.ts/index.ts:281:20)
    at Logger.throwArgumentError (<DIR>/node_modules/@ethersproject/logger/src.ts/index.ts:285:21)
    at getAddress (<DIR>/node_modules/@ethersproject/address/src.ts/index.ts:109:16)
    at Formatter.address (<DIR>/node_modules/@ethersproject/providers/src.ts/formatter.ts:234:26)
    at Object.miner (<DIR>/node_modules/@ethersproject/providers/src.ts/formatter.ts:465:20)
    at Function.Formatter.check (<DIR>/node_modules/@ethersproject/providers/src.ts/formatter.ts:450:42)
    at Formatter._block (<DIR>/node_modules/@ethersproject/providers/src.ts/formatter.ts:301:34)
    at Formatter.block (<DIR>/node_modules/@ethersproject/providers/src.ts/formatter.ts:307:21)
    at JsonRpcProvider.<anonymous> (<DIR>/node_modules/@ethersproject/providers/src.ts/base-provider.ts:1836:35) {
  reason: 'invalid address',
  code: 'INVALID_ARGUMENT',
  argument: 'address',
  value: 'xdc0000000000000000000000000000000000000000',
  checkKey: 'miner',
  checkValue: 'xdc0000000000000000000000000000000000000000'
}
error Command failed with exit code 1.
```

JSSONRPC request:
```shell
curl -X POST https://rpc.apothem.network/ -H "Content-Type: application/json" -d '{"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["0x0", false],"id":1}'
```

JSSONRPC response:
```json
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": {
    "difficulty": "0x1",
    "extraData": "0x00000000000000000000000000000000000000000000000000000000000000003ea0a3555f9b1de983572bff6444aeb1899ec58c4f7900282f3d371d585ab1361205b0940ab1789c942a5885a8844ee5587c8ac5e371fc39ffe618960000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
    "gasLimit": "0x47b760",
    "gasUsed": "0x0",
    "hash": "0xbdea512b4f12ff1135ec92c00dc047ffb93890c2ea1aa0eefe9b013d80640075",
    "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
    "miner": "xdc0000000000000000000000000000000000000000",
    "mixHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "nonce": "0x0000000000000000",
    "number": "0x0",
    "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "penalties": "0x",
    "receiptsRoot": "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
    "sha3Uncles": "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
    "size": "0x29d",
    "stateRoot": "0x8e3faa435358e7027e68989700c2edd281c87518f82c127e8523df46c41c160f",
    "timestamp": "0x5d02164f",
    "totalDifficulty": "0x1",
    "transactions": [],
    "transactionsRoot": "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
    "uncles": [],
    "validator": "0x",
    "validators": "0x"
  }
}
```

The miner is `xdc0000000000000000000000000000000000000000`, not `0x0000000000000000000000000000000000000000`.

**Comment by alcuadrado** [comment]
Hey! Thanks for opening this issue.

I'm afraid that'd be a huge change. It's not even us who are rejecting that address, but ethers.js instead. I'm sure that if ethers accepted it, other parts of the stack would also reject it.

If a new network wants to reuse the Ethereum tooling and/or be EVM-compatible they are welcome to do it, of course, but it's their job to make sure that they stay truly compatible. I believe some networks (e.g. harmony), have two address formats for this reason. 

I guess you should open this issue in a XinFin repository instead.
