### ISSUE TITLE
npx hardhat compile fails for solidity version 0.8.15 and hardhat 2.11.x on a linux ec2 instance

### ISSUE THREAD

**Issue by akhanubis** [NomicFoundation/hardhat#3188]
Steps to reproduce:

1. npm init
2. npm install --save-dev hardhat
3. use the following hardhat.config.js:
```
/** @type import('hardhat/config').HardhatUserConfig */
module.exports = {
  solidity: {
    compilers: [
      {
        version: "0.8.15",
        settings: {
          optimizer: {
            enabled: true,
            runs: 200000
          }
        }
      }
    ]
  },
  paths: {
    sources: "./contracts"
  },
};
```
4. create contracts/Token.sol with sample contract from docs: https://hardhat.org/tutorial/writing-and-compiling-contracts#writing-smart-contracts
5. npx hardhat compile
```
[ec2-user@ip-1-1-1-1 t]$ npx hardhat compile
Error: write EPIPE
    at afterWriteDispatched (node:internal/stream_base_commons:160:15)
    at writeGeneric (node:internal/stream_base_commons:151:3)
    at Socket._writeGeneric (node:net:795:11)
    at Socket._write (node:net:807:8)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at Socket.Writable.write (node:internal/streams/writable:334:10)
    at output (/home/ec2-user/t/node_modules/hardhat/src/internal/solidity/compiler/index.ts:82:24)
    at new Promise (<anonymous>)
    at NativeCompiler.compile (/home/ec2-user/t/node_modules/hardhat/src/internal/solidity/compiler/index.ts:66:34)
```

System is a default ec2 linux image (Amazon Linux 2 LTS Arm64 AMI 2.0.20210326.0 arm64 HVM gp2):

```
[ec2-user@ip-1-1-1-1 t]$ lscpu
Architecture:        aarch64
Byte Order:          Little Endian
CPU(s):              4
On-line CPU(s) list: 0-3
Thread(s) per core:  1
Core(s) per socket:  4
Socket(s):           1
NUMA node(s):        1
Model:               1
BogoMIPS:            243.75
L1d cache:           64K
L1i cache:           64K
L2 cache:            1024K
L3 cache:            32768K
NUMA node0 CPU(s):   0-3
Flags:               fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm lrcpc dcpop asimddp ssbs
[ec2-user@ip-1-1-1-1 t]$ cat /etc/os-release
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
```

Downgrading to 2.10.2 fixes the issue and compile works (2.11.1 and 2.11.0 also fail).

Let me know if you need any more information.

**Comment by alcuadrado** [comment]
Thanks for opening the issue! Can you run with --verbose using both versions and post the output here?

**Comment by alcuadrado** [comment]
Also, are you using an ephemeral vm? Or do you reuse it?

**Comment by akhanubis** [comment]
2.10.2
```
[ec2-user@ip-1-1-1-1 r]$ npx hardhat compile --verbose
  hardhat:core:config Loading Hardhat config from /home/ec2-user/r/hardhat.config.js +0ms
  hardhat:core:global-dir Looking up Client Id at /home/ec2-user/.local/share/hardhat-nodejs/analytics.json +0ms
  hardhat:core:global-dir Client Id found: dbe6045d-a305-4ad5-a26f-c4070e21ab4e +1ms
  hardhat:core:hre Creating HardhatRuntimeEnvironment +0ms
  hardhat:core:hre Running task compile +0ms
  hardhat:core:hre Running task compile:get-compilation-tasks +1ms
  hardhat:core:hre Running task compile:solidity +0ms
  hardhat:core:hre Running task compile:solidity:get-source-paths +1ms
  hardhat:core:hre Running task compile:solidity:get-source-names +19ms
  hardhat:core:hre Running task compile:solidity:get-dependency-graph +36ms
  hardhat:core:hre Running task compile:solidity:read-file +2ms
  hardhat:core:hre Running task compile:solidity:get-compilation-jobs +513ms
  hardhat:core:tasks:compile The dependency graph was divided in '1' connected components +0ms
  hardhat:core:hre Running task compile:solidity:get-compilation-job-for-file +1ms
  hardhat:core:compilation-job File '/home/ec2-user/r/contracts/Token.sol' will be compiled with version '0.8.15' +0ms
  hardhat:core:hre Running task compile:solidity:handle-compilation-jobs-failures +17ms
  hardhat:core:hre Running task compile:solidity:filter-compilation-jobs +1ms
  hardhat:core:tasks:compile '0' jobs were filtered out +18ms
  hardhat:core:hre Running task compile:solidity:merge-compilation-jobs +1ms
  hardhat:core:hre Running task compile:solidity:compile-jobs +0ms
  hardhat:core:tasks:compile Compiling 1 jobs +2ms
  hardhat:core:hre Running task compile:solidity:solc:get-build +1ms
  hardhat:core:hre Running task compile:solidity:log:download-compiler-start +4ms
  hardhat:core:tasks:compile Checking native solc binary +82ms
  hardhat:core:tasks:compile Native solc binary doesn't work, using solcjs instead +12ms
  hardhat:core:hre Running task compile:solidity:log:download-compiler-end +123ms
  hardhat:core:hre Running task compile:solidity:compile-job +2ms
  hardhat:core:tasks:compile Compiling job with version '0.8.15' +35ms
  hardhat:core:hre Running task compile:solidity:get-compiler-input +0ms
  hardhat:core:hre Running task compile:solidity:compile +0ms
  hardhat:core:hre Running task compile:solidity:solc:compile +0ms
  hardhat:core:hre Running task compile:solidity:solc:get-build +1ms
  hardhat:core:hre Running task compile:solidity:log:download-compiler-start +3ms
  hardhat:core:tasks:compile Checking native solc binary +69ms
  hardhat:core:tasks:compile Native solc binary doesn't work, using solcjs instead +40ms
  hardhat:core:hre Running task compile:solidity:log:download-compiler-end +164ms
  hardhat:core:hre Running task compile:solidity:log:run-compiler-start +0ms
  hardhat:core:hre Running task compile:solidity:solcjs:run +0ms
  hardhat:core:hre Running task compile:solidity:log:run-compiler-end +3s
  hardhat:core:hre Running task compile:solidity:check-errors +0ms
  hardhat:core:hre Running task compile:solidity:log:compilation-errors +0ms
  hardhat:core:hre Running task compile:solidity:emit-artifacts +0ms
  hardhat:core:tasks:compile Emitting artifacts for file 'contracts/Token.sol' +3s
  hardhat:core:tasks:compile Emitting artifact for contract 'Token' +0ms
  hardhat:core:hre Running task compile:solidity:get-artifact-from-compilation-output +14ms
  hardhat:core:hre Running task compile:solidity:log:compilation-result +14ms
Compiled 1 Solidity file successfully
  hardhat:core:hre Running task compile:remove-obsolete-artifacts +1ms
  hardhat:core:cli Killing Hardhat after successfully running task compile +0ms

```
2.11.2
```
[ec2-user@ip-1-1-1-1 t]$ npx hardhat compile --verbose
  hardhat:core:config Loading Hardhat config from /home/ec2-user/t/hardhat.config.js +0ms
  hardhat:core:global-dir Looking up Client Id at /home/ec2-user/.local/share/hardhat-nodejs/analytics.json +0ms
  hardhat:core:global-dir Client Id found: dbe6045d-a305-4ad5-a26f-c4070e21ab4e +0ms
  hardhat:core:hre Creating HardhatRuntimeEnvironment +0ms
  hardhat:core:hre Running task compile +1ms
  hardhat:core:hre Running task compile:get-compilation-tasks +0ms
  hardhat:core:hre Running task compile:solidity +0ms
  hardhat:core:hre Running task compile:solidity:get-source-paths +1ms
  hardhat:core:hre Running task compile:solidity:get-source-names +1ms
  hardhat:core:hre Running task compile:solidity:get-dependency-graph +1ms
  hardhat:core:hre Running task compile:solidity:read-file +2ms
  hardhat:core:hre Running task compile:solidity:get-compilation-jobs +10ms
  hardhat:core:tasks:compile The dependency graph was divided in '1' connected components +0ms
  hardhat:core:hre Running task compile:solidity:get-compilation-job-for-file +1ms
  hardhat:core:compilation-job File '/home/ec2-user/t/contracts/Token.sol' will be compiled with version '0.8.15' +0ms
  hardhat:core:hre Running task compile:solidity:handle-compilation-jobs-failures +2ms
  hardhat:core:hre Running task compile:solidity:filter-compilation-jobs +0ms
  hardhat:core:tasks:compile '0' jobs were filtered out +5ms
  hardhat:core:hre Running task compile:solidity:merge-compilation-jobs +4ms
  hardhat:core:hre Running task compile:solidity:compile-jobs +0ms
  hardhat:core:tasks:compile Compiling 1 jobs +2ms
  hardhat:core:hre Running task compile:solidity:compile-job +2ms
  hardhat:core:tasks:compile Compiling job with version '0.8.15' +1ms
  hardhat:core:hre Running task compile:solidity:get-compiler-input +0ms
  hardhat:core:hre Running task compile:solidity:compile +0ms
  hardhat:core:hre Running task compile:solidity:solc:compile +1ms
  hardhat:core:hre Running task compile:solidity:solc:get-build +0ms
  hardhat:core:hre Running task compile:solidity:log:run-compiler-start +3ms
  hardhat:core:hre Running task compile:solidity:solc:run +0ms
Error: write EPIPE
    at afterWriteDispatched (node:internal/stream_base_commons:160:15)
    at writeGeneric (node:internal/stream_base_commons:151:3)
    at Socket._writeGeneric (node:net:795:11)
    at Socket._write (node:net:807:8)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at Socket.Writable.write (node:internal/streams/writable:334:10)
    at output (/home/ec2-user/t/node_modules/hardhat/src/internal/solidity/compiler/index.ts:82:24)
    at new Promise (<anonymous>)
    at NativeCompiler.compile (/home/ec2-user/t/node_modules/hardhat/src/internal/solidity/compiler/index.ts:66:34)
```

So 2.10.2 doesnt use native compiler, uses solcjs.

VM is reused. It's a long living instance that periodically runs jobs.

**Comment by alcuadrado** [comment]
Thanks for the info. The problem is that we are incorrectly assuming that every Linux box is x86_64. 

`npx hardhat clean --global` should help you workaround this issue.

**Comment by akhanubis** [comment]
Ty, compile worked with 2.11.2 after running `npx hardhat clean --global`.
