### ISSUE TITLE
bug: cannot run hardhat coverage after upgrade to Hardhat 2.11.2

### ISSUE THREAD

**Issue by gabririgo** [NomicFoundation/hardhat#3202]
After upgrading project from hardhat v2.2.1 to v 2.11.2 and solidity-coverage from v.0.7.17 to 0.8.2 I receive the following error when running hardhat coverage:

`Unknown key "inliner"`

option `inliner` is not recognized as a valid `solcOptimizerDetails` param.
The project needs code optimization otherwise won't compile with hardhat.
in fact, while contracts compile with hardhat compile (uses optimizer in solidity settings), when running hardhat coverage the contract does not compile:
`CompilerError: Stack too deep when compiling inline assembly: Variable headStart is 1 slot(s) too deep inside the stack.
`
`
[Sample for replication](https://github.com/RigoBlock/v3-contracts/tree/build/upgrade-hardhat)

**Comment by gabririgo** [comment]
running command `hardhat test --verbose` returns an error:
`hardhat:core:hardhat-network:node Could not generate stack trace. Please report this to help us improve Hardhat.
  hardhat:core:hardhat-network:node  TypeError: Cannot use 'in' operator to search for 'pc' in undefined
    at isEvmStep (/home/gabriele/v3-contracts/node_modules/hardhat/src/internal/hardhat-network/stack-traces/message-trace.ts:88:14)
    at ErrorInferrer._isConstructorInvalidArgumentsError (/home/gabriele/v3-contracts/node_modules/hardhat/src/internal/hardhat-network/stack-traces/error-inferrer.ts:978:19)
    at ErrorInferrer.inferBeforeTracingCreateMessage (/home/gabriele/v3-contracts/node_modules/hardhat/src/internal/hardhat-network/stack-traces/error-inferrer.ts:139:14)
    at SolidityTracer._getCreateMessageStackTrace (/home/gabriele/v3-contracts/node_modules/hardhat/src/internal/hardhat-network/stack-traces/solidityTracer.ts:136:27)
    at SolidityTracer.getStackTrace (/home/gabriele/v3-contracts/node_modules/hardhat/src/internal/hardhat-network/stack-traces/solidityTracer.ts:50:19)
    at SolidityTracer._rawTraceEvmExecution (/home/gabriele/v3-contracts/node_modules/hardhat/src/internal/hardhat-network/stack-traces/solidityTracer.ts:211:38)
    at SolidityTracer._traceEvmExecution (/home/gabriele/v3-contracts/node_modules/hardhat/src/internal/hardhat-network/stack-traces/solidityTracer.ts:159:29)
    at SolidityTracer._getCallMessageStackTrace (/home/gabriele/v3-contracts/node_modules/hardhat/src/internal/hardhat-network/stack-traces/solidityTracer.ts:70:17)
    at SolidityTracer.getStackTrace (/home/gabriele/v3-contracts/node_modules/hardhat/src/internal/hardhat-network/stack-traces/solidityTracer.ts:54:19)
    at HardhatNode._manageErrors (/home/gabriele/v3-contracts/node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:1925:41)`

and process ends with 
`Failed to generate 1 stack trace. Run Hardhat with --verbose to learn more.`
` hardhat:core:cli Killing Hardhat after successfully running task test +0ms`

**Comment by fvictorio** [comment]
@gabririgo can you give me precise reproduction steps? I tried the repo you shared, but the config file seems to assume there are some environment variables set.

**Comment by gabririgo** [comment]
@fvictorio to run the repo, a file .env must be created and contain
`SOLIDITY_VERSION=""
SOLIDITY_SETTINGS="{"optimizer":{"enabled":true,"runs":1000}}"`
second line is requred, first line not required if solidity version specified in hardhat config file.

I will look into providing a working example, however, the way I see you can reproduce is by adding a config spec in any project that uses hardhat, i.e. in the .solcover.js file add following config:
`
configureYulOptimizer: true,
    solcOptimizerDetails: {
      peephole: false,
      inliner: false,
      jumpdestRemover: false,
      orderLiterals: true,
      deduplicate: false,
      cse: false,
      constantOptimizer: false,
      yul: false
    }
`

**Comment by fvictorio** [comment]
Thanks @gabririgo, I was able to reproduce it now. I believe this is something that belongs to the solidity-coverage repo, and I see that you've already opened [an issue](https://github.com/sc-forks/solidity-coverage/issues/752) there. I'm going to close this for the time being, but please let me know if there's something we can do on our side.

**Comment by gabririgo** [comment]
sure, I reverted to hardhat upgrade only, and it still fails with same error. I guess you are using a new version of solidity-coverage that has this issue. Please note also hardhat-deploy suffers from same bug, as in [this PR](https://github.com/RigoBlock/v3-contracts/pull/112) generated by dependabot version upgrades.
