### ISSUE TITLE
Executing functions on cloned contracts always fails with CALL_EXCEPTION 

### ISSUE THREAD

**Issue by itinance** [NomicFoundation/hardhat#3230]
### The Issue

I came across an issue which makes testing of Factories and Proxies impossible at the moment: 

calling a function of a contract address, which was created via `Clones.clone` from OpenZeppelins Minimal-Proxy-implementation reverts with CALL_EXECUTION when we attach the address onto a contract variable via `attach` or `getContractAt`.

Lets say we have a test, which 
1. creates a Sample Contract `Box`
2. create a `Factory`-Contract and tells it the address of `Box`, which can be cloned within the Factory
3. executes the `clone`-method of the Factory to receive a cloned `Box`-instance
4. grabs the deployed address of this clone from the list of emitted events
5. executes a normal function on this clone

What happens is, that every function call to the newly created `Box`-instance will cause an `CALL_EXCEPTION` revert, when we use tests via hardhat.  This is NOT happening when we deploy on Rinkeby, Görli or Mumbai.

My issue sounds like #2658, but we do not work across several nodes and script-executions here. We just stay within the same execution instance and the revert still happens.

### Steps to reproduce

I created a runs-out-of-the-box example which can be checked here: https://github.com/itinance/study-factory-proxy and includes all the necessary steps, that I describe below.

I have a Box-Contract and a Factory-Contract:
1. Box: 

```
contract BoxV1 is Initializable {

    uint public width;
    uint public length;

    function initialize(uint _length, uint _width) public initializer {
        length = _length;
        width = _width;
    }

    function area() public view returns(uint) {
        return length * width;
    }
}
```

3. Factory: 
```
pragma solidity ^0.8.9;

import "@openzeppelin/contracts-upgradeable/proxy/utils/Initializable.sol";
import "@openzeppelin/contracts/proxy/Clones.sol";

import "./BoxV1.sol";

contract BoxFactory is Initializable {
    event BoxDeployed(address instance);

    address private _impl;

    function initialize(address impl_) public initializer {
        _impl = impl_;
    }

    function impl() public view returns(address) {
        return _impl;
    }

    function createBox(uint _length, uint _width) public returns (address)
    {
        address clone = Clones.clone(_impl);
        BoxV1(clone).initialize(_length, _width);

        emit BoxDeployed(address(clone));

        return clone;
    }
}
```

In tests, I load Fixtures for the Box and the factory:

```
  async function deployFactory() {
    const boxV1Factory = (await ethers.getContractFactory('BoxV1')) as BoxV1__factory;
    const boxV1 = await upgrades.deployProxy(boxV1Factory, [0, 0])
    await boxV1.deployed();

    const boxFactoryFactory = (await ethers.getContractFactory('BoxFactory')) as BoxFactory__factory;

    const boxFactory = (await upgrades.deployProxy(boxFactoryFactory, [boxV1.address])) as BoxFactory;
    await boxFactory.deployed();

    console.log(1, boxFactory.address);

    return { boxFactory };
  }

  async function cloneMeABox_5x6() {
    const {boxFactory} = await loadFixture(deployFactory);

    const tokenTransaction: ContractTransaction = await boxFactory.createBox(5, 6 );
    const receipt: ContractReceipt = await tokenTransaction.wait();
    const boxAddress = findEventArgsByNameFromReceipt(receipt, 'BoxDeployed', 'instance');

    expect(boxAddress).to.be.properAddress;

    const contractFactory = (await ethers.getContractFactory('BoxV1')) as BoxV1__factory;
    const box = contractFactory.attach(boxAddress);

    // this is actually the same, leading to the same error
    //const box = await ethers.getContractAt('BoxV1', boxAddress)

    return {box};
  }
```

The actual failing test:

```
      const {box} = await loadFixture(cloneMeABox_5x6);
      expect(await box.area()).to.eq(5*6);
```

When accessing `box.area`, it reverts with:

>  Error: call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="area()", data="0x", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)
>       at Logger.makeError (node_modules/@ethersproject/logger/src.ts/index.ts:269:28)
>       at Logger.throwError (node_modules/@ethersproject/logger/src.ts/index.ts:281:20)
> 

This doesn't fail in "real life" with deployment on testnets like Görli and Rinkeby. It only fails with using hardhat and running tests within hardhat.

I tried to figure out, what happens here but I am lost. Has somebody faced this issue and can tell something about?
Thanks a lot!

**Comment by fvictorio** [comment]
Does this still happen if you change this line:

```
  async function cloneMeABox_5x6() {
    const {boxFactory} = await deployFactory();
```

(Notice I removed the `loadFixture` call)

In general, `loadFixture` calls shouldn't be nested. A fixture can call another fixture, but it shouldn't use it with `loadFixture`. In fact, this should've caused an error, I'm not sure why it didn't happen.

**Comment by itinance** [comment]
Thanks for mentioning that fixtures should not call `loadFixture` itself when resolving dependencies amongst them!

I remove it accordingly, but the issue still persists.

**Comment by fvictorio** [comment]
Ok, I know what's going on here.

When you do this:

```ts
const boxFactory = (await upgrades.deployProxy(boxFactoryFactory, [boxV1.address])) as BoxFactory;
```

`boxV1.address` is the address of the upgradable proxy, not of the box implementation. If you want to use the box implementation, you can do this:

```ts
import { getImplementationAddress } from '@openzeppelin/upgrades-core';

// ...

const implAddress = await getImplementationAddress(ethers.provider, boxV1.address);
const boxFactory = (await upgrades.deployProxy(boxFactoryFactory, [implAddress])) as BoxFactory;
```

Of course, if you then upgrade the contract, the ones created by the factory won't get upgraded (because you are using the implementation directly). I'm not sure how you would accomplish that tbh.

**Comment by fvictorio** [comment]
I'm curious about this though:

> This doesn't fail in "real life" with deployment on testnets like Görli and Rinkeby. It only fails with using hardhat and running tests within hardhat.

You should get the same problem in live networks too :confused:

**Comment by itinance** [comment]
@fvictorio Thank you very much! This explains and solves everything!

```
import { getImplementationAddress } from '@openzeppelin/upgrades-core';

// ...

const implAddress = await getImplementationAddress(ethers.provider, boxV1.address);
const boxFactory = (await upgrades.deployProxy(boxFactoryFactory, [implAddress])) as BoxFactory;
```

**Comment by fvictorio** [comment]
Glad to hear that! I'm going to close this issue then.
