### ISSUE TITLE
CALL_EXCEPTION stops running node

### ISSUE THREAD

**Issue by aliveli186** [NomicFoundation/hardhat#3245]
A call to a contract results in running node to stop.
hardhat v2.11.2:

Last message from node:
```
eth_call

  If you think this is a bug in Hardhat, please report it here: https://hardhat.org/report-bug

Mined empty block #15682283 with base fee 47143756
Y:\Blockchain\weeb-finance-solidity\node_modules\hardhat\internal\hardhat-network\stack-traces\solidity-errors.js:111
    return new SolidityCallSite(sourceReference.sourceName, sourceReference.contract, sourceReference.function !== undefined
                                                ^

TypeError: Cannot read properties of undefined (reading 'sourceName')
(Use `node --trace-uncaught ...` to show where the exception was thrown)
```

Script error:
```
Error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0xf39Fd6e
51aad88F6F4ce6aB8827279cffFb92266","to":"0x00CAC06Dd0BB4103f8b62D280fE9BCEE8f26fD59","data":"0x759eee10000000000000000000000000f95fa88bb0d0937100982061f4bb2cea7caf37eb0000000000000000000000006
87d9755aef27f19cf70b7df9c40d76464852271","accessList":null}, error={"errno":-4077,"code":"ECONNRESET","syscall":"read"}, code=CALL_EXCEPTION, version=providers/5.7.1)
    at Logger.makeError (C:\my-solidity\node_modules\@ethersproject\logger\src.ts\index.ts:269:28)
    at Logger.throwError (C:\my-solidity\node_modules\@ethersproject\logger\src.ts\index.ts:281:20)
    at checkError (C:\my-solidity\node_modules\@ethersproject\providers\src.ts\json-rpc-provider.ts:66:16)
    at EthersProviderWrapper.<anonymous> (C:\my-solidity\node_modules\@ethersproject\providers\src.ts\json-rpc-provider.ts:642:20)
    at step (C:\my-solidity\node_modules\@ethersproject\providers\lib\json-rpc-provider.js:48:23)
    at Object.throw (C:\my-solidity\node_modules\@ethersproject\providers\lib\json-rpc-provider.js:29:53)
    at rejected (C:\my-solidity\node_modules\@ethersproject\providers\lib\json-rpc-provider.js:21:65) {
  reason: 'missing revert data in call exception; Transaction reverted without a reason string',
  code: 'CALL_EXCEPTION',
  data: '0x',
  transaction: {
    from: '0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266',
    to: '0x00CAC06Dd0BB4103f8b62D280fE9BCEE8f26fD59',
    data: '0x759eee10000000000000000000000000f95fa88bb0d0937100982061f4bb2cea7caf37eb000000000000000000000000687d9755aef27f19cf70b7df9c40d76464852271',
    accessList: null
  },
  error: Error: read ECONNRESET
      at TCP.onStreamRead (node:internal/stream_base_commons:217:20) {
    errno: -4077,
    code: 'ECONNRESET',
    syscall: 'read'
  }
}
```

**Comment by aliveli186** [comment]
> Ugh, I think this is related to viaIR. Do you have `viaIR` enabled in your solc config?

Yes it is enabled.
`viaIR: true`

**Comment by fvictorio** [comment]
Thanks. We are going to release a (beta) version that works with viaIR soon.
