### ISSUE TITLE
Error while forking Avalanche C-Chain

### ISSUE THREAD

**Issue by 0xHyoga** [NomicFoundation/hardhat#3256]
As of recently I keep getting this error when forking the Avalanche C-Chain and interacting with any contract. I follow the same steps and it works with every other chain.

1. `npx hardhat node --fork https://api.avax.network/ext/bc/C/rpc`
2. `hh console` in another terminal

Then in the console i create an instance of say the DAI contract for example but then I keep getting this error on any simple call:

```
Error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266","to":"0xd586E7F844cEa2F87f50152665BCbc2C279D8d70","data":"0x06fdde03","accessList":null}, error={"name":"ProviderError","_stack":"ProviderError: HttpProviderError\n    at HttpProvider.request (/home/sorrowlol/project-cygnus/node_modules/hardhat/src/internal/core/providers/http.ts:78:19)\n    at AutomaticSenderProvider.request (/home/sorrowlol/project-cygnus/node_modules/hardhat/src/internal/core/providers/accounts.ts:341:34)\n    at AutomaticGasProvider.request (/home/sorrowlol/project-cygnus/node_modules/hardhat/src/internal/core/providers/gas-providers.ts:135:34)\n    at AutomaticGasPriceProvider.request (/home/sorrowlol/project-cygnus/node_modules/hardhat/src/internal/core/providers/gas-providers.ts:153:36)\n    at ChainIdValidatorProvider.request (/home/sorrowlol/project-cygnus/node_modules/hardhat/src/internal/core/providers/chainId.ts:66:34)\n    at BackwardsCompatibilityProviderAdapter.send (/home/sorrowlol/project-cygnus/node_modules/hardhat/src/internal/core/providers/backwards-compatibility.ts:36:27)\n    at EthersProviderWrapper.send (/home/sorrowlol/project-cygnus/node_modules/@nomiclabs/hardhat-ethers/src/internal/ethers-provider-wrapper.ts:13:48)\n    at EthersProviderWrapper.<anonymous> (/home/sorrowlol/project-cygnus/node_modules/@ethersproject/providers/src.ts/json-rpc-provider.ts:601:31)\n    at step (/home/sorrowlol/project-cygnus/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:48:23)\n    at Object.next (/home/sorrowlol/project-cygnus/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:29:53)","code":-32603,"_isProviderError":true,"data":{"message":"Error: invalid amount of extra data (block header number=20777364 hash=0x38347301c4ff099d9031e96b4c33a66d2e1f59a8169e184992050a8242fc995f hf=arrowGlacier baseFeePerGas=25000000000)"}}, code=CALL_EXCEPTION, version=providers/5.6.8)
    at step (/home/sorrowlol/project-cygnus/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:48:23)
    at EthersProviderWrapper.<anonymous> (/home/sorrowlol/project-cygnus/node_modules/@ethersproject/providers/src.ts/json-rpc-provider.ts:603:20)
    at checkError (/home/sorrowlol/project-cygnus/node_modules/@ethersproject/providers/src.ts/json-rpc-provider.ts:66:16)
    at Logger.throwError (/home/sorrowlol/project-cygnus/node_modules/@ethersproject/logger/src.ts/index.ts:273:20)
    at Logger.makeError (/home/sorrowlol/project-cygnus/node_modules/@ethersproject/logger/src.ts/index.ts:261:28) {
  reason: 'missing revert data in call exception; Transaction reverted without a reason string',
  code: 'CALL_EXCEPTION',
  data: '0x',
  transaction: {
    from: '0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266',
    to: '0xd586E7F844cEa2F87f50152665BCbc2C279D8d70',
    data: '0x06fdde03',
    accessList: null
  },
  error: ProviderError: HttpProviderError
```

If i do the exact same process with Fantom it works fine. Any ideas what is happening?

**Comment by fvictorio** [comment]
@0xHyoga I can't reproduce this. We fixed a similar issue recently, are you sure you are using the latest version of Hardhat?

**Comment by 0xHyoga** [comment]
Hi @fvictorio I was using hardhat v2.11.0. I just upgraded to v2.11.2 and it seemed to fix the issue. Thank you!

**Comment by fvictorio** [comment]
Glad to hear that!
