### ISSUE TITLE
Hardhat is unable to extract stacktrace if tx reverts inside await(expect contract.f())

### ISSUE THREAD

**Issue by hiroshi-yamamoto-dublr** [NomicFoundation/hardhat#3273]
Code:

```solidity
// SPDX-License-Identifier: MIT
pragma solidity 0.8.17;

contract Test {
  bool private flag = true;
  
  modifier someModifier() {
    require(flag, "Failed in modifier");
    _;
  }

  function f() external someModifier {
    require(false, "Can't call this method");
  }
}
```

I disabled the optimizer, due to #2755, and wrote some test code, where I instantiate the `Test` contract as `contract`.

If I call the code using `await contract.f()`, I correctly get:

```
     Error: VM Exception while processing transaction: reverted with reason string 'Can't call this method'
      at Test.f (contracts/Test.sol:13)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at runNextTicks (node:internal/process/task_queues:65:3)
      at listOnTimeout (node:internal/timers:528:9)
      at processTimers (node:internal/timers:502:7)
      at async HardhatNode._mineBlockWithPendingTxs (node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:1805:23)
      at async HardhatNode.mineBlock (node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:494:16)
      at async EthModule._sendTransactionAndReturnHash (node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:1522:18)
```

However, if I call the code using `await expect(contract.f()).to.be.revertedWith("Some wrong revert message")`, then I don't see the `Test.f` frame in the stacktrace:

```
     AssertionError: Expected transaction to be reverted with reason 'Wrong revert message', but it reverted with reason 'Can't call this method'
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at runNextTicks (node:internal/process/task_queues:65:3)
      at listOnTimeout (node:internal/timers:528:9)
      at processTimers (node:internal/timers:502:7)
      at async Context.<anonymous> (test/index.js:30:5)
```

This renders the stacktrace useless in the latter case.

**Comment by fvictorio** [comment]
This is interesting, thanks for reporting it. I'm not sure what's the best solution here, maybe we can include the original error as a parent error of the revert. It's not super straightforward though.

**Comment by olehmisar** [comment]
Are you using ethereum-waffle or hardhat-chai-matchers? I had the same issue with ethereum-waffle.

**Comment by fvictorio** [comment]
Blocked by #3463.
