### ISSUE TITLE
Error HH603: Hardhat flatten doesn't support cyclic dependencies.

### ISSUE THREAD

**Issue by youngqqcn** [NomicFoundation/hardhat#3277]
```
 npx hardhat flatten ./contracts/qyregistrar/QYRegistrarController.sol  --show-stack-traces
Error HH603: Hardhat flatten doesn't support cyclic dependencies.

HardhatError: HH603: Hardhat flatten doesn't support cyclic dependencies.
    at getSortedFiles (/data/qiyichain/qns-contracts/node_modules/hardhat/src/builtin-tasks/flatten.ts:47:15)
    at SimpleTaskDefinition.action (/data/qiyichain/qns-contracts/node_modules/hardhat/src/builtin-tasks/flatten.ts:84:25)
    at async Environment._runTaskDefinition (/data/qiyichain/qns-contracts/node_modules/hardhat/src/internal/core/runtime-environment.ts:219:14)
    at async Environment.run (/data/qiyichain/qns-contracts/node_modules/hardhat/src/internal/core/runtime-environment.ts:131:14)
    at async SimpleTaskDefinition.action (/data/qiyichain/qns-contracts/node_modules/hardhat/src/builtin-tasks/flatten.ts:125:17)
    at async Environment._runTaskDefinition (/data/qiyichain/qns-contracts/node_modules/hardhat/src/internal/core/runtime-environment.ts:219:14)
    at async Environment.run (/data/qiyichain/qns-contracts/node_modules/hardhat/src/internal/core/runtime-environment.ts:131:14)
    at async main (/data/qiyichain/qns-contracts/node_modules/hardhat/src/internal/cli/cli.ts:218:5)

```

**Comment by fvictorio** [comment]
Duplicate of https://github.com/NomicFoundation/hardhat/issues/1486
