### ISSUE TITLE
I have to install both `ethereum-waffle` and `@nomicfoundation/hardhat-chai-matchers`

### ISSUE THREAD

**Issue by islishude** [NomicFoundation/hardhat#3335]
I'm using yarn v3 and nodejs 18.

ethereum-waffle is an peer package in @nomicfoundation/hardhat-chai-matchers package.

If I uninstall ethereum-waffle, i will get a module not found error.

```
An unexpected error occurred:

Require stack:
- /app/uniswapv2-solc0.8/node_modules/@nomiclabs/hardhat-waffle/dist/src/deploy.js
- /app/uniswapv2-solc0.8/node_modules/@nomiclabs/hardhat-waffle/dist/src/index.js
- /app/uniswapv2-solc0.8/hardhat.config.ts
- /app/uniswapv2-solc0.8/node_modules/hardhat/internal/core/config/config-loading.js
- /app/uniswapv2-solc0.8/node_modules/hardhat/internal/cli/cli.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (/app/uniswapv2-solc0.8/node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
    at Function.resolve (node:internal/modules/cjs/helpers:109:19)
    at getDeployMockContract (/app/uniswapv2-solc0.8/node_modules/@nomiclabs/hardhat-waffle/src/deploy.ts:7:30)
    at /app/uniswapv2-solc0.8/node_modules/@nomiclabs/hardhat-waffle/src/index.ts:25:48
    at getRealTarget (/app/uniswapv2-solc0.8/node_modules/hardhat/src/internal/util/lazy.ts:112:22)
    at Object.get (/app/uniswapv2-solc0.8/node_modules/hardhat/src/internal/util/lazy.ts:185:26)
    at Suite.<anonymous> (/app/uniswapv2-solc0.8/src/test/UniswapV2ERC20.spec.ts:11:30)
    at Object.create (/app/uniswapv2-solc0.8/node_modules/hardhat/node_modules/mocha/lib/interfaces/common.js:148:19)
    at context.describe.context.context (/app/uniswapv2-solc0.8/node_modules/hardhat/node_modules/mocha/lib/interfaces/bdd.js:42:27) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/app/uniswapv2-solc0.8/node_modules/@nomiclabs/hardhat-waffle/dist/src/deploy.js',
    '/app/uniswapv2-solc0.8/node_modules/@nomiclabs/hardhat-waffle/dist/src/index.js',
    '/app/uniswapv2-solc0.8/hardhat.config.ts',
    '/app/uniswapv2-solc0.8/node_modules/hardhat/internal/core/config/config-loading.js',
    '/app/uniswapv2-solc0.8/node_modules/hardhat/internal/cli/cli.js'
  ]
}
```

**Comment by islishude** [comment]
I'm using yarn v3, it works for npm, because npm installs peer packages.

My hardhat.config.ts

```
import { HardhatUserConfig } from "hardhat/config";

import "@nomicfoundation/hardhat-toolbox";

// if I remove this, I will get an error: TypeError: Cannot read properties of undefined (reading 'createFixtureLoader')
import "@nomiclabs/hardhat-waffle";
```

yarn doesn't install peer packages, and `@nomicfoundation/hardhat-chai-matchers` has a peer package `ethereum-waffle`, so I have to install the peer package manually.

If i install `ethereum-waffle`, I will get a warning.

```
You have both ethereum-waffle and @nomicfoundation/hardhat-chai-matchers installed. They don't work correctly together, so please make sure you only use one.

We recommend you migrate to @nomicfoundation/hardhat-chai-matchers. Learn how to do it here: https://hardhat.org/migrate-from-waffle
```

**Comment by alcuadrado** [comment]
I see! You should migrate to our fixture loader instead. Take a look at this: https://hardhat.org/hardhat-network-helpers/docs/reference#fixtures

Also, we are working with waffle on making it more compatible with our chai matchers.
