### ISSUE TITLE
Support for ESM in TypeScript projects

### ISSUE THREAD

**Issue by fvictorio** [NomicFoundation/hardhat#3385]
Please comment and/or upvote this issue if you need support for ESM in TypeScript projects. If possible, tell us more about your use case and why you need this and cannot just transpile to cjs.

**Comment by DenisGorbachev** [comment]
I'm using https://github.com/sindresorhus/execa, which is ESM-only.

**Comment by anteqkois** [comment]
I can't run task when use new TypeScript:
```
"module": "NodeNext",
"moduleResolution": "NodeNext",
```
Obviously when i delete `"type": "module"` from package.json it's start work, but i must use this setting.

Error from terimnal:
![image](https://user-images.githubusercontent.com/73034007/210961492-af6a1a9c-a7dc-4252-bdad-b3fa73a25816.png)

**Comment by talentlessguy** [comment]
Suggestion for TS ESM implementation:

ts-node has a `ts-node/esm` loader hook. Also `mts` extension could be used but I'm not sure if that's needed.

**Comment by paulmillr** [comment]
Copying @alcuadrado comments from monorepo:

> Nop, unfortunately Hardhat's core depends on CJS pretty heavily.

> The reason for that is that our plugin system is dependent on the order of require() that users make to plugins. In ESM the order of imports is not guaranteed (and does change in practice).

What about `await import`? You can do this one after another.

> We need to rework our plugin system for it to fully support ESM.

> I'm starting to think that maybe we should move to esm-only when it's properly supported by ts-node or some similar project. But note that even after that, the migration would be a pretty large project, as every plugin will need to be adapted.

If you keep supporting two module systems, ESM modules would be able to import common.js code - which uses old sequential `require`s and is cool.

**Comment by alcuadrado** [comment]
> What about await import? You can do this one after another.

Oh, that may be a great idea actually! I think now ESM in node.js means/implies that you have top-level-await. This could work! Thanks !

**Comment by pynixwang** [comment]
pure esm package is coming.

**Comment by thevolcanomanishere** [comment]
I am looking to integrate Playwright with Hardhat + Wagmi in order to automate frontend testing that involves connecting to a hardhat node :)

**Comment by kostysh** [comment]
Upvote; we are using ESM in our TypeScript project

**Comment by lukaracki** [comment]
> pure esm package is coming.

do u know when? 🧐

**Comment by robwilkes** [comment]
upvote, many packages are ESM only now, I have to install older versions for compatibility. all my projects and code is ESM now, except for hardhat.

**Comment by CJ42** [comment]
Upvoting as well. We have `constants` values defined in a [`constants.ts` / constants.js`](https://github.com/lukso-network/lsp-smart-contracts/blob/develop/constants.ts) file in the LUKSO lsp-smart-contracts. These are part of the [`@lukso/lsp-smart-contracts` npm package](https://www.npmjs.com/package/@lukso/lsp-smart-contracts) and are important values to be consumed by projects that use our smart contracts package.

https://github.com/lukso-network/lsp-smart-contracts

In our case, this is problematic as any Hardhat Typescript project that has the `@lukso/lsp-smart-contracts` as a dependency cannot import these necessary constant values.

The only workaround we found was in this PR by @richtera in this PR: https://github.com/lukso-network/lsp-smart-contracts/pull/601.

<img width="464" alt="image" src="https://github.com/NomicFoundation/hardhat/assets/31145285/11527a7f-186a-447f-bc43-34ec66479304">

https://github.com/lukso-network/lsp-smart-contracts/pull/601/files

The file in the folder looks like this:

<img width="204" alt="image" src="https://github.com/NomicFoundation/hardhat/assets/31145285/37a049b8-873e-420c-a7e1-e29e33143931">

ES Lint raises a warning, but we are still able to import as shown below.

```js
import { INTERFACE_IDS } from "@lukso/lsp-smart-contracts/dist/constants.cjs.js";

const test = INTERFACE_IDS.LSP0ERC725Account;
```

**Comment by vinerz** [comment]
Following this issue. Would help a lot to get rid of some workarounds for ESM/CJS interop.

**Comment by fraVlaca** [comment]
yes pls really need esm compatibility with typescript, make it happen guys

**Comment by paulperegud** [comment]
Having to choose dependencies basing on "does it still support CommonJS" criterion is annoying. Following this issue.

**Comment by DefiCake** [comment]
Another upvote for this feature. Aztec 's ZK framework, Noir, needs ESM for the generation of proofs.

https://noir-lang.org/typescript

**Comment by fvictorio** [comment]
Thanks everyone. We'll try to prioritize this. I don't think we'll be able to do it properly before the next major, but we'll try to at least provide a useful workaround, even if it has some friction.

**Comment by timbrinded** [comment]
ts-node can be axed entirely with a drop-in replacement for [tsx](https://github.com/esbuild-kit/tsx).

This should unblock you entirely from allowing ESM TS support for HardHat

**Comment by developerasun** [comment]
Upvoted. I'm using hardhat-ts in workplace for Optimism L2 smart contract, dealing with batch transactions. 

And [fee estimate package](https://github.com/ethereum-optimism/optimism/tree/develop/packages/fee-estimation) provided by optimism is based on ts ESM and [hardhat is not yet support it](https://hardhat.org/hardhat-runner/docs/advanced/using-esm#esm-and-typescript-projects). 

so I  had to dynamic import it like below.

```ts
async function feeEstimator() {
  const sdk = await import("@eth-optimism/fee-estimation")
  const { what-you-need } = sdk
}
```

**Comment by MOZGIII** [comment]
I have found the following solution:

1. Import the real code via dynamic imports: `const { load } = await import("lp-staking-research/load");`
2. Import types via the type imports with import annotation like this: `import type { TestCase } from "lp-staking-research/schema/test-case" assert { "resolution-mode": "require" };`

These will also require using `"module": "NodeNext"` and `"moduleResolution": "NodeNext"` at `tsconfig.json`, and, for now, nightly TypeScript (`yarn install --dev typescript@next`).

**Comment by niconiahi** [comment]
I need this. I'm letting you know. The future is here already

**Comment by niconiahi** [comment]
I need that sweet pure ESM

**Comment by rhlsthrm** [comment]
Tried a barebones `bun` setup for a new Hardhat project and ran into an error with ESM.

**Comment by damianobarbati** [comment]
@schaable can `hardhat` just migrate to <https://www.npmjs.com/package/tsx> package? It runs without any problems with ESM, it was built to be ESM first.

**Comment by Confucian-e** [comment]
hoping to support bun which uses ESM in typescript

**Comment by jmrossy** [comment]
The Hyperlane team is hoping for this fix too! We compile our TS to ESM for better tree shaking.

**Comment by schaable** [comment]
Hi everyone, we just released a new version of Hardhat which has **experimental support for TypeScript + ESM projects**. To try it out, upgrade your version of Hardhat and follow these steps.

# Initial Setup

1. Modify `package.json`
    - Add `"type": "module"` to your `package.json`. This indicates that the project uses ESM syntax.
2. Rename Hardhat configuration file
    - Change `hardhat.config.ts` to `hardhat.config.cts`. The `.cts` extension is necessary as the Hardhat config can only be CommonJS.

# TypeScript Configuration

1. Update `tsconfig.json`
    - Under `compilerOptions`, set `"module": "node16"`, `"target": "es2022"`, and `"esModuleInterop": true`. These options ensure compatibility with Node.js v16 and above.
    - Add `experimentalResolver: true` under the `ts-node` configuration. This setting enables file extension inclusion in CommonJS, and can help suppressing some IDE errors.
    - If you’re using `files`, `include` or `exclude` in your config, you may need to add `files: true` the `ts-node` configuration to avoid certain type checking errors.

```
{
  "compilerOptions": {
    "module": "node16",
    "target": "es2022",
    "esModuleInterop": true
    // ...
  },
  "ts-node": {
    "experimentalResolver": true
    "files": true // only if you have "files", "include" or "exclude" in your config
  }
}
```

# Code Adjustments

To make your Hardhat project compatible with ESM, you'll need to make the following adjustments to your code:

1. Update relative imports
    - Include the file extension in all your relative import statements. This is a requirement in ESM to correctly resolve modules.
2. Specify full path for Directory Modules
    - Replace any directory module imports with the full file path. For instance, instead of importing from a directory like `./utils`, specify the exact file: `./utils/index.js`.
3. Handling Hardhat imports
    - As Hardhat is still based on CommonJS, you cannot use named imports directly due to the module system difference. Instead:
        - Import the entire module as a default import: `import hre from 'hardhat';`
        - Use destructuring to access specific properties: `const { ethers, network } = hre;`

## Plugins and types

Plugins such as `hardhat-ethers` and `hardhat-viem` automatically generate TypeScript typings for contracts during compilation. These files, despite having `.ts` extensions, should be treated as CommonJS modules. However, due to the root `package.json` specifying `"type": "module"`, they are incorrectly interpreted as ESM modules. This leads to issues in IDEs with type checking and autocomplete features.

To resolve this, add a `package.json` file with `"type": "commonjs"` in the folder where these files are generated (`./typechain-types` for `hardhat-ethers` and `./artifacts` for `hardhat-viem`). To streamline this process, we provide snippets with overrides of the compilation task which you can include in your `hardhat.config.cts`. These tasks automatically create the necessary `package.json` file during the compilation process.

### hardhat-viem

If you’re using `hardhat-viem`, add the following snippet after the `import`s in your `hardhat-config.cts`

```
import { join } from "path";
import { writeFile } from "fs/promises";
import { subtask } from "hardhat/config";
import { TASK_COMPILE_SOLIDITY } from "hardhat/builtin-tasks/task-names";

subtask(TASK_COMPILE_SOLIDITY).setAction(async (_, { config }, runSuper) => {
  const superRes = await runSuper();

  try {
    await writeFile(
      join(config.paths.artifacts, "package.json"),
      '{ "type": "commonjs" }'
    );
  } catch (error) {
    console.error("Error writing package.json: ", error);
  }

  return superRes;
});
```

### hardhat-ethers

If you’re using hardhat-ethers, add the following snippet after the `import`s in your `hardhat-config.cts`

```
import { join } from "path";
import { writeFile } from "fs/promises";
import { subtask } from "hardhat/config";
import { TASK_COMPILE_SOLIDITY } from "hardhat/builtin-tasks/task-names";

subtask(TASK_COMPILE_SOLIDITY).setAction(async (_, { config }, runSuper) => {
  const superRes = await runSuper();

  try {
    await writeFile(
      join(config.paths.root, "typechain-types", "package.json"),
      '{ "type": "commonjs" }'
    );
  } catch (error) {
    console.error("Error writing package.json: ", error);
  }

  return superRes;
});
```

# Running Scripts and Tests

- Run scripts with:
`NODE_OPTIONS="--experimental-loader ts-node/esm/transpile-only" hh run scripts/deploy.ts`
- Execute tests using:
`NODE_OPTIONS="--experimental-loader ts-node/esm/transpile-only" hh test`
- To avoid experimental feature warnings, append `--no-warnings=ExperimentalWarning` to your `NODE_OPTIONS`
- You can integrate these commands into your project's `package.json` for easy execution:

```
"scripts": {
  "test": "NODE_OPTIONS='--experimental-loader ts-node/esm/transpile-only --no-warnings=ExperimentalWarning' hardhat test",
  "script": "NODE_OPTIONS='--experimental-loader ts-node/esm/transpile-only --no-warnings=ExperimentalWarning' hardhat run"
}
```

**Comment by signorecello** [comment]
Thanks @schaable this works perfectly! Finally dumping CJS in Aztec's Noir stuff!

**Comment by pcaversaccio** [comment]
Happy New Year everyone! I just realised that `chai` [`v5.0.0`](https://github.com/chaijs/chai/releases/tag/v5.0.0) got released 4 days ago with an important breaking change:
> Chai now only supports EcmaScript Modules (ESM).

This means, if you use TypeScript _and_ `chai` for (unit) tests in Hardhat, and don't want to use the experimental version, you're blocked from upgrading `chai`. A perfect example would be my known [Hardhat template](https://github.com/pcaversaccio/hardhat-project-template-ts). I don't know about the internal roadmap but given this release, I think it would be worth to consider providing a more prod-ready, and migration-friendly version over the next weeks?

**Comment by CryptoGraffe** [comment]
Trying this out... I get this error:

```
❯ HARDHAT_VERBOSE=true npx hardhat
  hardhat:core:vars:varsManager Creating a new instance of VarsManager +0ms
  hardhat:core:vars:varsManager Loading ENV variables if any +1ms
  hardhat:core:config Loading Hardhat config from /Users/x/dev/yz/hardhat/hardhat.config.cts +0ms
An unexpected error occurred:

/
/Users/x/dev/yz/hardhat/hardhat.config.cts:3
import { BigNumber } from 'ethers';
^^^^^^

SyntaxError: Cannot use import statement outside a module
```

> @schaable can `hardhat` just migrate to https://www.npmjs.com/package/tsx package? It runs without any problems with ESM, it was built to be ESM first.

Hard agree this is what we use for everything else

**Comment by CryptoGraffe** [comment]
Also tried with args:

```
❯ NODE_OPTIONS='--experimental-loader ts-node/esm/transpile-only' HARDHAT_VERBOSE=true npx hardhat
(node:76579) ExperimentalWarning: `--experimental-loader` may be removed in the future; instead use `register()`:
--import 'data:text/javascript,import { register } from "node:module"; import { pathToFileURL } from "node:url"; register("ts-node/esm/transpile-only", pathToFileURL("./"));'
(Use `node --trace-warnings ...` to show where the warning was created)
(node:76598) ExperimentalWarning: `--experimental-loader` may be removed in the future; instead use `register()`:
--import 'data:text/javascript,import { register } from "node:module"; import { pathToFileURL } from "node:url"; register("ts-node/esm/transpile-only", pathToFileURL("./"));'
(Use `node --trace-warnings ...` to show where the warning was created)
  hardhat:core:vars:varsManager Creating a new instance of VarsManager +0ms
  hardhat:core:vars:varsManager Loading ENV variables if any +1ms
  hardhat:core:config Loading Hardhat config from /Users/x/dev/xyz/hardhat/hardhat.config.cts +0ms
An unexpected error occurred:

/Users/x/dev/yz/hardhat/hardhat.config.cts:3
import { BigNumber } from 'ethers';
^^^^^^

SyntaxError: Cannot use import statement outside a module
```

**Comment by rrthomas** [comment]
This worked for me in 2.19.4! Thanks very much for the ESM TypeScript support.

**Comment by signorecello** [comment]
Hey, great job finally making this over the ESM obstacle! But when using a project that uses `esnext` for the `module` option (which may be needed if, for example, you need to use `Bundler` for `moduleResolution`) this effectively ceases to work.

The solution would be to maybe use different `tsconfig` for hardhat but that is even more `hacky`. Wondering if you guys are still working on making ESM default in Hardhat?

**Comment by kanej** [comment]
@signorecello it is a big update to support ESM fully, but it will be a major focus for the teams efforts over the coming months.

**Comment by Yuripetusko** [comment]
The experimental solution works fine for me, but another solution would be to simply switch from ts-node to tsx internally

**Comment by signorecello** [comment]
Thanks! I went the monorepo route and it worked just fine by using separate tsconfigs. 

I was just wondering if you were still going for the full support. Seems like you are, which is great!

Thanks!

**Comment by schaable** [comment]
> can hardhat just migrate to https://www.npmjs.com/package/tsx package? It runs without any problems with ESM, it was built to be ESM first.

> The experimental solution works fine for me, but another solution would be to simply switch from ts-node to tsx internally

We tried that approach and, with our current setup, it's not possible to swap from `ts-node` to `tsx` without introducing breaking changes. As @kanej said, it's one of the key items we'll focus over the next months. Rest assured, full ESM support is on the way.

**Comment by Yuripetusko** [comment]
> > can hardhat just migrate to https://www.npmjs.com/package/tsx package? It runs without any problems with ESM, it was built to be ESM first.
> 
> > The experimental solution works fine for me, but another solution would be to simply switch from ts-node to tsx internally
> 
> We tried that approach and, with our current setup, it's not possible to swap from `ts-node` to `tsx` without introducing breaking changes. As @kanej said, it's one of the key items we'll focus over the next months. Rest assured, full ESM support is on the way.

Feel free to ignore, but just curious what are the blockers/breaking changes for switching hardhat to tsx? Also breaking change is not a big deal IMO if it allows to shed some legacy support and help move the whole dev ecosystem to a modern tooling and approaches

**Comment by fullkomnun** [comment]
Thanks for adding this support!

Recently migrated a TS prject to ESM and here's my feedback: 
1. Most of the codebase has been succesfully migrated (tests, scripts etc) except for `hardhat.config` and some related setup utils and tasks.
2. I had to patch `hardhat-deploy` (see [this](https://github.com/wighawag/template-ethereum-contracts/pull/14)) but was able to get it to load both CJS/ESM deployment scripts transparently. I'm not sure [how should proper support be added](https://github.com/wighawag/hardhat-deploy/issues/515) to the plugin itself.
3. The verbosity of `NODE_OPTIONS` is quite annoying but I was able to hide it away when using [mocha directly](https://github.com/fullkomnun/template-ethereum-contracts/blob/ffa6f8c8f6c659997b3d48e6faefd00b8cb21c3f/.mocharc.cjs#L25) (via `.mocharc`) or when [using a wrapper script](https://github.com/fullkomnun/template-ethereum-contracts/blob/ffa6f8c8f6c659997b3d48e6faefd00b8cb21c3f/_scripts.cjs#L24) to keep `package.json` clean. This also allows applying type checking conditionally based on `HARDHAT_TYPECHECK` env var (which by itself no longer affect type-check).
4. In addition to the configuration you mentioned I found that running tests in-parallel fails unless I also add ` "experimentalSpecifierResolution": "node"`:
```json
  "ts-node": {
    "experimentalSpecifierResolution": "node",
    "experimentalResolver": true,
    "files": true,
  },
```
with the following error:
```
  1) Uncaught error outside test suite:
     Uncaught Cannot find module '<REDACTED>/solidity/node_modules/hardhat/register' imported from <REDACTED>/solidity/node_modules/mocha/lib/nodejs/esm-utils.js
      at finalizeResolution (node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:366:11)
      at moduleResolve (node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:801:10)
      at Object.defaultResolve (node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:912:11)
      at <REDACTED>/solidity/node_modules/ts-node/src/esm.ts:218:35
      at entrypointFallback (node_modules/ts-node/src/esm.ts:168:34)
      at <REDACTED>/solidity/node_modules/ts-node/src/esm.ts:217:14
      at addShortCircuitFlag (node_modules/ts-node/src/esm.ts:409:21)
      at resolve (node_modules/ts-node/src/esm.ts:197:12)
      at nextResolve (node:internal/modules/esm/hooks:865:28)
      at Hooks.resolve (node:internal/modules/esm/hooks:303:30)
```
Could be easily reproduced [here](https://github.com/wighawag/template-ethereum-contracts/pull/14)
5. When running ESM tests/scripts (as opposed to CJS) reported LOC in call traces appear to be shifted  which makes it harder to debug. Could be easily reproduced [here](https://github.com/wighawag/template-ethereum-contracts/pull/14).
It is probably a bug in `ts-node`, and there have been reports of [similar issues probably due to a different root cause](https://github.com/TypeStrong/ts-node/issues/2053). 

Failed attempt to mitigate:
- Tried to use: Node 18 or Node 21. 
- Tried to use the beta release of ts-node  '11.0.0-beta.1' 
- Verified that we use latest versions of `typescript` and `ts-node` 
- Forced 'hardhat' to use specific versions (latest) of `mocha` and `ts-node` (NOTE: issue is not restricted to tests!)
- Tried to play with tsconfig and [NODE_OPTIONS](https://github.com/TypeStrong/ts-node/issues/2053#issuecomment-1877495719) (like add `--enable-source-maps`)

6. There's [this](https://github.com/NomicFoundation/hardhat/issues/4861) rare issue which is hard to reproduce

**Comment by sim31** [comment]
I experience the shifted line numbers in stack traces as well. Thanks @fullkomnun for your report, saved me time from trying these mitigations myself.

**Comment by pogilvie** [comment]
It's 2024 and I'd like to start new projects with Typescript and ESM support.  It would be create to support a runtime like Bun or Deno which supports these natively out of the box.

**Comment by Ahmedborwin** [comment]
I am trying to migrate a scaffold-eth project to allow for hardhat ESM support. I have followed the instructions listed by @schaable but I still get the much-loved HH19 error when I try to import hardhat tasks (that I got from the chainlink functions boilerplate) to my hardhat.config.cts. 

The tasks folder is made up of .js scripts that are common modules. Not sure why importing them is causing the error in the first place. I tried converting them to .cjs but still no luck. 

Anyone have any idea how I can make these hardhat tasks available to my hardhat typescript project? 

If this question is badly worded, please be patient with me. I am learning. Thank you

**Comment by damianobarbati** [comment]
Is there any news on the topic from the team? Should the user expect the project to be stuck on the old CJS or was any progress made with ESM? Thanks guys for the effort.

**Comment by kanej** [comment]
> Is there any news on the topic from the team? Should the user expect the project to be stuck on the old CJS or was any progress made with ESM? Thanks guys for the effort.

The team is currently focused on the next version of Hardhat, which will support ESM.

**Comment by 0xVinCal** [comment]
It would be great if the next version could be used with `bun`

**Comment by ppciesiolkiewicz** [comment]
Just letting you know
<img width="802" alt="Screenshot 2024-10-22 at 12 43 35" src="https://github.com/user-attachments/assets/6f9ba430-2758-41da-840d-566dcd0ee0eb">

Needed to use `permissionless` lib from Pimlico

**Comment by kanej** [comment]
Hardhat 3 will have support for ESM, it is currently in private Alpha. I am not aware of an ESM supporting alternative currently.

**Comment by vinerz** [comment]
Amazing news @kanej! Is there a possibility of joining this alpha group?

**Comment by 0xVinCal** [comment]
@kanej , I would be interested to join the private alpha

**Comment by rhlsthrm** [comment]
I am also interested in joining private alpha.

**Comment by olehmisar** [comment]
@kanej i want to join private alpha as well. Completely blocked by lack of ESM support with typescript

**Comment by olehmisar** [comment]
i managed to import esm like this:
```ts
const { tsImport } = require("tsx/esm/api")
const mod = await tsImport("./my-esm-module", __filename); 
```

**Comment by CJ42** [comment]
Seems that Hyperlane has an interesting approach to enable ESM with Typescript in their monorepo.

https://github.com/hyperlane-xyz/hyperlane-monorepo/blob/170a0fc73922297b1163316825bd98ff352fe57f/solidity/package.json#L73

**Comment by canastro** [comment]
Is there any way to get access to the alpha testing of hardhat?  I've tried following the steps in this [comment](https://github.com/NomicFoundation/hardhat/issues/3385#issuecomment-1841380253) but I always face a few different problems, eg. problems with `@nomicfoundation/hardhat-chai-matchers`

**Comment by kanej** [comment]
> Is there any way to get access to the alpha testing of hardhat? I've tried following the steps in this [comment](https://github.com/NomicFoundation/hardhat/issues/3385#issuecomment-1841380253) but I always face a few different problems, eg. problems with `@nomicfoundation/hardhat-chai-matchers`

Hey @canastro, thanks for the interest. The alpha is still very rough and lacks many basic features; it is not usable for general development currently, instead being more a test bed for new capabilities.

**Comment by canastro** [comment]
I found a workaround that might be specific to my use case:

I have an npm package containing my smart contracts, which I need to import into other packages within my monorepo. Since the package needs to be ESM, my main goal is to export only the Typechain factories.

To address this, I implemented the following steps:

* Based on [this comment](https://github.com/NomicFoundation/hardhat/issues/3385#issuecomment-2513829018), I created a hardhat-esm command and replaced all scripts.
* Following [this comment](https://github.com/NomicFoundation/hardhat/issues/3385#issuecomment-1841380253):
  * Updated my tsconfig.
  * Modified imports to use hardhat.

I avoided creating a Hardhat task to generate a package.json in the typechains folder, as doing so would conflict with my goal of exporting the package for use in an ESM context.

**Comment by damianobarbati** [comment]
@olehmisar @kanej how can we try alpha? 

The lack of proper native ESM is indeed a blocker, and also the time needed to properly adopt the current standard (it's been 2+ years...) is casting a lot of shadows on the project imho.

**Comment by lbltavares** [comment]
> [@olehmisar](https://github.com/olehmisar) [@kanej](https://github.com/kanej) how can we try alpha?
> 
> The lack of proper native ESM is indeed a blocker, and also the time needed to properly adopt the current standard (it's been 2+ years...) is casting a lot of shadows on the project imho.

Indeed

**Comment by kanej** [comment]
Hey, we have just opened up the Hardhat 3 Alpha publicly. It includes ESM support. Please take a look and give us your feedback:

https://github.com/NomicFoundation/hardhat/releases/tag/hardhat%403.0.0-next.0

**Comment by whitehatsentinel** [comment]
Hey @kanej thanks for sharing the Hardhat 3 public alpha, this has been a life-saver for me!

However, any idea why I can do `npx hardhat run path/to/file.test.ts`, but when I do `npx hardhat test path/to/file.test.ts` (with "test" instead) I get this strange error? This used to work in Hardhat 2, thanks for your help!

```
Error HHE506: The argument with value "path/to/file.test.ts" was not consumed because it is not associated with any task.
```

**Comment by kanej** [comment]
Hardhat 3 is available and fully supports ESM in typescript projects. Take a look: https://hardhat.org/docs/getting-started
