### ISSUE TITLE
Revert reason is not supported with ganache

### ISSUE THREAD

**Issue by joelamouche** [NomicFoundation/hardhat#3441]
I am using hardhat 2.12.0 and "ganache": "^7.7.2" (and I also tried using "@nomiclabs/hardhat-ganache") and when I run my test with a function call that should revert with "rollcall: proposal vote doesnt exist", I get this error:

```
Error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0xF781758bd10510d809eF2bEb11cbd2DE06d0C2e9","to":"0x1f047465513B6d7928cAF253B933E448a09C8700","data":"0x3e4f49e60000000000000000000000000000000000000000000000000000000000003039","accessList":null}, error={"name":"ProviderError","_stack":"ProviderError: HttpProviderError\n    at HttpProvider.request (/Users/antoineestienne/Github_Files/contracts/node_modules/hardhat/src/internal/core/providers/http.ts:78:19)\n    at AutomaticSenderProvider.request (/Users/antoineestienne/Github_Files/contracts/node_modules/hardhat/src/internal/core/providers/accounts.ts:341:34)\n    at AutomaticGasProvider.request (/Users/antoineestienne/Github_Files/contracts/node_modules/hardhat/src/internal/core/providers/gas-providers.ts:135:34)\n    at FixedGasPriceProvider.request (/Users/antoineestienne/Github_Files/contracts/node_modules/hardhat/src/internal/core/providers/gas-providers.ts:54:34)\n    at BackwardsCompatibilityProviderAdapter.send (/Users/antoineestienne/Github_Files/contracts/node_modules/hardhat/src/internal/core/providers/backwards-compatibility.ts:36:27)\n    at EthersProviderWrapper.send (/Users/antoineestienne/Github_Files/contracts/node_modules/@nomiclabs/hardhat-ethers/src/internal/ethers-provider-wrapper.ts:13:48)\n    at EthersProviderWrapper.<anonymous> (/Users/antoineestienne/Github_Files/contracts/node_modules/@ethersproject/providers/src.ts/json-rpc-provider.ts:640:31)\n    at step (/Users/antoineestienne/Github_Files/contracts/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:48:23)\n    at Object.next (/Users/antoineestienne/Github_Files/contracts/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:29:53)\n    at /Users/antoineestienne/Github_Files/contracts/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:23:71\n    at new Promise (<anonymous>)\n    at __awaiter (/Users/antoineestienne/Github_Files/contracts/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:19:12)\n    at EthersProviderWrapper.JsonRpcProvider.perform (/Users/antoineestienne/Github_Files/contracts/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:720:16)\n    at EthersProviderWrapper.<anonymous> (/Users/antoineestienne/Github_Files/contracts/node_modules/@ethersproject/providers/src.ts/base-provider.ts:1640:35)\n    at step (/Users/antoineestienne/Github_Files/contracts/node_modules/@ethersproject/providers/lib/base-provider.js:48:23)\n    at Object.next (/Users/antoineestienne/Github_Files/contracts/node_modules/@ethersproject/providers/lib/base-provider.js:29:53)","code":-32000,"_isProviderError":true,"data":{"0xb52e1c32d4786e8973d4368243cbf5a8ea6ffd7dd181361da476550c1ce08473":{"error":"revert","program_counter":1577,"return":"0x08c379a000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000024726f6c6c63616c6c3a2070726f706f73616c20766f746520646f65736e7420657869737400000000000000000000000000000000000000000000000000000000","reason":"rollcall: proposal vote doesnt exist"},"stack":"RuntimeError: VM Exception while processing transaction: revert rollcall: proposal vote doesnt exist\n    at Function.RuntimeError.fromResults (/Users/antoineestienne/Github_Files/contracts/node_modules/ganache-core/lib/utils/runtimeerror.js:94:13)\n    at /Users/antoineestienne/Github_Files/contracts/node_modules/ganache-core/lib/blockchain_double.js:568:26","name":"RuntimeError"}}, code=CALL_EXCEPTION, version=providers/5.7.2)
    at Logger.makeError (/Users/antoineestienne/Github_Files/contracts/node_modules/@ethersproject/logger/src.ts/index.ts:269:28)
    at Logger.throwError (/Users/antoineestienne/Github_Files/contracts/node_modules/@ethersproject/logger/src.ts/index.ts:281:20)
    at checkError (/Users/antoineestienne/Github_Files/contracts/node_modules/@ethersproject/providers/src.ts/json-rpc-provider.ts:66:16)
    at EthersProviderWrapper.<anonymous> (/Users/antoineestienne/Github_Files/contracts/node_modules/@ethersproject/providers/src.ts/json-rpc-provider.ts:642:20)
    at step (/Users/antoineestienne/Github_Files/contracts/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:48:23)
    at Object.throw (/Users/antoineestienne/Github_Files/contracts/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:29:53)
    at rejected (/Users/antoineestienne/Github_Files/contracts/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:21:65)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

As explained in https://github.com/trufflesuite/ganache/issues/2935#issuecomment-1102899802 , the error message does contain the right encoded revert reason: `0x08c379a000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000024726f6c6c63616c6c3a2070726f706f73616c20766f746520646f65736e7420657869737400000000000000000000000000000000000000000000000000000000` but it is not handled correctly by hardhat

**Comment by fvictorio** [comment]
Hi @joelamouche, I get the same error if I use plain ethers, so this is not a Hardhat issue.

Reproduction: deploy this contract in ganache

```solidity
contract Foo {
  function f() public pure {
    require(false, "some reason");
  }
}
```

and run this script:

```js
const ethers = require("ethers");

async function main() {
  const provider = new ethers.providers.JsonRpcProvider(
    "http://localhost:8545"
  );

  const foo = new ethers.Contract(
    addressOfContract,
    ["function f() public pure"],
    provider
  );

  await foo.f();
}

main()
  .then(() => process.exit(0))
  .catch(error => {
    console.error(error);
    process.exit(1);
  });
```

We had a similar problem in Hardhat in the past, and we fixed it by adding some extra data in the JSON-RPC error response. I don't remember the details, but if the ganache team needs help I can try to find the PR.
