### ISSUE TITLE
Assembly revert only be caught for those functions with returns declaration.

### ISSUE THREAD

**Issue by smtmfft** [NomicFoundation/hardhat#3577]
### Version of Hardhat

2.12.5

### What happened?

Not sure if it's a bug,

The test catches revert only if function has return signature.
See below 2 solidity functions, which contains only 1 simple assembly revert

```solidity
function simpleAssemblyRevert() public view {
    assembly {
        revert(0, 0)
    }
}
function simpleAssemblyRevertWithReturn() public view returns (uint){
    assembly {
        revert(0, 0)
    }
}
```

and corresponding 2 unit tests:

```ts
it.only("simple revert", async function(){
    const { simpleAssembly } = await loadFixture(deploySimpleAssemblyFixture);
    await expect(simpleAssembly.simpleAssemblyRevert()).to.be.reverted;
});
it.only("simple revert with return", async function(){
    const { simpleAssembly } = await loadFixture(deploySimpleAssemblyFixture);
    await expect(simpleAssembly.simpleAssemblyRevertWithReturn()).to.be.reverted;
});
```

The test results are:

```bash
  SimpleAssembly
    test simple assembly
      1) simple revert
      ✔ simple revert with return


  1 passing (812ms)
  1 failing

  1) SimpleAssembly
       test simple assembly
         simple revert:
     AssertionError: Expected transaction to be reverted
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at runNextTicks (internal/process/task_queues.js:64:3)
      at listOnTimeout (internal/timers.js:526:9)
      at processTimers (internal/timers.js:500:7)
      at async Context.<anonymous> (test/SimpleAssembly.ts:32:13)
```

The error **AssertionError: Expected transaction to be reverted** this line seems the one without return does not revert. 
Not sure if this is a bug or I misunderstood sth about solidity assembly.
Please help to take a look.
Thanks!

### Minimal reproduction steps

Test solidity:
```solidity
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.7;

// Uncomment this line to use console.log
// import "hardhat/console.sol";

contract SimpleAssembly {
    address payable public owner;

    constructor() payable {
        owner = payable(msg.sender);
    }

    function simpleAssemblyRevert() public view {
        assembly {
            revert(0, 0)
        }
    }

    function simpleAssemblyRevertWithReturn() public view returns (uint){
        assembly {
            revert(0, 0)
        }
    }
}
```

Test script:
```ts
import { time, loadFixture } from "@nomicfoundation/hardhat-network-helpers";
import { expect } from "chai";
import { BigNumber } from "ethers";
import { ethers } from "hardhat";

describe("SimpleAssembly", function () {
    // We define a fixture to reuse the same setup in every test.
    // We use loadFixture to run this setup once, snapshot that state,
    // and reset Hardhat Network to that snapshot in every test.
    async function deploySimpleAssemblyFixture() {
        const ONE_GWEI = 1_000_000_000;
        const GAS_LIMIT = 30_000_000

        // Contracts are deployed using the first signer/account by default
        const [owner, otherAccount] = await ethers.getSigners();

        const SimpleAssembly = await ethers.getContractFactory("SimpleAssembly");
        const simpleAssembly = await SimpleAssembly.deploy({value: 0, gasLimit: GAS_LIMIT });

        return { simpleAssembly, owner, otherAccount };
    }
    
    describe.only("test simple assembly", function () {
        it.only("simple revert", async function(){
            const { simpleAssembly } = await loadFixture(deploySimpleAssemblyFixture);

            await expect(simpleAssembly.simpleAssemblyRevert()).to.be.reverted;
        });

        it.only("simple revert with return", async function(){
            const { simpleAssembly } = await loadFixture(deploySimpleAssemblyFixture);
            await expect(simpleAssembly.simpleAssemblyRevertWithReturn()).to.be.reverted;
        });
    });
});

```

run `npx hardhat test`

### Search terms

assembly; revert;

**Comment by fvictorio** [comment]
Hi @smtmfft, this is a known bug in ethers (see [this issue](https://github.com/ethers-io/ethers.js/issues/3038)). Sadly there isn't much we can do on our side until it gets fixed.
