### ISSUE TITLE
 `Error: Transaction reverted and Hardhat couldn't infer the reason` when testing `safeTransferFrom` or `transferFrom`

### ISSUE THREAD

**Issue by badmetacoder** [NomicFoundation/hardhat#3617]
### Version of Hardhat

2.12.6

### What happened?

I am writing tests for an NFT using `safeTransferFrom` and `transferFrom` with `onlyAllowedOperator` and the tests are failing with and without `onlyAllowedOperator`. Here's the function:

```solidity
contract NFT is ERC721, Ownable, DefaultOperatorFilterer {
}
...
function transferFrom(address from, address to, uint256 tokenId) public override onlyAllowedOperator(from) {
        transferFrom(from, to, tokenId);
    }
```

and here's the test:

```javascript
describe("ERC721: transferFrom()", function () {

    it("transferFrom(): Transfer From owner to newOwner (address)", async function () {
      const { nft, owner, operator, newOwner, newOperator, minter } = await loadFixture(deployNFTFixture);

      await nft.mintTo(owner.address); // 1
      
      expect(await nft.balanceOf(owner.address)).to.equal(1);
      expect(await nft.balanceOf(newOwner.address)).to.equal(0);

      await nft.transferFrom(owner.address,newOwner.address,1);

      expect(await nft.balanceOf(owner.address)).to.equal(0);
      expect(await nft.balanceOf(newOwner.address)).to.equal(1);

    });
  });
```

I am getting the following message when I run the test with `npx hardhat test`:

```javascript
ERC721: transferFrom()
         transferFrom(): Transfer From owner to newOwner (address) fails:
     Error: Transaction reverted and Hardhat couldn't infer the reason.
    at NFT.transferFrom (contracts/NFT.sol:315)
    ...
    at NFT.transferFrom (contracts/NFT.sol:315)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at runNextTicks (node:internal/process/task_queues:65:3)
    at listOnTimeout (node:internal/timers:526:9)
    at processTimers (node:internal/timers:500:7)
    at async HardhatNode._mineBlockWithPendingTxs (node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:1815:23)
    at async HardhatNode.mineBlock (node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:504:16)
    at async EthModule._sendTransactionAndReturnHash (node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:1522:18)
```

### Minimal reproduction steps

Run `npx hardhat test`

### Search terms

safeTransferFrom, transferFrom

**Comment by badmetacoder** [comment]
Turns out I needed to use `super` in:

```
function transferFrom(address from, address to, uint256 tokenId) public override onlyAllowedOperator(from) {
        super.transferFrom(from, to, tokenId);
    }
```
