### ISSUE TITLE
"UnimplementedFeatureError provides no source reference

### ISSUE THREAD

**Issue by grapevinegizmos** [NomicFoundation/hardhat#3619]
### Version of Hardhat

2.12.0

### What happened?

Attempting to compile my project I got the following error (run with --show-stack-traces)

```
UnimplementedFeatureError: Copying of type struct KeyPair memory[] memory to storage not yet supported.


Error HH600: Compilation failed

HardhatError: HH600: Compilation failed
    at SimpleTaskDefinition.action (/Users/jk/Documents/VSCodeProjects/BKopy/bkopy-nft-contracts/node_modules/hardhat/src/builtin-tasks/compile.ts:456:15)
    at async Environment._runTaskDefinition (/Users/jk/Documents/VSCodeProjects/BKopy/bkopy-nft-contracts/node_modules/hardhat/src/internal/core/runtime-environment.ts:308:14)
    at async OverriddenTaskDefinition._action (/Users/jk/Documents/VSCodeProjects/BKopy/bkopy-nft-contracts/node_modules/@typechain/hardhat/src/index.ts:28:30)
    at async Environment._runTaskDefinition (/Users/jk/Documents/VSCodeProjects/BKopy/bkopy-nft-contracts/node_modules/hardhat/src/internal/core/runtime-environment.ts:308:14)
    at async Environment.run (/Users/jk/Documents/VSCodeProjects/BKopy/bkopy-nft-contracts/node_modules/hardhat/src/internal/core/runtime-environment.ts:156:14)
    at async SimpleTaskDefinition.action (/Users/jk/Documents/VSCodeProjects/BKopy/bkopy-nft-contracts/node_modules/hardhat/src/builtin-tasks/compile.ts:1331:63)
    at async Environment._runTaskDefinition (/Users/jk/Documents/VSCodeProjects/BKopy/bkopy-nft-contracts/node_modules/hardhat/src/internal/core/runtime-environment.ts:308:14)
    at async Environment.run (/Users/jk/Documents/VSCodeProjects/BKopy/bkopy-nft-contracts/node_modules/hardhat/src/internal/core/runtime-environment.ts:156:14)
    at async SimpleTaskDefinition.action (/Users/jk/Documents/VSCodeProjects/BKopy/bkopy-nft-contracts/node_modules/hardhat/src/builtin-tasks/compile.ts:1411:7)
    at async Environment._runTaskDefinition (/Users/jk/Documents/VSCodeProjects/BKopy/bkopy-nft-contracts/node_modules/hardhat/src/internal/core/runtime-environment.ts:308:14)
```
Typically, compile errors show me where the error occurred, but not in this case, even with stack trace, no way to identify where I have done such a thing.  With a big code base, and lots of updates, that's a lot of hunting and testing time to find the source.

Is it possible for this error message to identify the source code responsible?

### Minimal reproduction steps

hh compile

### Search terms

UnimplementedFeatureError

**Comment by fvictorio** [comment]
Hi @grapevinegizmos, sorry for not responding before.

I think this is a solc issue, so there isn't much we can do on our side: https://github.com/ethereum/solidity/issues/12783
