### ISSUE TITLE
Error HH412: Invalid import hardhat/console.sol 

### ISSUE THREAD

**Issue by Airwave1981** [NomicFoundation/hardhat#3623]
### Version of Hardhat

2.12.6

### What happened?

Since update on 2.12.6 I get the error:

Error HH412: Invalid import hardhat/console.sol from contracts/xyz.sol. Trying to import file using the own package's name.

```
HardhatError: HH412: Invalid import hardhat/console.sol from contracts/mycontract.sol. Trying to import file using the own package's name.
    at Resolver.resolveImport (/home/me/develop/nft-backend/hardhat/node_modules/hardhat/src/internal/solidity/resolver.ts:140:13)
    at /home/me/develop/nft-backend/hardhat/node_modules/hardhat/src/internal/solidity/dependencyGraph.ts:176:28
    at async Promise.all (index 6)
    at DependencyGraph._addDependenciesFrom (/home/me/develop/nft-backend/hardhat/node_modules/hardhat/src/internal/solidity/dependencyGraph.ts:174:5)
    at async Promise.all (index 1)
    at Function.createFromResolvedFiles (/home/me/develop/nft-backend/hardhat/node_modules/hardhat/src/internal/solidity/dependencyGraph.ts:13:5)
    at SimpleTaskDefinition.action (/home/me/develop/nft-backend/hardhat/node_modules/hardhat/src/builtin-tasks/compile.ts:202:31)
    at Environment._runTaskDefinition (/home/me/develop/nft-backend/hardhat/node_modules/hardhat/src/internal/core/runtime-environment.ts:311:14)
    at Environment.run (/home/me/develop/nft-backend/hardhat/node_modules/hardhat/src/internal/core/runtime-environment.ts:159:14)
    at SimpleTaskDefinition.action (/home/me/develop/nft-backend/hardhat/node_modules/hardhat/src/builtin-tasks/compile.ts:1311:58)
```

The import in the contract is correct:

import "hardhat/console.sol";

Anyone has an idea to solve this? 

### Minimal reproduction steps

Version installed up to 2.12.2
npm install --save-dev hardhat@↨2.12.3 (and older than 2.12.3)
npx hardhat --version
npx hardhat compile

### Search terms

console error hh412 import

**Comment by fvictorio** [comment]
Hi, I think this happen because the `name` entry in your `package.json` is "hardhat". Changing it to something else should fix the issue. There is a better fix for this, but I opened https://github.com/NomicFoundation/hardhat/issues/3625 to track it.

**Comment by fvictorio** [comment]
We were forbidding importing a package through its own name, mainly because it caused problems in monorepos. But we can (and should) support that, that's what #3625 is about.
