### ISSUE TITLE
TypeError: glob is not a function after updating project from typechain-hardhat to @typechain/hardhat package.

### ISSUE THREAD

**Issue by r0ugeEngine** [NomicFoundation/hardhat#3649]
After updating project from typechain-hardhat to @typechain/hardhat package.

Compilation of project throws TypeError: glob is not a function error. And I can not run scripts, tests, compile etc.

```
An unexpected error occurred:

TypeError: glob is not a function
    at SimpleTaskDefinition.action (C:\Users\user\SmartContracts\trade-smart-contracts\node_modules\@typechain\hardhat\src\index.ts:70:22)
    at Environment._runTaskDefinition (C:\Users\user\SmartContracts\trade-smart-contracts\node_modules\hardhat\src\internal\core\runtime-environment.ts:308:14)
    at Environment.run (C:\Users\user\SmartContracts\trade-smart-contracts\node_modules\hardhat\src\internal\core\runtime-environment.ts:156:14)
    at OverriddenTaskDefinition._action (C:\Users\user\SmartContracts\trade-smart-contracts\node_modules\@typechain\hardhat\src\index.ts:29:5)
    at Environment._runTaskDefinition (C:\Users\user\SmartContracts\trade-smart-contracts\node_modules\hardhat\src\internal\core\runtime-environment.ts:308:14)
    at Environment.run (C:\Users\user\SmartContracts\trade-smart-contracts\node_modules\hardhat\src\internal\core\runtime-environment.ts:156:14)
    at SimpleTaskDefinition.action (C:\Users\user\SmartContracts\trade-smart-contracts\node_modules\hardhat\src\builtin-tasks\compile.ts:1331:63)
    at Environment._runTaskDefinition (C:\Users\user\SmartContracts\trade-smart-contracts\node_modules\hardhat\src\internal\core\runtime-environment.ts:308:14)
    at Environment._runTaskDefinition (C:\Users\user\SmartContracts\trade-smart-contracts\node_modules\hardhat\src\internal\core\runtime-environment.ts:308:14)
    at Environment.run (C:\Users\user\SmartContracts\trade-smart-contracts\node_modules\hardhat\src\internal\core\runtime-environment.ts:156:14)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by r0ugeEngine** [comment]
I've solved this issue: 
the problem was that the previous `typechain-hardhat` package generated the `typechain` folder, but now `@typechain/hardhat` generates `typechain-types` folder
