### ISSUE TITLE
Cannot deploy. `[contract creation code storage out of gas]` error

### ISSUE THREAD

**Issue by 0xSwego** [NomicFoundation/hardhat#3674]
### Version of Hardhat

2.12.7

### What happened?

Suddenly I am not able to deploy UPGRADEABLE contracts POLYGON anymore (normal contracts on Polygon work, upgradeable contracts on other chains work)

The console shows this error:
```text
InvalidDeployment [Error]: No contract at address 0x67AE4792D6c5E3878F5Ebafea6d99EbeDBB4fe27 (Removed from manifest)
    at waitAndValidateDeployment (C:\Users\alvin\Development\Solidity\impact-self\node_modules\@openzeppelin\upgrades-core\src\deployment.ts:160:15)       
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async fetchOrDeployGeneric (C:\Users\alvin\Development\Solidity\impact-self\node_modules\@openzeppelin\upgrades-core\src\impl-store.ts:70:5)        
    at async deployImpl (C:\Users\alvin\Development\Solidity\impact-self\node_modules\@openzeppelin\hardhat-upgrades\src\utils\deploy-impl.ts:96:22)       
    at async deployProxyImpl (C:\Users\alvin\Development\Solidity\impact-self\node_modules\@openzeppelin\hardhat-upgrades\src\utils\deploy-impl.ts:74:10)  
    at async Proxy.upgradeProxy (C:\Users\alvin\Development\Solidity\impact-self\node_modules\@openzeppelin\hardhat-upgrades\src\upgrade-proxy.ts:25:32)   
    at async main (C:\Users\alvin\Development\Solidity\impact-self\scripts\upgrade-mainnet.ts:9:16)
```

This is one of the txs that failed:
https://polygonscan.com/tx/0x5155f552ef3036c4f9b8256d23ce472ab5d240953e9c7ec8b383e5528fa2f229

While deploying it on Mumbai succeded:
https://mumbai.polygonscan.com/tx/0x2e931942776594397e2f2e574834b6187f49434fd519acc59a208a53a3f266cd

I noticed that all the gas is used (Gas Used by Transaction = Gas Limit), but this also happened in the past and with the successfully deployed contract. Is it possible that there is a problem with the estimation of the gas?

<details>
<summary>Packages + versions</summary>

```
    "@chainlink/contracts": "^0.5.1",
    "@nomiclabs/hardhat-ethers": "^2.2.2",
    "@nomiclabs/hardhat-etherscan": "^3.1.6",
    "@nomiclabs/hardhat-waffle": "^2.0.5",
    "@nomicfoundation/hardhat-network-helpers": "^1.0.8",
    "@openzeppelin/contracts-upgradeable": "^4.8.1",
    "@openzeppelin/hardhat-upgrades": "^1.22.1",
    "@typechain/ethers-v5": "^10.1.1",
    "@types/fs-extra": "^11.0.1",
    "@typechain/hardhat": "^6.1.5",
    "@types/mocha": "^10.0.1",
    "chai": "^4.3.6",
    "dotenv": "^16.0.3",
    "ethereum-waffle": "^4.0.9",
    "ethers": "^5.7.2",
    "fs-extra": "^11.1.0",
    "hardhat": "^2.12.7",
    "hardhat-contract-sizer": "^2.8.0",
    "hardhat-deploy": "^0.11.23",
    "mocha": "^10.1.0",
    "solidity-coverage": "^0.8.2",
    "ts-node": "^10.9.1",
    "typechain": "^8.1.1",
    "typescript": "^4.9.5"
```

</details>

### Minimal reproduction steps

This is the code I use. It fails at `deployProxy`
```
  const Hook = await ethers.getContractFactory("DepositorWithVesting");
  const hook = await upgrades.deployProxy(Hook, [], { kind: "uups" });
  await hook.deployed();
```

### Search terms

contract creation code storage out of gas error

**Comment by alcuadrado** [comment]
Hi @0xSwego,

Can you report this to the Open Zeppelin plugin instead? This doesn't seem to be an error coming from Hardhat.

**Comment by 0xSwego** [comment]
@alcuadrado noted, thanks
