### ISSUE TITLE
typescript /pnpm 

### ISSUE THREAD

**Issue by DRIPDROPS** [NomicFoundation/hardhat#3714]
### Version of Hardhat

2.12.7

### What happened?

aulyaries@saulyaries-desktop:~/Desktop/dddd$ ts-node bundle.ts 
/home/saulyaries/Desktop/dddd/node_modules/.pnpm/hardhat@2.12.7_6qtx7vkbdhwvdm4crzlegk4mvi/node_modules/hardhat/src/internal/context.ts:37
      throw new HardhatError(ERRORS.GENERAL.CONTEXT_NOT_CREATED);
            ^
HardhatError: HH5: HardhatContext is not created.
    at Function.getHardhatContext (/home/saulyaries/Desktop/dddd/node_modules/.pnpm/hardhat@2.12.7_6qtx7vkbdhwvdm4crzlegk4mvi/node_modules/hardhat/src/internal/context.ts:37:13)
    at extendEnvironment (/home/saulyaries/Desktop/dddd/node_modules/.pnpm/hardhat@2.12.7_6qtx7vkbdhwvdm4crzlegk4mvi/node_modules/hardhat/src/internal/core/config/config-env.ts:128:30)
    at Object.<anonymous> (/home/saulyaries/Desktop/dddd/node_modules/.pnpm/@nomiclabs+hardhat-ethers@2.2.2_4tzilew2vuitdwerzusliplz24/node_modules/@nomiclabs/hardhat-ethers/src/internal/index.ts:27:18)
    at Module._compile (node:internal/modules/cjs/loader:1191:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1245:10)
    at Object.require.extensions.<computed> [as .js] (/usr/share/nodejs/ts-node/src/index.ts:1614:43)
    at Module.load (node:internal/modules/cjs/loader:1069:32)
    at Function.Module._load (node:internal/modules/cjs/loader:904:12)
    at Module.require (node:internal/modules/cjs/loader:1093:19)
    at require (node:internal/modules/cjs/helpers:108:18) {
  parent: undefined,
  _stack: 'HardhatError: HH5: HardhatContext is not created.\n' +
    '    at Function.getHardhatContext (/home/saulyaries/Desktop/dddd/node_modules/.pnpm/hardhat@2.12.7_6qtx7vkbdhwvdm4crzlegk4mvi/node_modules/hardhat/src/internal/context.ts:37:13)\n' +
    '    at extendEnvironment (/home/saulyaries/Desktop/dddd/node_modules/.pnpm/hardhat@2.12.7_6qtx7vkbdhwvdm4crzlegk4mvi/node_modules/hardhat/src/internal/core/config/config-env.ts:128:30)\n' +
    '    at Object.<anonymous> (/home/saulyaries/Desktop/dddd/node_modules/.pnpm/@nomiclabs+hardhat-ethers@2.2.2_4tzilew2vuitdwerzusliplz24/node_modules/@nomiclabs/hardhat-ethers/src/internal/index.ts:27:18)\n' +
    '    at Module._compile (node:internal/modules/cjs/loader:1191:14)\n' +
    '    at Module._extensions..js (node:internal/modules/cjs/loader:1245:10)\n' +
    '    at Object.require.extensions.<computed> [as .js] (/usr/share/nodejs/ts-node/src/index.ts:1614:43)\n' +
    '    at Module.load (node:internal/modules/cjs/loader:1069:32)\n' +
    '    at Function.Module._load (node:internal/modules/cjs/loader:904:12)\n' +
    '    at Module.require (node:internal/modules/cjs/loader:1093:19)\n' +
    '    at require (node:internal/modules/cjs/helpers:108:18)',
  errorDescriptor: {
    number: 5,
    message: 'HardhatContext is not created.',
    title: "Hardhat wasn't initialized",
    description: 'Hardhat initialization failed. This is a bug.\n' +
      '\n' +
      'Please [report it](https://github.com/nomiclabs/hardhat/issues/new) to help us improve Hardhat.',
    shouldBeReported: true
  },
  number: 5,
  messageArguments: {},
  _isHardhatError: true
}
saulyaries@saulyaries-desktop:~/Desktop/dddd$ npx hardhat --version
2.12.7
saulyaries@saulyaries-desktop:~/Desktop/dddd$ 

### Minimal reproduction steps

ts-node bundle.ts

**Comment by sshmaxime** [comment]
It's very hard to understand your issue.

That being said, you are not supposed to start your Hardhat process by launching it with `ts-node`. You should start from here: https://hardhat.org/tutorial

**Comment by fvictorio** [comment]
Closing because I don't understand what this issue is about.
