### ISSUE TITLE
trying to get fallback source reference from a contract without fallback

### ISSUE THREAD

**Issue by sherpya** [NomicFoundation/hardhat#3752]
### Version of Hardhat

2.13.0

### What happened?

trying to test Ownable pattern on a receive payable function without a fallback function

### Minimal reproduction steps

clone this repo:

https://github.com/sherpya/nerwo-contracts

lauch the specific test:
`yarn hardhat test --grep 'NerwoEscrow: funding Ownable' --verbose`

the test succeds but hardhat complains:
```
  hardhat:core:hardhat-network:node Could not generate stack trace. Please report this to help us improve Hardhat.
  hardhat:core:hardhat-network:node  Error: This shouldn't happen: trying to get fallback source reference from a contract without fallback
    at ErrorInferrer._getFallbackStartSourceReference (/home/sherpya/workspace/web3/nerwo-contracts/node_modules/hardhat/src/internal/hardhat-network/stack-traces/error-inferrer.ts:908:13)
    at ErrorInferrer._getEntryBeforeInitialModifierCallstackEntry (/home/sherpya/workspace/web3/nerwo-contracts/node_modules/hardhat/src/internal/hardhat-network/stack-traces/error-inferrer.ts:1069:29)
    at ErrorInferrer._fixInitialModifier (/home/sherpya/workspace/web3/nerwo-contracts/node_modules/hardhat/src/internal/hardhat-network/stack-traces/error-inferrer.ts:744:14)
    at ErrorInferrer._checkRevertOrInvalidOpcode (/home/sherpya/workspace/web3/nerwo-contracts/node_modules/hardhat/src/internal/hardhat-network/stack-traces/error-inferrer.ts:465:19)
    at ErrorInferrer._checkLastInstruction (/home/sherpya/workspace/web3/nerwo-contracts/node_modules/hardhat/src/internal/hardhat-network/stack-traces/error-inferrer.ts:591:44)
    at ErrorInferrer.inferAfterTracing (/home/sherpya/workspace/web3/nerwo-contracts/node_modules/hardhat/src/internal/hardhat-network/stack-traces/error-inferrer.ts:164:12)
    at SolidityTracer._rawTraceEvmExecution (/home/sherpya/workspace/web3/nerwo-contracts/node_modules/hardhat/src/internal/hardhat-network/stack-traces/solidityTracer.ts:224:61)
    at SolidityTracer._traceEvmExecution (/home/sherpya/workspace/web3/nerwo-contracts/node_modules/hardhat/src/internal/hardhat-network/stack-traces/solidityTracer.ts:159:29)
    at SolidityTracer._getCallMessageStackTrace (/home/sherpya/workspace/web3/nerwo-contracts/node_modules/hardhat/src/internal/hardhat-network/stack-traces/solidityTracer.ts:70:17)
    at SolidityTracer.getStackTrace (/home/sherpya/workspace/web3/nerwo-contracts/node_modules/hardhat/src/internal/hardhat-network/stack-traces/solidityTracer.ts:54:19) +0ms
    ✔ Ownable (1038ms)
```

### Search terms

fallback receive

**Comment by sherpya** [comment]
he problematic test:

https://github.com/sherpya/nerwo-contracts/blob/master/test/NerwoEscrow-funding.ts

**Comment by fvictorio** [comment]
Closing for lack of response.
