### ISSUE TITLE
I'm getting this problem, can u guys help out? code: 'NETWORK_ERROR'

### ISSUE THREAD

**Issue by ultperf** [NomicFoundation/hardhat#3763]
this deploy script doesnt work,
https://github.com/miukki/nft-full-stack/blob/test-winners/scripts/deploy.js

this is my hardhat config
https://github.com/miukki/nft-full-stack/blob/test-winners/hardhat.config.js

it's giving me this error, 
code: 'NETWORK_ERROR'

```
Error: could not detect network (event="noNetwork", code=NETWORK_ERROR, version=providers/5.7.1)
    at Logger.makeError (/Users/anjaishmukhametova/Projects/nft-full-stack/node_modules/@ethersproject/logger/src.ts/index.ts:269:28)
    at Logger.throwError (/Users/anjaishmukhametova/Projects/nft-full-stack/node_modules/@ethersproject/logger/src.ts/index.ts:281:20)
    at EthersProviderWrapper.<anonymous> (/Users/anjaishmukhametova/Projects/nft-full-stack/node_modules/@ethersproject/providers/src.ts/json-rpc-provider.ts:483:23)
    at step (/Users/anjaishmukhametova/Projects/nft-full-stack/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:48:23)
    at Object.throw (/Users/anjaishmukhametova/Projects/nft-full-stack/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:29:53)
    at rejected (/Users/anjaishmukhametova/Projects/nft-full-stack/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:21:65)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  reason: 'could not detect network',
  code: 'NETWORK_ERROR',
  event: 'noNetwork'
```

**Comment by miukki** [comment]
same issue here. tried setup deploy to goerli by following :
https://hardhat.org/hardhat-runner/docs/guides/deploying

<img width="820" alt="image" src="https://user-images.githubusercontent.com/132497/225024619-11ead21b-4b00-48ed-8c28-8d901adaf86b.png">

**Comment by miukki** [comment]
problem was if you set Restrict Access  to protect your alchemy api key , you will  get such error.. do not forget add here
<img width="737" alt="image" src="https://user-images.githubusercontent.com/132497/225234213-2c77ca5e-f280-4f5a-b247-d162e089715d.png"> ALLOWLIST IPS
