### ISSUE TITLE
can not verify contract hm.. [fixed]

### ISSUE THREAD

**Issue by miukki** [NomicFoundation/hardhat#3779]
### Version of Hardhat

2.13.0

### What happened?

I received this error today and can not verify contract... 
```
npx hardhat verify --network goerli --constructor-args arguments.js 0xE8e8d015B999674c7576786eb146CFB17c8035C2
An unexpected error occurred:

SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at consumeEnd (/Users/aishmukh/Projects/testdeploy/node_modules/undici/lib/api/readable.js:253:20)
    at BodyReadable.<anonymous> (/Users/aishmukh/Projects/testdeploy/node_modules/undici/lib/api/readable.js:235:7)
    at BodyReadable.emit (node:events:513:28)
    at BodyReadable.emit (/Users/aishmukh/Projects/testdeploy/node_modules/undici/lib/api/readable.js:66:18)
    at endReadableNT (node:internal/streams/readable:1358:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
                                                                                                                              
testdeploy git:master*  
❯ 
```

arguments.js:
```
module.exports = [
    ["0x1090C62B584c1c9a56E3D8AFd70cf9F2ECee17CC", "0x06f10E01E97718730179F53Bc6f8ff6625ACB2f1"],
    [5, 15],
    "https://ipfs.vipsland.com/nft/collections/genesis/json/hidden.json",
    "https://ipfs.vipsland.com/nft/collections/genesis/json/",
];
```

node version v16.18.1

hardhat.config.js:
```
require("@nomiclabs/hardhat-etherscan");
require("hardhat-contract-sizer");
require("dotenv").config();
require("@nomicfoundation/hardhat-toolbox");

const { GOERLI_ALCHEMY_API_KEY, GOERLI_PRIVATE_KEY, ETHERSCANAPIKEY } = process.env;


/** @type import('hardhat/config').HardhatUserConfig */

/** @type import('hardhat/config').HardhatUserConfig */
module.exports = {
  solidity: {
    version: '0.8.17',
    settings: {
      optimizer: {
        enabled: true,
        runs: 5
      }
    }
  },
  networks: {
    goerli: {
      url: `https://eth-goerli.g.alchemy.com/v2/${GOERLI_ALCHEMY_API_KEY}`,
      accounts: [GOERLI_PRIVATE_KEY],
      saveDeployments: true,
    },

  },
  
  etherscan: {
    apiKey: {
      goerli: ETHERSCANAPIKEY,
    },
    customChains: [
      {
        network: "goerli",
        chainId: 5,
        urls: {
          apiURL: "https://api-goerli.etherscan.io/api",
          browserURL: "https://goerli.etherscan.io"
        }
      }
    ]
  },

  contractSizer: {
    alphaSort: true,
    disambiguatePaths: false,
    runOnCompile: true,
    strict: true,
  }
};


```

### Minimal reproduction steps

```
npx hardhat run scripts/deploy.js --network goerli  
npx hardhat verify --network goerli --constructor-args arguments.js 0xE8e8d015B999674c7576786eb146CFB17c8035C2
```

### Search terms

verify contract issue

**Comment by miukki** [comment]
issue is fixed. when i isolated hardhat deployer package.json from  nextjs package.json.. just keep 2 separate repos.. 

works as expected

```
> npx hardhat --version
2.13.0

>npx hardhat run  ./scripts/deploy.js --network sepolia  

> npx hardhat run  ./scripts/verifyContract.js --network sepolia
``` 

packages
```
"devDependencies": {
    "@ethersproject/abi": "^5.7.0",
    "@ethersproject/providers": "^5.7.2",
    "@nomicfoundation/hardhat-chai-matchers": "^1.0.6",
    "@nomicfoundation/hardhat-network-helpers": "^1.0.8",
    "@nomicfoundation/hardhat-toolbox": "^2.0.2",
    "@nomiclabs/hardhat-ethers": "^2.2.2",
    "@nomiclabs/hardhat-etherscan": "^3.1.7",
    "@typechain/ethers-v5": "^10.2.0",
    "@typechain/hardhat": "^6.1.5",
    "chai": "^4.3.7",
    "dotenv": "^16.0.3",
    "ethers": "^5.7.2",
    "hardhat": "^2.13.0",
    "hardhat-gas-reporter": "^1.0.9",
    "solidity-coverage": "^0.8.2",
    "typechain": "^8.1.1"
  },
  "dependencies": {
    "@openzeppelin/contracts": "^4.8.2",
    "hardhat-contract-sizer": "^2.8.0"
  }
  ```

**Comment by fvictorio** [comment]
Glad you figured it out!
