### ISSUE TITLE
ProviderError: transaction would cause overdraft

### ISSUE THREAD

**Issue by alexisdavidson** [NomicFoundation/hardhat#3823]
### Version of Hardhat

2.8.4

### What happened?

When deploying on Goerli, I got this error. Everything was working fine one day ago. I tried multiple different wallets and couldn't fint anything on Google

ProviderError: transaction would cause overdraft
    at HttpProvider.request (...\node_modules\hardhat\src\internal\core\providers\http.ts:88:21)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at EthersProviderWrapper.send (...\node_modules\@nomiclabs\hardhat-ethers\src\internal\ethers-provider-wrapper.ts:13:20)

### Minimal reproduction steps

Just deploy something on Goerli

**Comment by fvictorio** [comment]
> ### Minimal reproduction steps
> Just deploy something on Goerli

I deployed something to Goerli and didn't get your issue.

Tentatively closing, will re-open if you can provide more detailed reproduction steps.
