### ISSUE TITLE
TypeError [ERR_INVALID_URL]

### ISSUE THREAD

**Issue by Confucian-PUT** [NomicFoundation/hardhat#3829]
### Version of Hardhat

2.13.0

### What happened?

When I run `npx hardhat run scripts/deploy.ts --network polygonMumbai`, it shows an error:
But my RPC url is correct.

`TypeError [ERR_INVALID_URL]: Invalid URL https://matic.getblock.io
    at new NodeError (node:internal/errors:399:5)
    at URL.onParseError (node:internal/url:566:9)
    at new URL (node:internal/url:646:5)
    at new ProxyAgent (/home/confucian/dev/eth-projects/USDT-ERC20/node_modules/undici/lib/proxy-agent.js:77:25)
    at new HttpProvider (/home/confucian/dev/eth-projects/USDT-ERC20/node_modules/hardhat/src/internal/core/providers/http.ts:65:28)
    at createProvider (/home/confucian/dev/eth-projects/USDT-ERC20/node_modules/hardhat/src/internal/core/providers/construction.ts:127:23)
    at /home/confucian/dev/eth-projects/USDT-ERC20/node_modules/hardhat/src/internal/core/runtime-environment.ts:96:28
    at getRealTarget (/home/confucian/dev/eth-projects/USDT-ERC20/node_modules/hardhat/src/internal/util/lazy.ts:112:22)
    at Object.get (/home/confucian/dev/eth-projects/USDT-ERC20/node_modules/hardhat/src/internal/util/lazy.ts:185:26)
    at createProviderProxy (/home/confucian/dev/eth-projects/USDT-ERC20/node_modules/@nomiclabs/hardhat-ethers/src/internal/provider-proxy.ts:25:19) {
  input: '192.168.2.143:1080',
  code: 'ERR_INVALID_URL'
}`

### Minimal reproduction steps

Run `npx hardhat run scripts/deploy.ts --network polygonMumbai`

**Comment by Confucian-PUT** [comment]
fixed
