### ISSUE TITLE
EACCES: permission denied, mkdir '/root/.config/hardhat-nodejs' 

### ISSUE THREAD

**Issue by pavankv241** [NomicFoundation/hardhat#3897]
**Description :-**
when i try to compile and test this error occuring please give solution . Even i test other projects through hardhat it's giving error like this .

npx hardhat compile  --show-stack-traces                                                             
Solidity 0.8.19 is not fully supported yet. You can still use Hardhat, but some features, like stack traces, might not work correctly.

Learn more at https://hardhat.org/hardhat-runner/docs/reference/solidity-support

An unexpected error occurred:

Error: EACCES: permission denied, mkdir '/root/.config/hardhat-nodejs'
    at Object.mkdirSync (node:fs:1336:3)
    at Object.mkdirsSync (/home/vasu/Desktop/Gravita-SmartContracts/node_modules/fs-extra/lib/mkdirs/mkdirs-sync.js:31:9)
    at getConfigDirSync (/home/vasu/Desktop/Gravita-SmartContracts/node_modules/hardhat/src/internal/util/global-dir.ts:22:6)
    at hasConsentedTelemetry (/home/vasu/Desktop/Gravita-SmartContracts/node_modules/hardhat/src/internal/util/global-dir.ts:105:21)
    at main (/home/vasu/Desktop/Gravita-SmartContracts/node_modules/hardhat/src/internal/cli/cli.ts:208:70)
    at Object.<anonymous> (/home/vasu/Desktop/Gravita-SmartContracts/node_modules/hardhat/src/internal/cli/cli.ts:377:1)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  errno: -13,
  syscall: 'mkdir',
  code: 'EACCES',
  path: '/root/.config/hardhat-nodejs'
}

**Comment by pavankv241** [comment]
### Resloved by below command . 

```
mkdir ~/.npm-global
npm config set prefix '~/.npm-global'
export PATH=~/.npm-global/bin:$PATH
source ~/.profile
```
