### ISSUE TITLE
TransactionExecutionError: Too Many Requests error received

### ISSUE THREAD

**Issue by FournyP** [NomicFoundation/hardhat#4053]
### Version of Hardhat

2.15.0

### What happened?

While writting my unit tests, I get the following errors for the lasts :
```
TransactionExecutionError: Too Many Requests error received from bsc-testnet.public.blastapi.io
      at HardhatNode.mineBlock (C:\Lab\Solidity\protocol-6022\node_modules\hardhat\src\internal\hardhat-network\provider\node.ts:529:15)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async HardhatNode._mineBlocksUntilTransactionIsIncluded (C:\Lab\Solidity\protocol-6022\node_modules\hardhat\src\internal\hardhat-network\provider\node.ts:1690:20)
      at async HardhatNode._mineTransactionAndPending (C:\Lab\Solidity\protocol-6022\node_modules\hardhat\src\internal\hardhat-network\provider\node.ts:1669:16)  
      at async EthModule._sendTransactionAndReturnHash (C:\Lab\Solidity\protocol-6022\node_modules\hardhat\src\internal\hardhat-network\provider\modules\eth.ts:1532:18)
      at async HardhatNetworkProvider.request (C:\Lab\Solidity\protocol-6022\node_modules\hardhat\src\internal\hardhat-network\provider\provider.ts:123:18)       
      at async HardhatEthersSigner.sendTransaction (C:\Lab\Solidity\protocol-6022\node_modules\@nomicfoundation\hardhat-ethers\src\signers.ts:125:18)
      at async ContractFactory.deploy (C:\Lab\Solidity\protocol-6022\node_modules\ethers\src.ts\contract\factory.ts:111:24)
      at async deployController6022AndCollectionGeneratorAndTokenFixture (C:\Lab\Solidity\protocol-6022\test\Controller6022.ts:12:28)
      at async loadFixture (C:\Lab\Solidity\protocol-6022\node_modules\@nomicfoundation\hardhat-network-helpers\src\loadFixture.ts:47:18)

      Caused by: ProviderError: Too Many Requests error received from bsc-testnet.public.blastapi.io
          at HttpProvider._fetchJsonRpcResponse (C:\Lab\Solidity\protocol-6022\node_modules\hardhat\src\internal\core\providers\http.ts:212:15)
          at processTicksAndRejections (node:internal/process/task_queues:96:5)
          at async HttpProvider.sendBatch (C:\Lab\Solidity\protocol-6022\node_modules\hardhat\src\internal\core\providers\http.ts:126:30)
          at async JsonRpcClient._sendBatch (C:\Lab\Solidity\protocol-6022\node_modules\hardhat\src\internal\hardhat-network\jsonrpc\client.ts:377:14)
          at async JsonRpcClient._performBatch (C:\Lab\Solidity\protocol-6022\node_modules\hardhat\src\internal\hardhat-network\jsonrpc\client.ts:332:24)
          at async JsonRpcClient.getAccountData (C:\Lab\Solidity\protocol-6022\node_modules\hardhat\src\internal\hardhat-network\jsonrpc\client.ts:197:21)        
          at async ForkStateManager.getAccount (C:\Lab\Solidity\protocol-6022\node_modules\hardhat\src\internal\hardhat-network\provider\fork\ForkStateManager.ts:125:27)
          at async EVM._executeCreate (C:\Lab\Solidity\protocol-6022\node_modules\@nomicfoundation\ethereumjs-evm\src\evm.ts:438:21)
          at async EVM.runCall (C:\Lab\Solidity\protocol-6022\node_modules\@nomicfoundation\ethereumjs-evm\src\evm.ts:772:16)
          at async VM._runTx (C:\Lab\Solidity\protocol-6022\node_modules\@nomicfoundation\ethereumjs-vm\src\runTx.ts:380:20)
```

I understand that there is too much requests make to the local blockchain, but there is no documentation on how to bypass this problem (https://hardhat.org/hardhat-runner/docs/errors)

Or maybe there is a configuration to set ?

Have a good day ;)

### Minimal reproduction steps

Make a lot of requests in unit tests

**Comment by FournyP** [comment]
Pour ceux qui rencontre le même problème, c'est parce que je forkais the bsc testnet like this in my configuration :
```
networks: {
  hardhat: {
    forking: {
      url: "https://bsc-testnet.public.blastapi.io",
    },
  },
},
```

Just remove these configuration and it will work

Sorry for the mistake

Have a good day ;)
