### ISSUE TITLE
rodar comando

### ISSUE THREAD

**Issue by tianopo** [NomicFoundation/hardhat#4213]
### Version of Hardhat

2.17.0

### What happened?

estou tentando rodar o comando "NODE_OPTIONS=--trace-deprecation ts-node-dev -r tsconfig-paths/register --respawn --transpile-only --exit-child --watch src/**/*{!.test,!.spec}.ts src/index.ts"
porém está dando o seguinte erro no terminal: HardhatError: HH5: HardhatContext is not created.
    at Function.getHardhatContext (/root/Matheus/colmeah_back/node_modules/hardhat/src/internal/context.ts:38:13)
    at extendEnvironment (/root/Matheus/colmeah_back/node_modules/hardhat/src/internal/core/config/config-env.ts:129:30)
    at Object.<anonymous> (/root/Matheus/colmeah_back/node_modules/@nomicfoundation/hardhat-ethers/src/internal/index.ts:19:18)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._compile (/root/Matheus/colmeah_back/node_modules/source-map-support/source-map-support.js:568:25)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at require.extensions..jsx.require.extensions..js (/tmp/ts-node-dev-hook-2206839388010038.js:114:20)
    at Object.nodeDevHook [as .js] (/root/Matheus/colmeah_back/node_modules/ts-node-dev/lib/hook.js:63:13)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Function.Module._load (node:internal/modules/cjs/loader:958:12)
[ERROR] 14:19:48 HardhatError: HH5: HardhatContext is not created.
Child got SIGTERM, exiting.

por qual razão?

### Minimal reproduction steps

diitei acima em português

**Comment by schaable** [comment]
Hi @tianopo, can you expand on what are you trying to do? Can you provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)?
