### ISSUE TITLE
Artifact for contract "ERC20PermitMock" not found

### ISSUE THREAD

**Issue by abhijeetbhagat** [NomicFoundation/hardhat#4368]
### Version of Hardhat

2.17.2

### What happened?

my script:
```
const provider = ethers.getDefaultProvider("some goerli rpc"); // set goerli RPC node
const privateKey = "some private key"; // From wallet.txt Trusted sequencer
const wallet = new ethers.Wallet(privateKey, provider);

const maticTokenFactory = await ethers.getContractFactory(
  "ERC20PermitMock",
  provider
);
maticTokenContract = maticTokenFactory.attach("some address"); // From ~/zkevm/zkevm-contract/deployments/goerly_***/deploy_output.json maticTokenAddress
maticTokenContractWallet = maticTokenContract.connect(wallet);
await maticTokenContractWallet.approve("some address", ethers.utils.parseEther("100.0")); // From ~/zkevm/zkevm-contract/deployments/goerly_***/deploy_output.json polygonZkEVMAddress
```

my `hardhat.config.js`:
```
require("@nomicfoundation/hardhat-toolbox");
require("@nomicfoundation/hardhat-ethers");
~
/** @type import('hardhat/config').HardhatUserConfig */
module.exports = {
  solidity: "0.8.19",
};
```

the error:
```
root@zkevm-supernet:/opt/approve-matic# npx hardhat run script.js

/opt/node_modules/hardhat/src/internal/artifacts.ts:733
    throw new HardhatError(ERRORS.ARTIFACTS.NOT_FOUND, {
          ^
HardhatError: HH700: Artifact for contract "ERC20PermitMock" not found.
    at Artifacts._handleWrongArtifactForContractName (/opt/node_modules/hardhat/src/internal/artifacts.ts:733:11)
    at Artifacts._getArtifactPathFromFiles (/opt/node_modules/hardhat/src/internal/artifacts.ts:864:19)
    at Artifacts._getArtifactPath (/opt/node_modules/hardhat/src/internal/artifacts.ts:522:21)
    at Artifacts.readArtifact (/opt/node_modules/hardhat/src/internal/artifacts.ts:71:26)
    at getContractFactory (/opt/node_modules/@nomicfoundation/hardhat-ethers/src/internal/helpers.ts:107:22)
    at main (/opt/approve-matic/script.js:6:28)
```

### Minimal reproduction steps

1. create a hardhat javascript project
2. create a script file - script.js - and paste the above script in it
3. `npx hardhat run script.js` from the root of the project.

**Comment by fvictorio** [comment]
This happens because you don't have a contract named `ERC20PermitMock` in your project.

**Comment by abhijeetbhagat** [comment]
not sure why you closed it, but that contract is indeed deployed on goerli: https://goerli.etherscan.io/address/0x4701aa9471d7bfac765d87dcb1ea6bb23ad32733#code
