### ISSUE TITLE
The Hardhat Network tracing engine could not be initialized. ContractsIdentifier failed to be initialized

### ISSUE THREAD

**Issue by gdnathan** [NomicFoundation/hardhat#4609]
### Version of Hardhat

2.19.1

### What happened?

I know that this issue have been arised already, but unless I'm mistaken all of them didn't concern v2.19.1.
Here is the full log:

```
  hardhat:core:hre Creating provider for network hardhat +57ms
The Hardhat Network tracing engine could not be initialized. Run Hardhat with --verbose to learn more.
  hardhat:core:hardhat-network:node Hardhat Network tracing disabled: ContractsIdentifier failed to be initialized. Please report this to help us improve Hardhat.
  hardhat:core:hardhat-network:node  TypeError: Cannot read properties of undefined (reading 'content')
    at createSourcesModelFromAst (/home/erudyx/l1x/x_talk_contracts/eth-contracts/node_modules/hardhat/src/internal/hardhat-network/stack-traces/compiler-to-model.ts:90:41)
    at createModelsAndDecodeBytecodes (/home/erudyx/l1x/x_talk_contracts/eth-contracts/node_modules/hardhat/src/internal/hardhat-network/stack-traces/compiler-to-model.ts:47:3)
    at new HardhatNode (/home/erudyx/l1x/x_talk_contracts/eth-contracts/node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:427:57)
    at Function.create (/home/erudyx/l1x/x_talk_contracts/eth-contracts/node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:287:18)
    at HardhatNetworkProvider._init (/home/erudyx/l1x/x_talk_contracts/eth-contracts/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:260:28)
    at HardhatNetworkProvider._send (/home/erudyx/l1x/x_talk_contracts/eth-contracts/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:198:5)
    at HardhatNetworkProvider.request (/home/erudyx/l1x/x_talk_contracts/eth-contracts/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:124:18)
    at getSigners (/home/erudyx/l1x/x_talk_contracts/eth-contracts/node_modules/@nomicfoundation/hardhat-ethers/src/internal/helpers.ts:43:30)
    at Context.<anonymous> (/home/erudyx/l1x/x_talk_contracts/eth-contracts/tests/L1XBridge.tests.js:11:29) +0ms

```

### Minimal reproduction steps

This is my storages (I put it there because it was the cause of the issue in previous opened issues)

```
    mapping(address => uint256) public signer_transaction;
    address[] public authorized_signers;
    mapping(address => uint256) public pending_authorized_signers;
    mapping(address => uint256) public pending_removal_signers;
```

**Comment by schaable** [comment]
Hi @gdnathan, I tested this by creating a contract with that storage, and running a `hardhat node` along with the deploy script and tests, but didn't find any errors. I'm closing this issue for now as it seems non-reproducible, but please reopen it with more details if you're still facing the problem.

**Comment by gdnathan** [comment]
Hi @schaable ,
I tried to reproduce it, and it look like I'm getting the same error, even if my contract is totally empty, so I believe it might come from my installation of hardhat

**Comment by schaable** [comment]
ah, that sounds like a totally different issue. Try creating a new hardhat sample project and see if it happens there as well.
