### ISSUE TITLE
Revert data is treated as a function result data and results in `invalid length for result data` error 

### ISSUE THREAD

**Issue by mmv08** [NomicFoundation/hardhat#4645]
### Version of Hardhat

hardhat 2.19.1/ethers 6.9.0

### What happened?

I have the following test that checks that the contract function was reverted with a custom error:
https://github.com/wtree-id/offchain-resolver/blob/99c142a1aa5778c7ad7a6cf91654831ea90a409c/packages/contracts/test/OffchainResolver.test.ts#L82-L99
(Contains some debugging artifacts)
It passes just fine in the original repo, which uses ethers 5.7.2 and hardhat 2.12.1:
https://github.com/ensdomains/offchain-resolver/blob/efb7c02eb8f8fc02a222cd055f9c055919b7a5ae/packages/contracts/test/TestOffchainResolver.js#L49-L53

However, in my updated test file, the test fails with the following error:
```
Error: invalid length for result data (value="0x556f18300000000000000000000000000165878a594ca255338adfa4d48449f69242eb8f00000000000000000000000000000000000000000000000000000000000000a00000000000000000000000000000000000000000000000000000000000000120f4d4d2f8000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000016687474703a2f2f6c6f63616c686f73743a383038302f0000000000000000000000000000000000000000000000000000000000000000000000000000000000a49061b92300000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000000a047465737403657468000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a49061b92300000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000000a0474657374036574680000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000", info={ "method": "resolve", "signature": "resolve(bytes,bytes)" }, code=BAD_DATA, version=6.9.0)
      at makeError (/Users/mmv/Projects/wtree/offchain-resolver/node_modules/ethers/src.ts/utils/errors.ts:694:21)
      at assert (/Users/mmv/Projects/wtree/offchain-resolver/node_modules/ethers/src.ts/utils/errors.ts:715:25)
      at Interface.decodeFunctionResult (/Users/mmv/Projects/wtree/offchain-resolver/node_modules/ethers/src.ts/abi/interface.ts:917:20)
      at staticCallResult (/Users/mmv/Projects/wtree/offchain-resolver/node_modules/ethers/src.ts/contract/contract.ts:349:57)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async staticCall (/Users/mmv/Projects/wtree/offchain-resolver/node_modules/ethers/src.ts/contract/contract.ts:303:24)
      at async Proxy.resolve (/Users/mmv/Projects/wtree/offchain-resolver/node_modules/ethers/src.ts/contract/contract.ts:352:16)
```

I debugged it a little bit, and I believe the reason for this is that ethers tries to interpret this as a function result data, and not as an error (`0x556f1830` is a signature for `OffchainLookup(address,string[],bytes,bytes4,bytes)`. I found this function in `ethers`:
https://github.com/ethers-io/ethers.js/blob/98910ba01efa774710eefa5a6a5836a8b271c654/src.ts/contract/contract.ts#L328-L347

It looks like the runner (which should be Hardhat's provider) didn't throw an error, and the function execution continued, and it called the `decodeFunctionResult` function.

Any help would be appreciated.

Could be similar to https://github.com/NomicFoundation/hardhat/issues/3438

### Minimal reproduction steps

1. Clone https://github.com/wtree-id/offchain-resolver at `e14000d9c8d35d5e44dff234255fbd9304834f7f`
2. `npm i`
3. `npm run test -w @ensdomains/offchain-resolver-contracts`
4. The test should fail

### Search terms

invalid length for result data

**Comment by mmv08** [comment]
Goddammit, the project had `throwOnCallFailures` set to false. I found it out when I looked at hardhat's internal provider... 🤦 🤦 🤦
