### ISSUE TITLE
Support for OpenBSD

### ISSUE THREAD

**Issue by vtamara** [NomicFoundation/hardhat#4712]
### Describe the feature

With OpenBSD/adJ 7.4 I can create a new Javascript project with:

       npx hardhat

But trying to compile produce the following error:

```
% npx hardhat compile
An unexpected error occurred:

Error: Unsupported OS: openbsd, architecture: x64
    at Object.<anonymous> (/home/vtamara/comp/x1/p1/node_modules/@nomicfoundation/solidity-analyzer/index.js:252:11)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Function.Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Parser.parse (/home/vtamara/comp/x1/p1/node_modules/hardhat/src/internal/solidity/parse.ts:34:9)
    at Resolver._resolveFile (/home/vtamara/comp/x1/p1/node_modules/hardhat/src/internal/solidity/resolver.ts:430:40)
    at Resolver.resolveSourceName (/home/vtamara/comp/x1/p1/node_modules/hardhat/src/internal/solidity/resolver.ts:98:22)
```

**Comment by vtamara** [comment]
I could do compile by editing running:

    cd node_modules/@nomicfoundation/solidity-analyzer
    vi index.js

Adding this section:
```
  case "openbsd":                                                                                                                                               
    if (arch !== "x64") {                                                                                                                                       
      throw new Error(`Unsupported architecture on OpenBSD: ${arch}`);                                                                                          
    }                                                                                                                                                           
    localFileExisted = existsSync(                                                                                                                              
      join(__dirname, "solidity-analyzer.openbsd-x64.node")                                                                                                     
    );                                                                                                                                                          
    try {                                                                                                                                                       
      if (localFileExisted) {                                                                                                                                   
        nativeBinding = require("./solidity-analyzer.openbsd-x64.node");                                                                                        
      } else {                                                                                                                                                  
        nativeBinding = require("@nomicfoundation/solidity-analyzer-openbsd-x64");                                                                              
      }                                                                                                                                                         
    } catch (e) {                                                                                                                                               
      loadError = e;                                                                                                                                            
    }                                                                                                                                                           
    break;                 
```

Installing rust with `pkg_add rust` And compiling with

    yarn
    yarn build

That process generated the attached binary.

[solidity-analyzer.openbsd-x64.node.zip](https://github.com/NomicFoundation/hardhat/files/13767040/solidity-analyzer.openbsd-x64.node.zip)

**Comment by fvictorio** [comment]
Blocked by https://github.com/NomicFoundation/solidity-analyzer/issues/17 which in turn is blocked by https://github.com/napi-rs/napi-rs/issues/1183

**Comment by vtamara** [comment]
Hey @schaable @fvictorio is it possible to have support for OpenBSD/adJ in Hardhat 3?

Today I tried the example at: https://hardhat.org/hardhat3-alpha with npm

```sh
% mkdir hardhat-example
% cd hardhat-example
% npx hardhat@next --init
```
Works, but `npx hardhat --help` produces:

```
Error: Unsupported OS: openbsd, architecture: x64
    at Object.<anonymous> (/home/vtamara/comp/hardhat/h3-npm/node_modules/@nomicfoundation/edr/index.js:303:11)
    at Module._compile (node:internal/modules/cjs/loader:1730:14)
    at Object..js (node:internal/modules/cjs/loader:1895:10)
    at Module.load (node:internal/modules/cjs/loader:1465:32)
    at Function._load (node:internal/modules/cjs/loader:1282:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:235:24)
    at cjsLoader (node:internal/modules/esm/translators:266:5)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:200:7)
    at ModuleJob.run (node:internal/modules/esm/module_job:274:25)
```
