### ISSUE TITLE
`Invalid source name` when trying to import openzeppelin inside a monorepo

### ISSUE THREAD

**Issue by fvictorio** [NomicFoundation/hardhat#4734]
### Discussed in https://github.com/NomicFoundation/hardhat/discussions/4729

<div type='discussions-op-text'>

<sup>Originally posted by **SebastienGllmt** January  4, 2024</sup>
# Goal

use `@openzeppelin/contracts` within a package in my monorepo

# Error

I have a monorepo, and one of my packages is my evm contracts folder
```
root
    - node_modules
    - packages
        - evm-contracts
            - hardhat.config.ts
            - package.json
        - app
```

I want to use `@openzeppelin/contracts` from inside my package and use `foundry` so I've done the following:
1. I installed `@openzeppelin/contracts` and `@openzeppelin/contracts-upgradeable`
2. I installed `@nomicfoundation/hardhat-foundry`

Now, since dependencies for my project are hoisted to the root of the repository, I've set the following foundry configuration: `@openzeppelin/=../../../node_modules/@openzeppelin/`

This works and now foundry compiles. However, when I run `npx hardhat compile` I get the following error

```
HardhatError: HH1001: Invalid source name ../../../node_modules/@openzeppelin/contracts/token/ERC20/ERC20.sol. Expected source name but found a relative path.
    at validateSourceNameFormat (my-project/node_modules/hardhat/src/utils/source-names.ts:27:11)
    at Resolver.resolveSourceName (my-project/node_modules/hardhat/src/internal/solidity/resolver.ts:97:15)
    at Resolver.resolveImport (my-project/node_modules/hardhat/src/internal/solidity/resolver.ts:197:35)
    at async my-project/node_modules/hardhat/src/internal/solidity/dependencyGraph.ts:188:28
    at async Promise.all (index 0)
    at async DependencyGraph._addDependenciesFrom (my-project/node_modules/hardhat/src/internal/solidity/dependencyGraph.ts:186:5)
    at async Promise.all (index 0)
    at async Function.createFromResolvedFiles (my-project/node_modules/hardhat/src/internal/solidity/dependencyGraph.ts:15:5)
    at async Environment._runTaskDefinition (my-project/node_modules/hardhat/src/internal/core/runtime-environment.ts:358:14)
    at async Environment.run (my-project/node_modules/hardhat/src/internal/core/runtime-environment.ts:191:14)
```

# Debugging

I tried to debug the [resolveSourceName](https://github.com/NomicFoundation/hardhat/blob/7630646422deb62f5d082ff4d80c0271ea87d5f8/packages/hardhat-core/src/internal/solidity/resolver.ts#L85) function in `hardhat-core` and found the following:
1. The input to the function is `sourceName: "@openzeppelin/contracts/token/ERC20/ERC20.sol"`
2. This gets updated to `remappedSourceName: "../../../node_modules/@openzeppelin/contracts/token/ERC20/ERC20.sol"`
3. It then crashes on the `validateSourceNameFormat` call in this function

Notably, this fails because [validateSourceNameFormat explicitly disallows relative paths](https://github.com/NomicFoundation/hardhat/blob/7630646422deb62f5d082ff4d80c0271ea87d5f8/packages/hardhat-core/src/utils/source-names.ts#L26)

# Question

If relative paths are explicitly disabled, is there another way I can use `@openzeppelin/contracts` together with `hardhat` within my monorepo?

To be clear, removing `import '@nomicfoundation/hardhat-foundry';` in my hardhat config solves the issue.

Possibly related: https://github.com/NomicFoundation/hardhat/issues/4194 mentioned the remapping not being detected. In my case, it's definitely being detected (but the fact it's being used is breaking things)</div>

**Comment by j-h-scheufen** [comment]
FYI, running into the same problem. A monorepo setup where the "contracts" package is using Hardhat and Foundry. However, the hoisting of dependencies to <root>/node_modules presents challenges. I can only get one of the two (HH or Foundry) to compile successfully. hardhat-foundry stumples on the remappings with relative paths pointing to the project root.
Removing `@nomicfoundation/hardhat-foundry` from hardhat.config.ts solves the problems.

**Comment by pseudobun** [comment]
By removing `@nomicfoundation/hardhat-foundry` from `hardhat.config.ts` as @j-h-scheufen suggested, my `.t.sol` tests with foundry fail. I tried using `bun` at first and had the same issues but managed to solve them by transitioning to `pnpm`-based monorepo instead. With `pnpm`, dependencies and `node_modules` folders are installed in each respective package root and both hardhat and forge don't have any problem finding them. For detailed configs you can take a look at my repo here https://github.com/pseudobun/onchain-issuer.

**Comment by j-h-scheufen** [comment]
> By removing `@nomicfoundation/hardhat-foundry` from `hardhat.config.ts`, as @j-h-scheufen suggested, my `.t.sol` tests with Foundry fail. I tried using `bun` at first and had the same issues, but managed to solve them by transitioning to a `pnpm`-based monorepo instead. With `pnpm`, dependencies/`node_modules` are installed in each respective package root, and both Hardhat and Forge can find them. For detailed configs, you can take a look at my repo here: https://github.com/pseudobun/onchain-issuer.

Thanks for posting another workaround!
As a follow-up to my prior remarks: I'm letting yarn make the decisions on which level of the monorepo the "node_modules" get installed. But to make sure I cover all scenarios, I had to add the monorepo root folder location to the `foundry.toml`:
```
libs = ['lib', 'node_modules', '../../node_modules']
```

**Comment by clauBv23** [comment]
I’m experiencing the same issue.

For now, removing `import '@nomicfoundation/hardhat-foundry';` from the Hardhat configuration file seems to resolve it for me.
