### ISSUE TITLE
The custom error thrown by viem publicClient.readContract cannot be used in tests

### ISSUE THREAD

**Issue by xxxijustwei** [NomicFoundation/hardhat#4870]
### Version of Hardhat

2.19.5

### What happened?
repo: https://github.com/xxxijustwei/erc721-diamond

```solidity
// SPDX-License-Identifier: MIT
// OpenZeppelin Contracts (last updated v5.0.0) (interfaces/draft-IERC6093.sol)
pragma solidity ^0.8.18;

library ERC721Errors {
    error ERC721InvalidOwner(address owner);

    error ERC721NonexistentToken(uint256 tokenId);

    error ERC721IncorrectOwner(address sender, uint256 tokenId, address owner);

    error ERC721InvalidSender(address sender);

    error ERC721InvalidReceiver(address receiver);

    error ERC721InsufficientApproval(address operator, uint256 tokenId);

    error ERC721InvalidApprover(address approver);

    error ERC721InvalidOperator(address operator);

    error ERC721OutOfBoundsIndex(address owner, uint256 index);

    error ERC721EnumerableForbiddenBatchMint();
}

```

test code:
```ts
describe('when querying the zero address', function () {
    it('throws', async function () {
        const errors = await hre.viem.getContractAt("ERC721Errors", this.contractAddress);
        await expect(
            this.publicClient.readContract({
            address: this.erc721Contract.address,
            abi: this.erc721Contract.abi,
            functionName: "balanceOf",
            args: [zeroAddress],
        })
    )
        .to.be.revertedWithCustomError(errors, 'ERC721InvalidOwner')
        .withArgs(zeroAddress);
    });
});
```
result:
```text
  1) ERC721
       with mited tokens
         balanceOf
           when querying the zero address
             throws:
     TypeError: The first argument of .revertedWithCustomError must be the contract that defines the custom error
      at validateInput (node_modules/@nomicfoundation/hardhat-chai-matchers/src/internal/reverted/revertedWithCustomError.ts:161:13)
      at Proxy.<anonymous> (node_modules/@nomicfoundation/hardhat-chai-matchers/src/internal/reverted/revertedWithCustomError.ts:41:46)
      at Proxy.methodWrapper (node_modules/chai/lib/chai/utils/addMethod.js:57:25)
      at Context.<anonymous> (test/erc721.behavior.ts:83:32)
```

### Minimal reproduction steps

see `What happened?`

### Search terms

viem

**Comment by schaable** [comment]
The issue here is that you're trying to use `hardhat-chai-matchers` along with `viem`, which the plugin currently does not support. Although, I skimmed through the docs, and there's no mention of this. I've added issues to [make this explicit in the documentation](https://github.com/NomicFoundation/hardhat/issues/4871) and [track interest in making `hardhat-chai-matchers` library-agnostic](https://github.com/NomicFoundation/hardhat/issues/4874).
