### ISSUE TITLE
`hardhat_setBalance` on contracts is reverting with  "Contract with code hash `0x...` does not exist"

### ISSUE THREAD

**Issue by bugduino** [NomicFoundation/hardhat#4984]
### Version of Hardhat

2.21.0

### What happened?

Hi, I have an old repo which was recently updated to hardhat >= 2.17.3 as I needed to have shanghai evm version (currently at 2.21.0) and I'm running a script in eth mainnet fork.
Everything seems to be working fine except for `hardhat_setBalance` which is now constantly halting script execution.
I've tried many different versions >= 2.17.3 but it always reverts on the hardhat_setBalance

This is the trace using `loggingEnabled: true`:

```
hardhat_setBalance [THIS IS IN RED]

  Contract with code hash `0xaea7d4252f6245f301e540cfbee27d3a88de543af8e49c5c62405d5499fab7e5` does not exist.

An unexpected error occurred:

ProviderError: Contract with code hash `0xaea7d4252f6245f301e540cfbee27d3a88de543af8e49c5c62405d5499fab7e5` does not exist.
    at EdrProviderWrapper.request (/idle/idle-proposals/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:424:19)
    at SimpleTaskDefinition.action (/idle/idle-proposals/scripts/execute-proposal-or-simulate.ts:19:7)
    at Environment._runTaskDefinition (/idle/idle-proposals/node_modules/hardhat/src/internal/core/runtime-environment.ts:359:14)
    at Environment.run (/idle/idle-proposals/node_modules/hardhat/src/internal/core/runtime-environment.ts:192:14)
    at SimpleTaskDefinition.action (/idle/idle-proposals/scripts/iip-39.ts:113:3)
    at Environment._runTaskDefinition (/idle/idle-proposals/node_modules/hardhat/src/internal/core/runtime-environment.ts:359:14)
    at Environment.run (/idle/idle-proposals/node_modules/hardhat/src/internal/core/runtime-environment.ts:192:14)
    at main (/idle/idle-proposals/node_modules/hardhat/src/internal/cli/cli.ts:323:7)
```

I'm not sure why ```ProviderError: Contract with code hash `0xaea7d4252f6245f301e540cfbee27d3a88de543af8e49c5c62405d5499fab7e5` does not exist.``` is even thrown honestly. If I use other methods to set the balance (eg transfer funds from another address) it works as expected.

### Minimal reproduction steps

- clone https://github.com/Idle-Finance/idle-proposals/pull/22
- `npx hardhat iip-39` (`ALCHEMY_API_KEY` needs to be set in the env)
- script will halt here https://github.com/Idle-Finance/idle-proposals/blob/main/scripts/execute-proposal-or-simulate.ts#L21

**Comment by bugduino** [comment]
Minimal test on our repo:

https://github.com/Idle-Finance/idle-proposals/blob/688e35c603f08afc45b554e9a21215b172165fe7/scripts/utilities.ts

```
npx hardhat set-balance-test
```

**Comment by bugduino** [comment]
This apparently happens only when calling `hardhat_setBalance` on a contract address rather than an EOA, if I set balance on EOA it works. This behaviour was working previously though

**Comment by Wodann** [comment]
Thank you for the detailed bug report. I was able to reproduce the issue and implemented a [fix](https://github.com/NomicFoundation/hardhat/pull/5000). We'll try to ship a bug fix release as soon as possible.
