### ISSUE TITLE
Hardhat was'nt initialized

### ISSUE THREAD

**Issue by Rizalliza** [NomicFoundation/hardhat#5546]
### Version of Hardhat

10.7.0

### What happened?

i can't connect to sepolia testnet, always giving error. here's the error code =   _stack: 'HardhatError: HH5: HardhatContext is not created.\n' +
    '    at HardhatContext.getHardhatContext (/Users/qistina/Desktop/Abah/BlkMan/node_modules/hardhat/internal/context.js:38:19)\n' +
    '    at extendEnvironment (/Users/qistina/Desktop/Abah/BlkMan/node_modules/hardhat/internal/core/config/config-env.js:72:42)\n' +
    '    at Object.<anonymous> (/Users/qistina/Desktop/Abah/BlkMan/node_modules/@nomiclabs/hardhat-ethers/internal/index.js:13:32)\n' +
    '    at Module._compile (node:internal/modules/cjs/loader:1358:14)\n' +
    '    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)\n' +
    '    at Module.load (node:internal/modules/cjs/loader:1208:32)\n' +
    '    at Module._load (node:internal/modules/cjs/loader:1024:12)\n' +
    '    at Module.require (node:internal/modules/cjs/loader:1233:19)\n' +
    '    at require (node:internal/modules/helpers:179:18)\n' +
    '    at Object.<anonymous> (/Users/qistina/Desktop/Abah/BlkMan/node_modules/@nomiclabs/hardhat-waffle/dist/src/index.js:3:1)',
  errorDescriptor: {
    number: 5,
    message: 'HardhatContext is not created.',
    title: "Hardhat wasn't initialized",
    description: 'Hardhat initialization failed. This is a bug.\n' +
      '\n' +
      'Please [report it](https://github.com/nomiclabs/hardhat/issues/new) to help us improve Hardhat.',
    shouldBeReported: true
  },
  number: 5,
  messageArguments: {},
  _isHardhatError: true
}

### Minimal reproduction steps

no idea.

**Comment by ChristopherDedominici** [comment]
Hi @Rizalliza, Hardhat does not have a version 10.7.0. This is probably a typo. Could you try using the [latest Hardhat version](https://www.npmjs.com/package/hardhat) to connect to Sepolia and see if it works? Thanks.

**Comment by ChristopherDedominici** [comment]
Closing because of no activity in the last 2 weeks
