### ISSUE TITLE
Hardhat compile aborts

### ISSUE THREAD

**Issue by doerfli** [NomicFoundation/hardhat#5752]
### Version of Hardhat

2.22.10

### What happened?

Running `hh compile` brings up this error
```
Solidity 0.8.26 is not fully supported yet. You can still use Hardhat, but some features, like stack traces, might not work correctly.

Learn more at https://hardhat.org/hardhat-runner/docs/reference/solidity-support

An unexpected error occurred:

Error: Command failed: /usr/local/bin/node /workspaces/gif-next/node_modules/hardhat/internal/solidity/compiler/solcjs-runner.js /home/node/.cache/hardhat-nodejs/compilers-v2/wasm/soljson-v0.8.26+commit.8a97fa7a.js
Aborted()
RuntimeError: Aborted(). Build with -sASSERTIONS for more info.
    at abort (/home/node/.cache/hardhat-nodejs/compilers-v2/wasm/soljson-v0.8.26+commit.8a97fa7a.js:110:7480)
    at _abort (/home/node/.cache/hardhat-nodejs/compilers-v2/wasm/soljson-v0.8.26+commit.8a97fa7a.js:110:18516)
    at invoke_v (/home/node/.cache/hardhat-nodejs/compilers-v2/wasm/soljson-v0.8.26+commit.8a97fa7a.js:110:38411)
    at wasm://wasm/0551ebc6:wasm-function[142]:0x2775e
    at wasm://wasm/0551ebc6:wasm-function[42983]:0x13a969a
    at ccall (/home/node/.cache/hardhat-nodejs/compilers-v2/wasm/soljson-v0.8.26+commit.8a97fa7a.js:110:28937)
    at /home/node/.cache/hardhat-nodejs/compilers-v2/wasm/soljson-v0.8.26+commit.8a97fa7a.js:110:29328
    at runWithCallbacks (/workspaces/gif-next/node_modules/solc/bindings/compile.js:169:18)
    at Object.boundFunctionStandard [as compileStandard] (/workspaces/gif-next/node_modules/solc/bindings/compile.js:83:20)
    at compileStandardWrapper (/workspaces/gif-next/node_modules/solc/wrapper.js:66:24)

    at genericNodeError (node:internal/errors:984:15)
    at wrappedFn (node:internal/errors:538:14)
    at ChildProcess.exithandler (node:child_process:422:12)
    at ChildProcess.emit (node:events:519:28)
    at ChildProcess.emit (node:domain:488:12)
    at maybeClose (node:internal/child_process:1105:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:305:5) {
  code: 1,
  killed: false,
  signal: null,
  cmd: '/usr/local/bin/node /workspaces/gif-next/node_modules/hardhat/internal/solidity/compiler/solcjs-runner.js /home/node/.cache/hardhat-nodejs/compilers-v2/wasm/soljson-v0.8.26+commit.8a97fa7a.js'
}

```

It happens inside a linux based devcontainer instance running on a macbook. This setup has been running like this for months without any issues. All of a sudden this happens since last week. 

node runtime version: v20.17.0
hardhat version: 2.22.10
forge version: forge 0.2.0 (280aa26 2024-09-16T00:21:36.170507215Z)

### Minimal reproduction steps

1. Checkout repository https://github.com/etherisc/gif-next
2. Use VSCode to open devcontainer 
3. Run `git submodule update --init --recursive` to get submodules
4. Run `hh compile`

### Search terms

compile build Aborted solc

**Comment by doerfli** [comment]
I've just found the issue. After writing the ticket the idea came and it reason was having the entry `@gif-next=contracts/` in remappings.txt

**Comment by doerfli** [comment]
I was able to break it down to the commit where the problem starts happening: https://github.com/etherisc/gif-next/commit/f0d9a15c7ff9f301aec2fbcec60916d86c022d32?diff=split&w=0#diff-3c548fe5d18247b979e5f35cb097855b6242d9019bb7117f90587760e9ca5ad9
And strangely it only happens in the devcontainer, the github action that also runs a `hh compile` runs flawless. It must be some change in `contracts/*` because `hh compile` doesn't compile the other stuff. Is there any way to get more details on what the reason for the compilation issue is?

**Comment by doerfli** [comment]
I have an update to this: i did some more digging and it turns out that to the best of my knowledge, this somehow is an issue with the osx hypervisor for arm64 linux images. 🤯  since it only happened on the devcontainer which runs locally on my mac and is backed by Orbstack (an alternative docker daemon) i've decided to fire up a plain linux, checkout the project and build it (like github runner does) ... same error. Then i did the same with a x86 image (Orbstack supports running x86 images) ... tada works!

No actually i have no idea how to handle this. I think it might be an issue with the osx vm hypervisor, but still there is the strange effect that one old commit works (the one right before `f0d9a15`) and after that commit it doesn't. To the best of my knowledge the commit just contains basic solidity code. 

I think it would be really helpful to get some more insight on what exactly goes wrong during the compilation. Thanks!

**Comment by doerfli** [comment]
I've got an update on the node base image i use today and now i get a proper error message that shows that happens
```
⬢ [Docker] ❯ hh compile           
Solidity 0.8.26 is not fully supported yet. You can still use Hardhat, but some features, like stack traces, might not work correctly.

Learn more at https://hardhat.org/hardhat-runner/docs/reference/solidity-support

Downloading compiler 0.8.26
Downloading compiler 0.8.26
An unexpected error occurred:

Error: Command failed: /usr/local/bin/node /workspaces/gif-next/node_modules/hardhat/internal/solidity/compiler/solcjs-runner.js /home/node/.cache/hardhat-nodejs/compilers-v2/wasm/soljson-v0.8.26+commit.8a97fa7a.js
RuntimeError: memory access out of bounds
    at wasm://wasm/0551ebc6:wasm-function[992]:0x3ce2f
    at wasm://wasm/0551ebc6:wasm-function[148]:0x27927
    at invoke_ii (/home/node/.cache/hardhat-nodejs/compilers-v2/wasm/soljson-v0.8.26+commit.8a97fa7a.js:110:37961)
    at wasm://wasm/0551ebc6:wasm-function[42983]:0x13a68af
    at ccall (/home/node/.cache/hardhat-nodejs/compilers-v2/wasm/soljson-v0.8.26+commit.8a97fa7a.js:110:28937)
    at /home/node/.cache/hardhat-nodejs/compilers-v2/wasm/soljson-v0.8.26+commit.8a97fa7a.js:110:29328
    at runWithCallbacks (/workspaces/gif-next/node_modules/solc/bindings/compile.js:169:18)
    at Object.boundFunctionStandard [as compileStandard] (/workspaces/gif-next/node_modules/solc/bindings/compile.js:83:20)
    at compileStandardWrapper (/workspaces/gif-next/node_modules/solc/wrapper.js:66:24)
    at main (/workspaces/gif-next/node_modules/hardhat/internal/solidity/compiler/solcjs-runner.js:26:23)

    at genericNodeError (node:internal/errors:984:15)
    at wrappedFn (node:internal/errors:538:14)
    at ChildProcess.exithandler (node:child_process:422:12)
    at ChildProcess.emit (node:events:519:28)
    at ChildProcess.emit (node:domain:488:12)
    at maybeClose (node:internal/child_process:1105:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:305:5) {
  code: 1,
  killed: false,
  signal: null,
  cmd: '/usr/local/bin/node /workspaces/gif-next/node_modules/hardhat/internal/solidity/compiler/solcjs-runner.js /home/node/.cache/hardhat-nodejs/compilers-v2/wasm/soljson-v0.8.26+commit.8a97fa7a.js'
}
```
