### ISSUE TITLE
Error while calling contract function

### ISSUE THREAD

**Issue by anurag-iitk** [NomicFoundation/hardhat#6075]
### Version of Hardhat

2.22.17

### What happened?

This is smart contract
```
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

contract CeroSharedSequence {
    error InvalidAddress();
    error CeroProxyAddressNotSet();
    error FailedToFetchBatch();
    address public proxyContractAddress;

    function setProxyContractAddress(address _proxyAddress) external {
        if (_proxyAddress == address(0)) {
            revert InvalidAddress();
        }
        proxyContractAddress = _proxyAddress;
    }

    function fetchBatches(uint256 batchIndex)
        external
        view
        returns (bytes32, uint64)
    {
        if (proxyContractAddress == address(0)) {
            revert CeroProxyAddressNotSet();
        }
        (bool success, bytes memory data) = proxyContractAddress.staticcall(
            abi.encodeWithSignature(
                "getBatchByRollupIdAndIndex(uint64,uint256)",
                1,
                batchIndex
            )
        );

        if (!success) {
            revert FailedToFetchBatch();
        }

        (bytes32 batchHash, uint64 timestamp) = abi.decode(
            data,
            (bytes32, uint64)
        );
        return (batchHash, timestamp);
    }
}

```

And this is my test script

```

import { expect } from "chai";
import { ethers } from "hardhat";

describe("CeroSharedSequence", function () {
  let owner: any;
  let ceroSharedSequence: any;
  const hardcodedProxyAddress = "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512";
  
  beforeEach(async function () {
    [owner] = await ethers.getSigners();
    const CeroSharedSequence = await ethers.getContractFactory("CeroSharedSequence");
    ceroSharedSequence = await CeroSharedSequence.deploy();
  });

  it("should set the proxy contract address to the hardcoded address", async function () {
    await ceroSharedSequence.setProxyContractAddress(hardcodedProxyAddress);
  });

  it("should fetch batches", async function () {
    await ceroSharedSequence.setProxyContractAddress(hardcodedProxyAddress);
    const batchIndex = 0;
    const trx = await ceroSharedSequence.fetchBatches(batchIndex);
    console.log(trx);
  });
});

```

### Minimal reproduction steps

While running the testcase got this issue
```
should fetch batches:
     Error: Transaction reverted and Hardhat couldn't infer the reason.
    at CeroSharedSequence.fetchBatches (contracts/Cero.sol:37)
    at CeroSharedSequence.fetchBatches (contracts/Cero.sol:37)
    at EdrProviderWrapper.request (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:444:41)
    at async staticCallResult (node_modules/ethers/src.ts/contract/contract.ts:337:22)
    at async staticCall (node_modules/ethers/src.ts/contract/contract.ts:303:24)
    at async Proxy.fetchBatches (node_modules/ethers/src.ts/contract/contract.ts:351:41)
    at async Context.<anonymous> (test/Lock.ts:22:17)
    ```
    
but it's working fine with remix

**Comment by sisco0** [comment]
It looks like the root cause is that, in your Hardhat environment, the address you’re passing (`0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512`) does **not** actually contain a contract that implements the function `getBatchByRollupIdAndIndex(uint64,uint256)`, causing the `staticcall` to fail. In Remix, you probably did deploy the correct contract and wired it up, so it worked there.

To fix this in _Hardhat_, you can deploy a quick mock (or your actual proxy contract) that includes the `getBatchByRollupIdAndIndex` function, then modify your test script to use the newly deployed mock’s address, like so:

```js
  const MockProxy = await ethers.getContractFactory("MockProxy");
  const mockProxy = await MockProxy.deploy();
  await mockProxy.waitForDeployment();

  await ceroSharedSequence.setProxyContractAddress(await mockProxy.getAddress());
```

**Comment by anurag-iitk** [comment]
I'm using Diamond Proxy Pattern and I've not deploy the proxy contract using remix. I've used same address ```0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512``` and pass it to setProxyContractAddress function. And it's work.
This address contract is in my other repository and above contract I've mentioned is in other repository. Any idea how can i do
@sisco0

**Comment by sisco0** [comment]
I would let other community members to provide a solution for your case @anurag-iitk .

**Comment by anurag-iitk** [comment]
@kanej

**Comment by kanej** [comment]
@anurag-iitk where you able to resolve your problem?
Were you running the tests with forking to pull in the proxy contract from a mainnet/testnet?
