### ISSUE TITLE
An error occurs when executing the “npx hardhat” command on Windows 11 arm64

### ISSUE THREAD

**Issue by huguojunsy** [NomicFoundation/hardhat#6096]
### Version of Hardhat

2.22.17

### What happened?

OS:windows 11 arm64(24H2 , 26100.2605)
An error occurs when executing the “npx hardhat” command on Windows 11 arm64:

C:\myproject\myweb3>npx hardhat
An unexpected error occurred:

Error: Cannot find module '@nomicfoundation/solidity-analyzer-win32-arm64-msvc'
Require stack:
- C:\myproject\myweb3\node_modules\@nomicfoundation\solidity-analyzer\index.js
- C:\myproject\myweb3\node_modules\@nomicfoundation\ignition-core\dist\src\verify.js
- C:\myproject\myweb3\node_modules\@nomicfoundation\ignition-core\dist\src\index.js
- C:\myproject\myweb3\node_modules\@nomicfoundation\hardhat-ignition\dist\src\index.js
- C:\myproject\myweb3\node_modules\@nomicfoundation\hardhat-ignition-ethers\dist\src\index.js
- C:\myproject\myweb3\node_modules\@nomicfoundation\hardhat-toolbox\index.js
- C:\myproject\myweb3\hardhat.config.ts
- C:\myproject\myweb3\node_modules\hardhat\internal\core\config\config-loading.js
- C:\myproject\myweb3\node_modules\hardhat\internal\cli\cli.js
- C:\myproject\myweb3\node_modules\hardhat\internal\cli\bootstrap.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1249:15)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (C:\myproject\myweb3\node_modules\@cspotcode\source-map-support\source-map-support.js:811:30)
    at Function.Module._load (node:internal/modules/cjs/loader:1075:27)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:219:24)
    at Module.require (node:internal/modules/cjs/loader:1340:12)
    at require (node:internal/modules/helpers:138:16)
    at Object.<anonymous> (C:\myproject\myweb3\node_modules\@nomicfoundation\solidity-analyzer\index.js:107:29)
    at Module._compile (node:internal/modules/cjs/loader:1565:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1708:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\myproject\\myweb3\\node_modules\\@nomicfoundation\\solidity-analyzer\\index.js',
    'C:\\myproject\\myweb3\\node_modules\\@nomicfoundation\\ignition-core\\dist\\src\\verify.js',
    'C:\\myproject\\myweb3\\node_modules\\@nomicfoundation\\ignition-core\\dist\\src\\index.js',
    'C:\\myproject\\myweb3\\node_modules\\@nomicfoundation\\hardhat-ignition\\dist\\src\\index.js',
    'C:\\myproject\\myweb3\\node_modules\\@nomicfoundation\\hardhat-ignition-ethers\\dist\\src\\index.js',
    'C:\\myproject\\myweb3\\node_modules\\@nomicfoundation\\hardhat-toolbox\\index.js',
    'C:\\myproject\\myweb3\\hardhat.config.ts',
    'C:\\myproject\\myweb3\\node_modules\\hardhat\\internal\\core\\config\\config-loading.js',
    'C:\\myproject\\myweb3\\node_modules\\hardhat\\internal\\cli\\cli.js',
    'C:\\myproject\\myweb3\\node_modules\\hardhat\\internal\\cli\\bootstrap.js'
  ]
}

### Minimal reproduction steps

npm init
npm install --save-dev hardhat
npx hardhat init
npx hardhat

**Comment by kanej** [comment]
Currently we are not supporting Windows on ARM. We have two underlying libraries that do not support Windows on ARM:

* EDR
* Solidity analyzer

We are investigating turning on Windows on ARM support for both, and will report back on this issue.

**Comment by kanej** [comment]
To give an update on this, EDR support for Windows on Arm is on our roadmap but is not just the configuration update we were hoping it was.
You should not expect Windows on Arm support in the next few months, given our prioritization of Hardhat 3.

**Comment by vbaraku** [comment]
Any updates on this. Thanks

**Comment by kanej** [comment]
No updates I am afraid. It is on our roadmap but we don't have a firm timeline.

**Comment by vbaraku** [comment]
Alright, thank you. There are workarounds to it, such as having the node running on WSL. So it is not a complete blocker.
