### ISSUE TITLE
Unexpected all the transactions of its network interaction were dropped

### ISSUE THREAD

**Issue by gionn** [NomicFoundation/hardhat#7555]
When not getting NomicFoundation/hardhat-ignition#664, I got this new error, however one tx creating one of the contracts is being emitted properly (can see it in the explorer), and it get repeated as well if I try to rerun deploy again.

```
Batch NomicFoundation/hardhat-ignition#1
  Executing MyModule#Deployer...
  Executing MyModule#PaymentSplitter...
  Executing MyModule#XercFactory...

An unexpected error occurred:

IgnitionError: IGN401: Error while executing MyModule#PaymentSplitter: all the transactions of its network interaction 1 were dropped. Please try rerunning Hardhat Ignition.
    at monitorOnchainInteraction (/home/gionn/src/xerc/node_modules/@nomicfoundation/ignition-core/src/internal/execution/future-processor/handlers/monitor-onchain-interaction.ts:88:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async FutureProcessor.processFuture (/home/gionn/src/xerc/node_modules/@nomicfoundation/ignition-core/src/internal/execution/future-processor/future-processor.ts:114:9)
    at async ExecutionEngine._executeBatch (/home/gionn/src/xerc/node_modules/@nomicfoundation/ignition-core/src/internal/execution/execution-engine.ts:148:30)
    at async ExecutionEngine.executeModule (/home/gionn/src/xerc/node_modules/@nomicfoundation/ignition-core/src/internal/execution/execution-engine.ts:109:25)
    at async Deployer.deploy (/home/gionn/src/xerc/node_modules/@nomicfoundation/ignition-core/src/internal/deployer.ts:194:25)
    at async SimpleTaskDefinition.action (/home/gionn/src/xerc/node_modules/@nomicfoundation/hardhat-ignition/src/index.ts:206:24)
    at async Environment._runTaskDefinition (/home/gionn/src/xerc/node_modules/hardhat/src/internal/core/runtime-environment.ts:358:14)
    at async Environment.run (/home/gionn/src/xerc/node_modules/hardhat/src/internal/core/runtime-environment.ts:191:14)
    at async main (/home/gionn/src/xerc/node_modules/hardhat/src/internal/cli/cli.ts:328:7)
```

**Comment by jacek0x** [comment]
> I am not sure. We have seen an issue when deploying via infura because it abstracts over different memory pools, so that transactions can apparently suddenly disappear. But we hadn't seen it against alchemy. We will need to dig in more. Is the repo you are using open source?

Not sure if this is related, but I'm seeing the following error on Alchemy.

![image](https://github.com/NomicFoundation/hardhat/assets/95072960/64ac88ac-e0ed-43a3-b692-7fe967991cf3)


```
{"jsonrpc":"2.0","id":2,"error":{"code":-32600,"message":"Unsupported method: hardhat_getAutomine. See available methods at https://docs.alchemy.com/alchemy/documentation/apis"}}
```
