### ISSUE TITLE
using forking on eth_call: `tx has a higher gas limit than the block`

### ISSUE THREAD

**Issue by dbeal-eth** [NomicFoundation/hardhat#983]
Given the following hardhat configuration segment:

```
{
  defaultNetwork: 'hardhat',

  networks: {
    hardhat: {
      blockGasLimit: 100000000,
      allowUnlimitedContractSize: true,
      forking: {
        url: `https://mainnet.infura.io/v3/${process.env.INFURA}`
      }
    }
}
```

where `INFURA` is set to a valid API key from their website.

If I run `npx hardhat node`, and in another terminal run an RPC query `eth_call` on any valid contract/function call, the terminal running the node prints out an error and the query fails:

```
eth_call
  Error: tx has a higher gas limit than the block
      at VM.runTx (/home/beald/code/node_modules/@nomiclabs/ethereumjs-vm/lib/runTx.ts:72:11)
      at VM.runTx (/home/beald/code/node_modules/@nomiclabs/ethereumjs-vm/lib/index.ts:172:28)
      at HardhatNode._runTxAndRevertMutations (/home/beald/code/node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:1411:29)
      at process._tickCallback (internal/process/next_tick.js:68:7)
```

When commenting out the line `blockGasLimit: 100000000` in the configuration above, the rpc call succeeds and returns as normal.

It is expected that a valid `eth_call` query should succeed with forking regardless of the setting of `blockGasLimit`.

**Comment by fvictorio** [comment]
I believe this doesn't happen anymore in the latest versions of Hardhat.
